import {
  FORBIDDEN,
  VALIDATION_400,
  nestDefaultError,
  ref,
  type RouteDefinition,
  type RoutePathParam,
} from "./route-registry-shared";

/** 13.21: the charity registry's routes. */
const CHARITY_ID: RoutePathParam = {
  name: "charityId",
  description: "A charity in the registry.",
  schema: { type: "string", format: "uuid" },
};
const NOT_FOUND = nestDefaultError(404, "No such charity in the caller's reach.");

export const CHARITY_ROUTE_DEFINITIONS: readonly RouteDefinition[] = [
  {
    method: "post",
    path: "/api/charities/applications",
    summary: "A foundation applies to the registry (simulated KYB check)",
    tags: ["charity"],
    pathParams: [],
    requestBody: { description: "The application.", schema: ref("CharityApplicationRequest") },
    successStatus: 201,
    successDescription: "The pending application, with the payout account masked.",
    successSchema: ref("CharityDetail"),
    errors: [
      VALIDATION_400,
      FORBIDDEN,
      nestDefaultError(422, "The simulated KYB check refused it."),
    ],
  },
  {
    method: "get",
    path: "/api/charities",
    summary: "Approved charities in the caller's region",
    tags: ["charity"],
    pathParams: [],
    successStatus: 200,
    successDescription: "Approved charities only.",
    successSchema: ref("PublicCharityList"),
    errors: [VALIDATION_400],
  },
  {
    method: "get",
    path: "/api/charities/{charityId}",
    summary: "One approved charity in the caller's region",
    tags: ["charity"],
    pathParams: [CHARITY_ID],
    successStatus: 200,
    successDescription: "The charity.",
    successSchema: ref("PublicCharity"),
    errors: [VALIDATION_400, NOT_FOUND],
  },
  {
    method: "get",
    path: "/api/me/charities",
    summary: "The caller's own applications and the charities they administer",
    tags: ["charity", "me"],
    pathParams: [],
    successStatus: 200,
    successDescription: "Newest first.",
    successSchema: ref("CharityDetailList"),
    errors: [FORBIDDEN],
  },
  {
    method: "get",
    path: "/api/charities/{charityId}/console",
    summary: "A charity's console: its proceeds and statements, never a balance",
    tags: ["charity"],
    pathParams: [CHARITY_ID],
    successStatus: 200,
    successDescription: "The charity with its proceeds and monthly statements.",
    successSchema: ref("CharityConsole"),
    errors: [FORBIDDEN, NOT_FOUND],
  },
  {
    method: "get",
    path: "/api/staff/charities",
    summary: "Every application in the registry, for review (ops)",
    tags: ["charity", "staff"],
    pathParams: [],
    successStatus: 200,
    successDescription: "Newest first, optionally one state.",
    successSchema: ref("CharityDetailList"),
    errors: [VALIDATION_400, FORBIDDEN],
  },
  {
    method: "post",
    path: "/api/staff/charities/{charityId}/decision",
    summary: "Approve or reject an application, with a reason (ops, audited)",
    tags: ["charity", "staff"],
    pathParams: [CHARITY_ID],
    requestBody: {
      description: "The decision and its reason.",
      schema: ref("CharityDecisionRequest"),
    },
    successStatus: 201,
    successDescription: "The decided charity.",
    successSchema: ref("CharityDetail"),
    errors: [VALIDATION_400, FORBIDDEN, NOT_FOUND, nestDefaultError(409, "Already decided.")],
  },
  {
    method: "get",
    path: "/api/staff/auctions",
    summary: "Every open charity auction, every region (ops, 13.22.g)",
    tags: ["auction", "staff"],
    pathParams: [],
    successStatus: 200,
    successDescription: "Soonest to end first. Who bid is never shown.",
    successSchema: ref("AuctionList"),
    errors: [FORBIDDEN],
  },
  {
    method: "post",
    path: "/api/staff/auctions/{auctionId}/cancel",
    summary:
      "Cancel an open auction with a reason: every hold released, voucher back to the seller (ops, audited)",
    tags: ["auction", "staff"],
    pathParams: [
      {
        name: "auctionId",
        description: "An open auction.",
        schema: { type: "string", format: "uuid" },
      },
    ],
    requestBody: {
      description: "The reason, for the audit trail.",
      schema: {
        type: "object",
        required: ["reason"],
        properties: { reason: { type: "string", minLength: 3, maxLength: 500 } },
      },
    },
    successStatus: 201,
    successDescription: "The cancelled auction.",
    successSchema: ref("Auction"),
    errors: [
      VALIDATION_400,
      FORBIDDEN,
      NOT_FOUND,
      nestDefaultError(409, "The auction is not open."),
    ],
  },
];
