packages:
  - 'apps/*'
  - 'packages/*'
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.2'
  - '@turbo/darwin-arm64@2.11.2'
  - '@turbo/linux-64@2.11.2'
  - '@turbo/linux-arm64@2.11.2'
  - '@turbo/windows-64@2.11.2'
  - '@turbo/windows-arm64@2.11.2'
  - '@types/node@26.6.2'
  - eslint@10.11.0
  - knip@6.37.0
  - turbo@2.11.2
