// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redeem.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFailedAttemptsSince = `-- name: CountFailedAttemptsSince :one
SELECT COUNT(*)::bigint AS failures
FROM voucher.redemption_attempt
WHERE merchant_id = $1 AND outcome <> 'authorized' AND occurred_at >= $2
`

type CountFailedAttemptsSinceParams struct {
	MerchantID pgtype.UUID
	OccurredAt pgtype.Timestamptz
}

// docs/09 section 10: "repeated invalid codes from one merchant is THE
// canonical signal of a compromised key or an enumeration attempt."
func (q *Queries) CountFailedAttemptsSince(ctx context.Context, arg CountFailedAttemptsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedAttemptsSince, arg.MerchantID, arg.OccurredAt)
	var failures int64
	err := row.Scan(&failures)
	return failures, err
}

const enableKillSwitch = `-- name: EnableKillSwitch :exec
INSERT INTO voucher.kill_switch (id, scope, scope_id, reason, enabled_by)
VALUES ($1, $2, $3, $4, $5)
`

type EnableKillSwitchParams struct {
	ID        pgtype.UUID
	Scope     string
	ScopeID   pgtype.UUID
	Reason    string
	EnabledBy string
}

func (q *Queries) EnableKillSwitch(ctx context.Context, arg EnableKillSwitchParams) error {
	_, err := q.db.Exec(ctx, enableKillSwitch,
		arg.ID,
		arg.Scope,
		arg.ScopeID,
		arg.Reason,
		arg.EnabledBy,
	)
	return err
}

const expireStaleHolds = `-- name: ExpireStaleHolds :many
UPDATE voucher.authorization
   SET state = 'expired', resolved_at = now()
 WHERE state = 'held' AND expires_at <= now()
RETURNING id, voucher_id
`

type ExpireStaleHoldsRow struct {
	ID        pgtype.UUID
	VoucherID pgtype.UUID
}

// The sweeper. Idempotent by construction: it only matches rows still
// 'held', so running it twice is a no-op, and not running it changes no
// decision because every read already filters on expires_at.
func (q *Queries) ExpireStaleHolds(ctx context.Context) ([]ExpireStaleHoldsRow, error) {
	rows, err := q.db.Query(ctx, expireStaleHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireStaleHoldsRow
	for rows.Next() {
		var i ExpireStaleHoldsRow
		if err := rows.Scan(&i.ID, &i.VoucherID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveCredential = `-- name: GetActiveCredential :one
SELECT key_id, merchant_id, wrapped_data_key, nonce, ciphertext, key_purpose,
       key_version, state, created_at, not_after, revoked_at
FROM voucher.merchant_credential
WHERE key_id = $1 AND state <> 'revoked'
  AND (not_after IS NULL OR not_after > now())
`

func (q *Queries) GetActiveCredential(ctx context.Context, keyID string) (VoucherMerchantCredential, error) {
	row := q.db.QueryRow(ctx, getActiveCredential, keyID)
	var i VoucherMerchantCredential
	err := row.Scan(
		&i.KeyID,
		&i.MerchantID,
		&i.WrappedDataKey,
		&i.Nonce,
		&i.Ciphertext,
		&i.KeyPurpose,
		&i.KeyVersion,
		&i.State,
		&i.CreatedAt,
		&i.NotAfter,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthorization = `-- name: GetAuthorization :one
SELECT id, voucher_id, merchant_id, amount_minor, currency, merchant_order_ref,
       state, expires_at, created_at, resolved_at
FROM voucher.authorization WHERE id = $1
`

// YT-0571 audit: no merchant predicate, by consideration rather than by
// omission. Both call sites resolve a client-supplied id against merchant
// ownership without this query's help — ownership.go's
// requireOwnedAuthorization fetches by id and compares merchant_id itself,
// which IS the boundary check this ticket says stays; release.go's Refund
// calls this with an authorization id it already reached through a
// capture that captureForReceipt resolved under a merchant predicate
// (GetCaptureByReceipt, below). Scoping this query too would need a
// merchant_id neither call site is wrong to be missing — the boundary
// check already does the comparison it exists to do, and the other caller
// never had an unscoped id in the first place.
func (q *Queries) GetAuthorization(ctx context.Context, id pgtype.UUID) (VoucherAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthorization, id)
	var i VoucherAuthorization
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.MerchantOrderRef,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAuthorizationForOrder = `-- name: GetAuthorizationForOrder :one
SELECT id, voucher_id, merchant_id, amount_minor, currency, merchant_order_ref,
       state, expires_at, created_at, resolved_at
FROM voucher.authorization WHERE merchant_id = $1 AND merchant_order_ref = $2
`

type GetAuthorizationForOrderParams struct {
	MerchantID       pgtype.UUID
	MerchantOrderRef string
}

// The replay path: a merchant retrying an authorize for the same order gets
// back the hold it already has, rather than a duplicate-key error it would
// have to interpret.
func (q *Queries) GetAuthorizationForOrder(ctx context.Context, arg GetAuthorizationForOrderParams) (VoucherAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthorizationForOrder, arg.MerchantID, arg.MerchantOrderRef)
	var i VoucherAuthorization
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.MerchantOrderRef,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getCapture = `-- name: GetCapture :one
SELECT id, authorization_id, authorized_amount_minor, amount_minor, receipt_id,
       settled_at, created_at
FROM voucher.capture WHERE id = $1
`

// YT-0571 audit: no merchant predicate, considered rather than silent. The
// only caller is Refund (release.go), and its capture id is never
// client-supplied — a merchant's refund call carries a receipt_id, resolved
// to this capture's id by captureForReceipt under a merchant predicate
// (GetCaptureByReceipt, below) before Refund ever runs. By the time this id
// reaches here it has already passed a scoped lookup once.
func (q *Queries) GetCapture(ctx context.Context, id pgtype.UUID) (VoucherCapture, error) {
	row := q.db.QueryRow(ctx, getCapture, id)
	var i VoucherCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.AuthorizedAmountMinor,
		&i.AmountMinor,
		&i.ReceiptID,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCaptureByReceipt = `-- name: GetCaptureByReceipt :one
SELECT c.id, c.authorization_id, c.authorized_amount_minor, c.amount_minor, c.receipt_id,
       c.settled_at, c.created_at
FROM voucher.capture c
JOIN voucher.authorization a ON a.id = c.authorization_id
WHERE c.receipt_id = $1 AND a.merchant_id = $2
`

type GetCaptureByReceiptParams struct {
	ReceiptID  string
	MerchantID pgtype.UUID
}

// ⚠️ YT-0571: `merchant_id = $2` closes the same hole as ResolveAuthorization,
// for the same reason — "refund-by-receipt has the same shape as capture."
// `voucher.capture` carries no merchant_id of its own, so this joins back to
// the authorization that owns it rather than trusting captureForReceipt's
// own boundary check (which stays) to be the only thing standing between a
// stranger's receipt_id guess and somebody else's settled transaction. A
// receipt from another merchant, real or guessed, now matches no row —
// the same `pgx.ErrNoRows` an unknown receipt already produced.
func (q *Queries) GetCaptureByReceipt(ctx context.Context, arg GetCaptureByReceiptParams) (VoucherCapture, error) {
	row := q.db.QueryRow(ctx, getCaptureByReceipt, arg.ReceiptID, arg.MerchantID)
	var i VoucherCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.AuthorizedAmountMinor,
		&i.AmountMinor,
		&i.ReceiptID,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO voucher.redemption_attempt (merchant_id, outcome, amount_minor)
VALUES ($1, $2, $3)
`

type InsertAttemptParams struct {
	MerchantID  pgtype.UUID
	Outcome     string
	AmountMinor *int64
}

// Every attempt, successful or not. Rows rather than a metric, for the same
// reason the Reward Engine counts velocity from its grant log: a control
// enforced against something lossy is not a control, and an evicted counter
// becomes free attempts for whoever notices first.
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt, arg.MerchantID, arg.Outcome, arg.AmountMinor)
	return err
}

const insertAuthorization = `-- name: InsertAuthorization :one
INSERT INTO voucher.authorization
  (id, voucher_id, merchant_id, amount_minor, currency, merchant_order_ref, state, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, 'held', $7)
RETURNING id, voucher_id, merchant_id, amount_minor, currency, merchant_order_ref,
          state, expires_at, created_at, resolved_at
`

type InsertAuthorizationParams struct {
	ID               pgtype.UUID
	VoucherID        pgtype.UUID
	MerchantID       pgtype.UUID
	AmountMinor      int64
	Currency         string
	MerchantOrderRef string
	ExpiresAt        pgtype.Timestamptz
}

// Places the hold. Two unique indexes do the work that no service check
// could: one live hold per voucher, and one authorization per merchant
// order. Both surface as unique violations, which the caller maps to
// distinct refusals — "that voucher is busy" and "you already authorized
// this order" need different answers at a till.
func (q *Queries) InsertAuthorization(ctx context.Context, arg InsertAuthorizationParams) (VoucherAuthorization, error) {
	row := q.db.QueryRow(ctx, insertAuthorization,
		arg.ID,
		arg.VoucherID,
		arg.MerchantID,
		arg.AmountMinor,
		arg.Currency,
		arg.MerchantOrderRef,
		arg.ExpiresAt,
	)
	var i VoucherAuthorization
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.MerchantOrderRef,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertCapture = `-- name: InsertCapture :one
INSERT INTO voucher.capture
  (id, authorization_id, authorized_amount_minor, amount_minor, receipt_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, authorization_id, authorized_amount_minor, amount_minor, receipt_id,
          settled_at, created_at
`

type InsertCaptureParams struct {
	ID                    pgtype.UUID
	AuthorizationID       pgtype.UUID
	AuthorizedAmountMinor int64
	AmountMinor           int64
	ReceiptID             string
}

// `authorized_amount_minor` is passed in and constrained by a COMPOSITE
// foreign key back to the authorization, so a caller cannot inflate it to
// justify a larger capture. See the migration.
func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) (VoucherCapture, error) {
	row := q.db.QueryRow(ctx, insertCapture,
		arg.ID,
		arg.AuthorizationID,
		arg.AuthorizedAmountMinor,
		arg.AmountMinor,
		arg.ReceiptID,
	)
	var i VoucherCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.AuthorizedAmountMinor,
		&i.AmountMinor,
		&i.ReceiptID,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO voucher.merchant_credential
  (key_id, merchant_id, wrapped_data_key, nonce, ciphertext, key_purpose, key_version, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active')
`

type InsertCredentialParams struct {
	KeyID          string
	MerchantID     pgtype.UUID
	WrappedDataKey []byte
	Nonce          []byte
	Ciphertext     []byte
	KeyPurpose     string
	KeyVersion     int32
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.KeyID,
		arg.MerchantID,
		arg.WrappedDataKey,
		arg.Nonce,
		arg.Ciphertext,
		arg.KeyPurpose,
		arg.KeyVersion,
	)
	return err
}

const insertRefund = `-- name: InsertRefund :exec
INSERT INTO voucher.refund (id, capture_id, amount_minor, reason)
VALUES ($1, $2, $3, $4)
`

type InsertRefundParams struct {
	ID          pgtype.UUID
	CaptureID   pgtype.UUID
	AmountMinor int64
	Reason      string
}

// The total is bounded by a deferred constraint trigger, not by this
// statement: "refunds must not exceed the capture" is a claim about a SET of
// rows, and a per-row check cannot make it.
func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) error {
	_, err := q.db.Exec(ctx, insertRefund,
		arg.ID,
		arg.CaptureID,
		arg.AmountMinor,
		arg.Reason,
	)
	return err
}

const isKilled = `-- name: IsKilled :one
SELECT EXISTS (
  SELECT 1 FROM voucher.kill_switch
   WHERE lifted_at IS NULL
     AND (scope = 'global'
          OR (scope = 'merchant' AND scope_id = $1)
          OR (scope = 'batch'    AND scope_id = $2))
)::boolean AS killed
`

type IsKilledParams struct {
	ScopeID   pgtype.UUID
	ScopeID_2 pgtype.UUID
}

// One query for all three scopes. In an incident the question is "is this
// stopped", and somebody answering it should not have to remember which of
// three tools covers the case in front of them.
func (q *Queries) IsKilled(ctx context.Context, arg IsKilledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isKilled, arg.ScopeID, arg.ScopeID_2)
	var killed bool
	err := row.Scan(&killed)
	return killed, err
}

const liftKillSwitch = `-- name: LiftKillSwitch :exec
UPDATE voucher.kill_switch SET lifted_by = $2, lifted_at = now()
 WHERE id = $1 AND lifted_at IS NULL
`

type LiftKillSwitchParams struct {
	ID       pgtype.UUID
	LiftedBy *string
}

// Lifting is recorded as a lift; rows are never deleted, so the timeline of
// an incident survives the incident.
func (q *Queries) LiftKillSwitch(ctx context.Context, arg LiftKillSwitchParams) error {
	_, err := q.db.Exec(ctx, liftKillSwitch, arg.ID, arg.LiftedBy)
	return err
}

const resolveAuthorization = `-- name: ResolveAuthorization :one
UPDATE voucher.authorization
   SET state = $2, resolved_at = now()
 WHERE id = $1 AND merchant_id = $3 AND state = 'held' AND expires_at > now()
RETURNING id, voucher_id, merchant_id, amount_minor, currency, merchant_order_ref,
          state, expires_at, created_at, resolved_at
`

type ResolveAuthorizationParams struct {
	ID         pgtype.UUID
	State      string
	MerchantID pgtype.UUID
}

// `state = 'held' AND expires_at > now()` is the whole expiry policy, applied
// at the moment of use rather than trusted to a sweeper. A sweeper that
// stopped running must not silently turn every hold into a permanent one —
// so an expired hold cannot be captured even while its row still says
// 'held', and the sweeper's only job is tidying.
//
// ⚠️ YT-0571: `merchant_id = $3` is the fix, not a hardening. Capture and
// Void resolve a CLIENT-SUPPLIED authorization id, and this query used to
// carry no merchant predicate at all — correct for the invariant the
// domain tests assert (an id is only ever handed back to the merchant that
// placed the hold), wrong the moment an HTTP client can supply the id.
// ownership.go's requireOwnedAuthorization is a boundary check and stays;
// this is the WHERE clause that makes the data safe on its own, for
// whatever calls this query next without going through that boundary. A
// wrong merchant and a wrong id now fail identically — both are
// `pgx.ErrNoRows`, mapped by the caller to the same ErrNoLiveHold — so this
// does not create a new distinguishable refusal.
func (q *Queries) ResolveAuthorization(ctx context.Context, arg ResolveAuthorizationParams) (VoucherAuthorization, error) {
	row := q.db.QueryRow(ctx, resolveAuthorization, arg.ID, arg.State, arg.MerchantID)
	var i VoucherAuthorization
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.MerchantOrderRef,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const revokeCredential = `-- name: RevokeCredential :exec
UPDATE voucher.merchant_credential SET state = 'revoked', revoked_at = now()
 WHERE key_id = $1
`

// Revocation is immediate — the half that matters in an incident.
func (q *Queries) RevokeCredential(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, revokeCredential, keyID)
	return err
}

const sumRefunds = `-- name: SumRefunds :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint AS refunded
FROM voucher.refund WHERE capture_id = $1
`

// YT-0571 audit: not called from any Go code yet — no caller to audit. When
// wired, capture_id must arrive the same way Refund's does: resolved from a
// receipt through GetCaptureByReceipt's merchant predicate, never accepted
// bare from a request body.
func (q *Queries) SumRefunds(ctx context.Context, captureID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumRefunds, captureID)
	var refunded int64
	err := row.Scan(&refunded)
	return refunded, err
}

const supersedeCredential = `-- name: SupersedeCredential :exec
UPDATE voucher.merchant_credential SET state = 'superseded', not_after = $2
 WHERE key_id = $1 AND state = 'active'
`

type SupersedeCredentialParams struct {
	KeyID    string
	NotAfter pgtype.Timestamptz
}

// Rotation with overlap: the old key keeps working until `not_after`,
// because a merchant cannot swap a key atomically across their own fleet and
// a rotation that took their till offline is one nobody would ever run.
func (q *Queries) SupersedeCredential(ctx context.Context, arg SupersedeCredentialParams) error {
	_, err := q.db.Exec(ctx, supersedeCredential, arg.KeyID, arg.NotAfter)
	return err
}
