/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552). Do not edit by hand.  `paths` covers every route the business module serves (apps/api/src/modules/business), hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the campaign and watch modules are separate, concurrently in-flight streams (YT-0101/YT-0120/YT-0548) this ticket did not give a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a business-module controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// CampaignFunderType Who is paying for a campaign's points: a partner's pre-purchased block, or the platform funding its own grants. They post to different contra accounts, so collapsing them would hide marketing spend inside funded issuance.
type CampaignFunderType string

// List of CampaignFunderType
const (
	CAMPAIGNFUNDERTYPE_PARTNER CampaignFunderType = "partner"
	CAMPAIGNFUNDERTYPE_MARKETING CampaignFunderType = "marketing"
)

// All allowed values of CampaignFunderType enum
var AllowedCampaignFunderTypeEnumValues = []CampaignFunderType{
	"partner",
	"marketing",
}

func (v *CampaignFunderType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CampaignFunderType(value)
	for _, existing := range AllowedCampaignFunderTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CampaignFunderType", value)
}

// NewCampaignFunderTypeFromValue returns a pointer to a valid CampaignFunderType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCampaignFunderTypeFromValue(v string) (*CampaignFunderType, error) {
	ev := CampaignFunderType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CampaignFunderType: valid values are %v", v, AllowedCampaignFunderTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CampaignFunderType) IsValid() bool {
	for _, existing := range AllowedCampaignFunderTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CampaignFunderType value
func (v CampaignFunderType) Ptr() *CampaignFunderType {
	return &v
}

type NullableCampaignFunderType struct {
	value *CampaignFunderType
	isSet bool
}

func (v NullableCampaignFunderType) Get() *CampaignFunderType {
	return v.value
}

func (v *NullableCampaignFunderType) Set(val *CampaignFunderType) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignFunderType) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignFunderType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignFunderType(val *CampaignFunderType) *NullableCampaignFunderType {
	return &NullableCampaignFunderType{value: val, isSet: true}
}

func (v NullableCampaignFunderType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignFunderType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

