/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiStaffModerationCampaignsCampaignIdApprovePost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffModerationCampaignsCampaignIdApprovePost201Response{}

// ApiStaffModerationCampaignsCampaignIdApprovePost201Response struct for ApiStaffModerationCampaignsCampaignIdApprovePost201Response
type ApiStaffModerationCampaignsCampaignIdApprovePost201Response struct {
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	BusinessId string `json:"businessId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Region string `json:"region"`
	Title string `json:"title"`
	Synopsis string `json:"synopsis"`
	Audience string `json:"audience"`
	ContentCategory string `json:"contentCategory"`
	LifecycleState string `json:"lifecycleState"`
	RejectionReason NullableString `json:"rejectionReason"`
	PosterUrl NullableString `json:"posterUrl"`
	TeaserUrl NullableString `json:"teaserUrl"`
}

type _ApiStaffModerationCampaignsCampaignIdApprovePost201Response ApiStaffModerationCampaignsCampaignIdApprovePost201Response

// NewApiStaffModerationCampaignsCampaignIdApprovePost201Response instantiates a new ApiStaffModerationCampaignsCampaignIdApprovePost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffModerationCampaignsCampaignIdApprovePost201Response(id string, businessId string, region string, title string, synopsis string, audience string, contentCategory string, lifecycleState string, rejectionReason NullableString, posterUrl NullableString, teaserUrl NullableString) *ApiStaffModerationCampaignsCampaignIdApprovePost201Response {
	this := ApiStaffModerationCampaignsCampaignIdApprovePost201Response{}
	this.Id = id
	this.BusinessId = businessId
	this.Region = region
	this.Title = title
	this.Synopsis = synopsis
	this.Audience = audience
	this.ContentCategory = contentCategory
	this.LifecycleState = lifecycleState
	this.RejectionReason = rejectionReason
	this.PosterUrl = posterUrl
	this.TeaserUrl = teaserUrl
	return &this
}

// NewApiStaffModerationCampaignsCampaignIdApprovePost201ResponseWithDefaults instantiates a new ApiStaffModerationCampaignsCampaignIdApprovePost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffModerationCampaignsCampaignIdApprovePost201ResponseWithDefaults() *ApiStaffModerationCampaignsCampaignIdApprovePost201Response {
	this := ApiStaffModerationCampaignsCampaignIdApprovePost201Response{}
	return &this
}

// GetId returns the Id field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetId(v string) {
	o.Id = v
}

// GetBusinessId returns the BusinessId field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetBusinessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessId, true
}

// SetBusinessId sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetBusinessId(v string) {
	o.BusinessId = v
}

// GetRegion returns the Region field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetRegion(v string) {
	o.Region = v
}

// GetTitle returns the Title field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetTitle(v string) {
	o.Title = v
}

// GetSynopsis returns the Synopsis field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetSynopsis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Synopsis
}

// GetSynopsisOk returns a tuple with the Synopsis field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetSynopsisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Synopsis, true
}

// SetSynopsis sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetSynopsis(v string) {
	o.Synopsis = v
}

// GetAudience returns the Audience field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetAudience() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetAudienceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audience, true
}

// SetAudience sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetAudience(v string) {
	o.Audience = v
}

// GetContentCategory returns the ContentCategory field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetContentCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentCategory
}

// GetContentCategoryOk returns a tuple with the ContentCategory field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetContentCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentCategory, true
}

// SetContentCategory sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetContentCategory(v string) {
	o.ContentCategory = v
}

// GetLifecycleState returns the LifecycleState field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetLifecycleState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LifecycleState
}

// GetLifecycleStateOk returns a tuple with the LifecycleState field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetLifecycleStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LifecycleState, true
}

// SetLifecycleState sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetLifecycleState(v string) {
	o.LifecycleState = v
}

// GetRejectionReason returns the RejectionReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetRejectionReason() string {
	if o == nil || o.RejectionReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.RejectionReason.Get()
}

// GetRejectionReasonOk returns a tuple with the RejectionReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetRejectionReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RejectionReason.Get(), o.RejectionReason.IsSet()
}

// SetRejectionReason sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetRejectionReason(v string) {
	o.RejectionReason.Set(&v)
}

// GetPosterUrl returns the PosterUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetPosterUrl() string {
	if o == nil || o.PosterUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.PosterUrl.Get()
}

// GetPosterUrlOk returns a tuple with the PosterUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetPosterUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PosterUrl.Get(), o.PosterUrl.IsSet()
}

// SetPosterUrl sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetPosterUrl(v string) {
	o.PosterUrl.Set(&v)
}

// GetTeaserUrl returns the TeaserUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetTeaserUrl() string {
	if o == nil || o.TeaserUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.TeaserUrl.Get()
}

// GetTeaserUrlOk returns a tuple with the TeaserUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) GetTeaserUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TeaserUrl.Get(), o.TeaserUrl.IsSet()
}

// SetTeaserUrl sets field value
func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) SetTeaserUrl(v string) {
	o.TeaserUrl.Set(&v)
}

func (o ApiStaffModerationCampaignsCampaignIdApprovePost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffModerationCampaignsCampaignIdApprovePost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["businessId"] = o.BusinessId
	toSerialize["region"] = o.Region
	toSerialize["title"] = o.Title
	toSerialize["synopsis"] = o.Synopsis
	toSerialize["audience"] = o.Audience
	toSerialize["contentCategory"] = o.ContentCategory
	toSerialize["lifecycleState"] = o.LifecycleState
	toSerialize["rejectionReason"] = o.RejectionReason.Get()
	toSerialize["posterUrl"] = o.PosterUrl.Get()
	toSerialize["teaserUrl"] = o.TeaserUrl.Get()
	return toSerialize, nil
}

func (o *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"businessId",
		"region",
		"title",
		"synopsis",
		"audience",
		"contentCategory",
		"lifecycleState",
		"rejectionReason",
		"posterUrl",
		"teaserUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffModerationCampaignsCampaignIdApprovePost201Response := _ApiStaffModerationCampaignsCampaignIdApprovePost201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiStaffModerationCampaignsCampaignIdApprovePost201Response)

	if err != nil {
		return err
	}

	*o = ApiStaffModerationCampaignsCampaignIdApprovePost201Response(varApiStaffModerationCampaignsCampaignIdApprovePost201Response)

	return err
}

type NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response struct {
	value *ApiStaffModerationCampaignsCampaignIdApprovePost201Response
	isSet bool
}

func (v NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response) Get() *ApiStaffModerationCampaignsCampaignIdApprovePost201Response {
	return v.value
}

func (v *NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response) Set(val *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffModerationCampaignsCampaignIdApprovePost201Response(val *ApiStaffModerationCampaignsCampaignIdApprovePost201Response) *NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response {
	return &NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response{value: val, isSet: true}
}

func (v NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffModerationCampaignsCampaignIdApprovePost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


