/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WalletSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletSummary{}

// WalletSummary GET /api/wallet: spendable, pending by unlock time, and expiring points. Points only, never a rate or a money value (4.9.d).  Rules NOT enforced by this schema (they cannot be expressed in JSON Schema, and are enforced only by the Zod schema in @yourtal/contracts):   - pendingPoints is the sum of pending.
type WalletSummary struct {
	Region Region `json:"region"`
	// Platform points. Always a whole number; there is no fractional point.
	AvailablePoints int64 `json:"availablePoints"`
	// Platform points. Always a whole number; there is no fractional point.
	PendingPoints int64 `json:"pendingPoints"`
	Pending []WalletPending `json:"pending"`
	// Platform points. Always a whole number; there is no fractional point.
	ExpiringPoints int64 `json:"expiringPoints"`
	ExpiringAt NullableTime `json:"expiringAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
}

type _WalletSummary WalletSummary

// NewWalletSummary instantiates a new WalletSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletSummary(region Region, availablePoints int64, pendingPoints int64, pending []WalletPending, expiringPoints int64, expiringAt NullableTime) *WalletSummary {
	this := WalletSummary{}
	this.Region = region
	this.AvailablePoints = availablePoints
	this.PendingPoints = pendingPoints
	this.Pending = pending
	this.ExpiringPoints = expiringPoints
	this.ExpiringAt = expiringAt
	return &this
}

// NewWalletSummaryWithDefaults instantiates a new WalletSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletSummaryWithDefaults() *WalletSummary {
	this := WalletSummary{}
	return &this
}

// GetRegion returns the Region field value
func (o *WalletSummary) GetRegion() Region {
	if o == nil {
		var ret Region
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *WalletSummary) GetRegionOk() (*Region, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *WalletSummary) SetRegion(v Region) {
	o.Region = v
}

// GetAvailablePoints returns the AvailablePoints field value
func (o *WalletSummary) GetAvailablePoints() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AvailablePoints
}

// GetAvailablePointsOk returns a tuple with the AvailablePoints field value
// and a boolean to check if the value has been set.
func (o *WalletSummary) GetAvailablePointsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailablePoints, true
}

// SetAvailablePoints sets field value
func (o *WalletSummary) SetAvailablePoints(v int64) {
	o.AvailablePoints = v
}

// GetPendingPoints returns the PendingPoints field value
func (o *WalletSummary) GetPendingPoints() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PendingPoints
}

// GetPendingPointsOk returns a tuple with the PendingPoints field value
// and a boolean to check if the value has been set.
func (o *WalletSummary) GetPendingPointsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingPoints, true
}

// SetPendingPoints sets field value
func (o *WalletSummary) SetPendingPoints(v int64) {
	o.PendingPoints = v
}

// GetPending returns the Pending field value
func (o *WalletSummary) GetPending() []WalletPending {
	if o == nil {
		var ret []WalletPending
		return ret
	}

	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value
// and a boolean to check if the value has been set.
func (o *WalletSummary) GetPendingOk() ([]WalletPending, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pending, true
}

// SetPending sets field value
func (o *WalletSummary) SetPending(v []WalletPending) {
	o.Pending = v
}

// GetExpiringPoints returns the ExpiringPoints field value
func (o *WalletSummary) GetExpiringPoints() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpiringPoints
}

// GetExpiringPointsOk returns a tuple with the ExpiringPoints field value
// and a boolean to check if the value has been set.
func (o *WalletSummary) GetExpiringPointsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiringPoints, true
}

// SetExpiringPoints sets field value
func (o *WalletSummary) SetExpiringPoints(v int64) {
	o.ExpiringPoints = v
}

// GetExpiringAt returns the ExpiringAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *WalletSummary) GetExpiringAt() time.Time {
	if o == nil || o.ExpiringAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ExpiringAt.Get()
}

// GetExpiringAtOk returns a tuple with the ExpiringAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WalletSummary) GetExpiringAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiringAt.Get(), o.ExpiringAt.IsSet()
}

// SetExpiringAt sets field value
func (o *WalletSummary) SetExpiringAt(v time.Time) {
	o.ExpiringAt.Set(&v)
}

func (o WalletSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["region"] = o.Region
	toSerialize["availablePoints"] = o.AvailablePoints
	toSerialize["pendingPoints"] = o.PendingPoints
	toSerialize["pending"] = o.Pending
	toSerialize["expiringPoints"] = o.ExpiringPoints
	toSerialize["expiringAt"] = o.ExpiringAt.Get()
	return toSerialize, nil
}

func (o *WalletSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"region",
		"availablePoints",
		"pendingPoints",
		"pending",
		"expiringPoints",
		"expiringAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletSummary := _WalletSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWalletSummary)

	if err != nil {
		return err
	}

	*o = WalletSummary(varWalletSummary)

	return err
}

type NullableWalletSummary struct {
	value *WalletSummary
	isSet bool
}

func (v NullableWalletSummary) Get() *WalletSummary {
	return v.value
}

func (v *NullableWalletSummary) Set(val *WalletSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletSummary(val *WalletSummary) *NullableWalletSummary {
	return &NullableWalletSummary{value: val, isSet: true}
}

func (v NullableWalletSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


