/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign{}

// ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign struct for ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign
type ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign struct {
	Id NullableString `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	BusinessId NullableString `json:"businessId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Region NullableString `json:"region"`
	Title NullableString `json:"title"`
	Synopsis NullableString `json:"synopsis"`
	Audience string `json:"audience"`
	ContentCategory string `json:"contentCategory"`
	LifecycleState string `json:"lifecycleState"`
	RejectionReason NullableString `json:"rejectionReason"`
	PosterUrl NullableString `json:"posterUrl"`
	TeaserUrl NullableString `json:"teaserUrl"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign

// NewApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign instantiates a new ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign(id NullableString, businessId NullableString, region NullableString, title NullableString, synopsis NullableString, audience string, contentCategory string, lifecycleState string, rejectionReason NullableString, posterUrl NullableString, teaserUrl NullableString) *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign {
	this := ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign{}
	this.Id = id
	this.BusinessId = businessId
	this.Region = region
	this.Title = title
	this.Synopsis = synopsis
	this.Audience = audience
	this.ContentCategory = contentCategory
	this.LifecycleState = lifecycleState
	this.RejectionReason = rejectionReason
	this.PosterUrl = posterUrl
	this.TeaserUrl = teaserUrl
	return &this
}

// NewApiStaffModerationCampaignsGet200ResponseItemsInnerCampaignWithDefaults instantiates a new ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffModerationCampaignsGet200ResponseItemsInnerCampaignWithDefaults() *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign {
	this := ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetId(v string) {
	o.Id.Set(&v)
}

// GetBusinessId returns the BusinessId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetBusinessId() string {
	if o == nil || o.BusinessId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BusinessId.Get()
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BusinessId.Get(), o.BusinessId.IsSet()
}

// SetBusinessId sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetBusinessId(v string) {
	o.BusinessId.Set(&v)
}

// GetRegion returns the Region field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetRegion() string {
	if o == nil || o.Region.Get() == nil {
		var ret string
		return ret
	}

	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// SetRegion sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetRegion(v string) {
	o.Region.Set(&v)
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}

	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// SetTitle sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetTitle(v string) {
	o.Title.Set(&v)
}

// GetSynopsis returns the Synopsis field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetSynopsis() string {
	if o == nil || o.Synopsis.Get() == nil {
		var ret string
		return ret
	}

	return *o.Synopsis.Get()
}

// GetSynopsisOk returns a tuple with the Synopsis field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetSynopsisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Synopsis.Get(), o.Synopsis.IsSet()
}

// SetSynopsis sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetSynopsis(v string) {
	o.Synopsis.Set(&v)
}

// GetAudience returns the Audience field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetAudience() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetAudienceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audience, true
}

// SetAudience sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetAudience(v string) {
	o.Audience = v
}

// GetContentCategory returns the ContentCategory field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetContentCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentCategory
}

// GetContentCategoryOk returns a tuple with the ContentCategory field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetContentCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentCategory, true
}

// SetContentCategory sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetContentCategory(v string) {
	o.ContentCategory = v
}

// GetLifecycleState returns the LifecycleState field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetLifecycleState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LifecycleState
}

// GetLifecycleStateOk returns a tuple with the LifecycleState field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetLifecycleStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LifecycleState, true
}

// SetLifecycleState sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetLifecycleState(v string) {
	o.LifecycleState = v
}

// GetRejectionReason returns the RejectionReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetRejectionReason() string {
	if o == nil || o.RejectionReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.RejectionReason.Get()
}

// GetRejectionReasonOk returns a tuple with the RejectionReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetRejectionReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RejectionReason.Get(), o.RejectionReason.IsSet()
}

// SetRejectionReason sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetRejectionReason(v string) {
	o.RejectionReason.Set(&v)
}

// GetPosterUrl returns the PosterUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetPosterUrl() string {
	if o == nil || o.PosterUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.PosterUrl.Get()
}

// GetPosterUrlOk returns a tuple with the PosterUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetPosterUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PosterUrl.Get(), o.PosterUrl.IsSet()
}

// SetPosterUrl sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetPosterUrl(v string) {
	o.PosterUrl.Set(&v)
}

// GetTeaserUrl returns the TeaserUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetTeaserUrl() string {
	if o == nil || o.TeaserUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.TeaserUrl.Get()
}

// GetTeaserUrlOk returns a tuple with the TeaserUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) GetTeaserUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TeaserUrl.Get(), o.TeaserUrl.IsSet()
}

// SetTeaserUrl sets field value
func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) SetTeaserUrl(v string) {
	o.TeaserUrl.Set(&v)
}

func (o ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	toSerialize["businessId"] = o.BusinessId.Get()
	toSerialize["region"] = o.Region.Get()
	toSerialize["title"] = o.Title.Get()
	toSerialize["synopsis"] = o.Synopsis.Get()
	toSerialize["audience"] = o.Audience
	toSerialize["contentCategory"] = o.ContentCategory
	toSerialize["lifecycleState"] = o.LifecycleState
	toSerialize["rejectionReason"] = o.RejectionReason.Get()
	toSerialize["posterUrl"] = o.PosterUrl.Get()
	toSerialize["teaserUrl"] = o.TeaserUrl.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"businessId",
		"region",
		"title",
		"synopsis",
		"audience",
		"contentCategory",
		"lifecycleState",
		"rejectionReason",
		"posterUrl",
		"teaserUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign := _ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign{}

	err = json.Unmarshal(data, &varApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign)

	if err != nil {
		return err
	}

	*o = ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign(varApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "businessId")
		delete(additionalProperties, "region")
		delete(additionalProperties, "title")
		delete(additionalProperties, "synopsis")
		delete(additionalProperties, "audience")
		delete(additionalProperties, "contentCategory")
		delete(additionalProperties, "lifecycleState")
		delete(additionalProperties, "rejectionReason")
		delete(additionalProperties, "posterUrl")
		delete(additionalProperties, "teaserUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign struct {
	value *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign
	isSet bool
}

func (v NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) Get() *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign {
	return v.value
}

func (v *NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) Set(val *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign(val *ApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) *NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign {
	return &NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign{value: val, isSet: true}
}

func (v NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffModerationCampaignsGet200ResponseItemsInnerCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


