/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
)

// checks if the ApiMePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMePatchRequest{}

// ApiMePatchRequest struct for ApiMePatchRequest
type ApiMePatchRequest struct {
	DisplayName *string `json:"displayName,omitempty"`
	DisplayLocale *string `json:"displayLocale,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApiMePatchRequest ApiMePatchRequest

// NewApiMePatchRequest instantiates a new ApiMePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMePatchRequest() *ApiMePatchRequest {
	this := ApiMePatchRequest{}
	return &this
}

// NewApiMePatchRequestWithDefaults instantiates a new ApiMePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMePatchRequestWithDefaults() *ApiMePatchRequest {
	this := ApiMePatchRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ApiMePatchRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMePatchRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ApiMePatchRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ApiMePatchRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayLocale returns the DisplayLocale field value if set, zero value otherwise.
func (o *ApiMePatchRequest) GetDisplayLocale() string {
	if o == nil || IsNil(o.DisplayLocale) {
		var ret string
		return ret
	}
	return *o.DisplayLocale
}

// GetDisplayLocaleOk returns a tuple with the DisplayLocale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMePatchRequest) GetDisplayLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayLocale) {
		return nil, false
	}
	return o.DisplayLocale, true
}

// HasDisplayLocale returns a boolean if a field has been set.
func (o *ApiMePatchRequest) HasDisplayLocale() bool {
	if o != nil && !IsNil(o.DisplayLocale) {
		return true
	}

	return false
}

// SetDisplayLocale gets a reference to the given string and assigns it to the DisplayLocale field.
func (o *ApiMePatchRequest) SetDisplayLocale(v string) {
	o.DisplayLocale = &v
}

func (o ApiMePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.DisplayLocale) {
		toSerialize["displayLocale"] = o.DisplayLocale
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiMePatchRequest) UnmarshalJSON(data []byte) (err error) {
	varApiMePatchRequest := _ApiMePatchRequest{}

	err = json.Unmarshal(data, &varApiMePatchRequest)

	if err != nil {
		return err
	}

	*o = ApiMePatchRequest(varApiMePatchRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "displayLocale")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiMePatchRequest struct {
	value *ApiMePatchRequest
	isSet bool
}

func (v NullableApiMePatchRequest) Get() *ApiMePatchRequest {
	return v.value
}

func (v *NullableApiMePatchRequest) Set(val *ApiMePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMePatchRequest(val *ApiMePatchRequest) *NullableApiMePatchRequest {
	return &NullableApiMePatchRequest{value: val, isSet: true}
}

func (v NullableApiMePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


