/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// BusinessTeamRole The job one person does inside one business (docs/17 section 2.1). Defined here rather than in @yourtal/authz because a member carries it in an API payload; authz imports it and keeps the drift test against the Cerbos principal schema (YT-0509). Store staff are absent by design — they are device sessions, not members.
type BusinessTeamRole string

// List of BusinessTeamRole
const (
	BUSINESSTEAMROLE_OWNER BusinessTeamRole = "owner"
	BUSINESSTEAMROLE_ADMIN BusinessTeamRole = "admin"
	BUSINESSTEAMROLE_MARKETER BusinessTeamRole = "marketer"
	BUSINESSTEAMROLE_MERCHANDISER BusinessTeamRole = "merchandiser"
	BUSINESSTEAMROLE_FINANCE BusinessTeamRole = "finance"
	BUSINESSTEAMROLE_ANALYST BusinessTeamRole = "analyst"
)

// All allowed values of BusinessTeamRole enum
var AllowedBusinessTeamRoleEnumValues = []BusinessTeamRole{
	"owner",
	"admin",
	"marketer",
	"merchandiser",
	"finance",
	"analyst",
}

func (v *BusinessTeamRole) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BusinessTeamRole(value)
	for _, existing := range AllowedBusinessTeamRoleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BusinessTeamRole", value)
}

// NewBusinessTeamRoleFromValue returns a pointer to a valid BusinessTeamRole
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBusinessTeamRoleFromValue(v string) (*BusinessTeamRole, error) {
	ev := BusinessTeamRole(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BusinessTeamRole: valid values are %v", v, AllowedBusinessTeamRoleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BusinessTeamRole) IsValid() bool {
	for _, existing := range AllowedBusinessTeamRoleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BusinessTeamRole value
func (v BusinessTeamRole) Ptr() *BusinessTeamRole {
	return &v
}

type NullableBusinessTeamRole struct {
	value *BusinessTeamRole
	isSet bool
}

func (v NullableBusinessTeamRole) Get() *BusinessTeamRole {
	return v.value
}

func (v *NullableBusinessTeamRole) Set(val *BusinessTeamRole) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessTeamRole) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessTeamRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessTeamRole(val *BusinessTeamRole) *NullableBusinessTeamRole {
	return &NullableBusinessTeamRole{value: val, isSet: true}
}

func (v NullableBusinessTeamRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessTeamRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

