/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the WatchProgressReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WatchProgressReport{}

// WatchProgressReport One span of playback a client claims to have played. `reportedAt` is the client's clock and is recorded for audit only: the server judges a report against its OWN clock, because a claim of more playback than time has passed is arithmetically impossible rather than merely suspicious.
type WatchProgressReport struct {
	SessionId string `json:"sessionId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	FromSeconds float32 `json:"fromSeconds"`
	ToSeconds float32 `json:"toSeconds"`
	ReportedAt time.Time `json:"reportedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _WatchProgressReport WatchProgressReport

// NewWatchProgressReport instantiates a new WatchProgressReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatchProgressReport(sessionId string, fromSeconds float32, toSeconds float32, reportedAt time.Time) *WatchProgressReport {
	this := WatchProgressReport{}
	this.SessionId = sessionId
	this.FromSeconds = fromSeconds
	this.ToSeconds = toSeconds
	this.ReportedAt = reportedAt
	return &this
}

// NewWatchProgressReportWithDefaults instantiates a new WatchProgressReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatchProgressReportWithDefaults() *WatchProgressReport {
	this := WatchProgressReport{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *WatchProgressReport) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *WatchProgressReport) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *WatchProgressReport) SetSessionId(v string) {
	o.SessionId = v
}

// GetFromSeconds returns the FromSeconds field value
func (o *WatchProgressReport) GetFromSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FromSeconds
}

// GetFromSecondsOk returns a tuple with the FromSeconds field value
// and a boolean to check if the value has been set.
func (o *WatchProgressReport) GetFromSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromSeconds, true
}

// SetFromSeconds sets field value
func (o *WatchProgressReport) SetFromSeconds(v float32) {
	o.FromSeconds = v
}

// GetToSeconds returns the ToSeconds field value
func (o *WatchProgressReport) GetToSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ToSeconds
}

// GetToSecondsOk returns a tuple with the ToSeconds field value
// and a boolean to check if the value has been set.
func (o *WatchProgressReport) GetToSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToSeconds, true
}

// SetToSeconds sets field value
func (o *WatchProgressReport) SetToSeconds(v float32) {
	o.ToSeconds = v
}

// GetReportedAt returns the ReportedAt field value
func (o *WatchProgressReport) GetReportedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReportedAt
}

// GetReportedAtOk returns a tuple with the ReportedAt field value
// and a boolean to check if the value has been set.
func (o *WatchProgressReport) GetReportedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportedAt, true
}

// SetReportedAt sets field value
func (o *WatchProgressReport) SetReportedAt(v time.Time) {
	o.ReportedAt = v
}

func (o WatchProgressReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WatchProgressReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionId"] = o.SessionId
	toSerialize["fromSeconds"] = o.FromSeconds
	toSerialize["toSeconds"] = o.ToSeconds
	toSerialize["reportedAt"] = o.ReportedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WatchProgressReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionId",
		"fromSeconds",
		"toSeconds",
		"reportedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWatchProgressReport := _WatchProgressReport{}

	err = json.Unmarshal(data, &varWatchProgressReport)

	if err != nil {
		return err
	}

	*o = WatchProgressReport(varWatchProgressReport)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sessionId")
		delete(additionalProperties, "fromSeconds")
		delete(additionalProperties, "toSeconds")
		delete(additionalProperties, "reportedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWatchProgressReport struct {
	value *WatchProgressReport
	isSet bool
}

func (v NullableWatchProgressReport) Get() *WatchProgressReport {
	return v.value
}

func (v *NullableWatchProgressReport) Set(val *WatchProgressReport) {
	v.value = val
	v.isSet = true
}

func (v NullableWatchProgressReport) IsSet() bool {
	return v.isSet
}

func (v *NullableWatchProgressReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatchProgressReport(val *WatchProgressReport) *NullableWatchProgressReport {
	return &NullableWatchProgressReport{value: val, isSet: true}
}

func (v NullableWatchProgressReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWatchProgressReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


