/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response{}

// ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response struct for ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response
type ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response struct {
	Question ApiTenantIdStudioCampaignsCampaignIdQuestionsPostRequest `json:"question"`
	Status string `json:"status"`
	PiiScreen NullableString `json:"piiScreen"`
	TimesAsked NullableInt32 `json:"timesAsked"`
	TimesCorrect NullableInt32 `json:"timesCorrect"`
	RetiredReason NullableString `json:"retiredReason"`
	AdditionalProperties map[string]interface{}
}

type _ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response

// NewApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response instantiates a new ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response(question ApiTenantIdStudioCampaignsCampaignIdQuestionsPostRequest, status string, piiScreen NullableString, timesAsked NullableInt32, timesCorrect NullableInt32, retiredReason NullableString) *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response {
	this := ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response{}
	this.Question = question
	this.Status = status
	this.PiiScreen = piiScreen
	this.TimesAsked = timesAsked
	this.TimesCorrect = timesCorrect
	this.RetiredReason = retiredReason
	return &this
}

// NewApiTenantIdStudioCampaignsCampaignIdQuestionsPost201ResponseWithDefaults instantiates a new ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTenantIdStudioCampaignsCampaignIdQuestionsPost201ResponseWithDefaults() *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response {
	this := ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response{}
	return &this
}

// GetQuestion returns the Question field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetQuestion() ApiTenantIdStudioCampaignsCampaignIdQuestionsPostRequest {
	if o == nil {
		var ret ApiTenantIdStudioCampaignsCampaignIdQuestionsPostRequest
		return ret
	}

	return o.Question
}

// GetQuestionOk returns a tuple with the Question field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetQuestionOk() (*ApiTenantIdStudioCampaignsCampaignIdQuestionsPostRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Question, true
}

// SetQuestion sets field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) SetQuestion(v ApiTenantIdStudioCampaignsCampaignIdQuestionsPostRequest) {
	o.Question = v
}

// GetStatus returns the Status field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) SetStatus(v string) {
	o.Status = v
}

// GetPiiScreen returns the PiiScreen field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetPiiScreen() string {
	if o == nil || o.PiiScreen.Get() == nil {
		var ret string
		return ret
	}

	return *o.PiiScreen.Get()
}

// GetPiiScreenOk returns a tuple with the PiiScreen field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetPiiScreenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PiiScreen.Get(), o.PiiScreen.IsSet()
}

// SetPiiScreen sets field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) SetPiiScreen(v string) {
	o.PiiScreen.Set(&v)
}

// GetTimesAsked returns the TimesAsked field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetTimesAsked() int32 {
	if o == nil || o.TimesAsked.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TimesAsked.Get()
}

// GetTimesAskedOk returns a tuple with the TimesAsked field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetTimesAskedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimesAsked.Get(), o.TimesAsked.IsSet()
}

// SetTimesAsked sets field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) SetTimesAsked(v int32) {
	o.TimesAsked.Set(&v)
}

// GetTimesCorrect returns the TimesCorrect field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetTimesCorrect() int32 {
	if o == nil || o.TimesCorrect.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TimesCorrect.Get()
}

// GetTimesCorrectOk returns a tuple with the TimesCorrect field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetTimesCorrectOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimesCorrect.Get(), o.TimesCorrect.IsSet()
}

// SetTimesCorrect sets field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) SetTimesCorrect(v int32) {
	o.TimesCorrect.Set(&v)
}

// GetRetiredReason returns the RetiredReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetRetiredReason() string {
	if o == nil || o.RetiredReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.RetiredReason.Get()
}

// GetRetiredReasonOk returns a tuple with the RetiredReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) GetRetiredReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetiredReason.Get(), o.RetiredReason.IsSet()
}

// SetRetiredReason sets field value
func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) SetRetiredReason(v string) {
	o.RetiredReason.Set(&v)
}

func (o ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["question"] = o.Question
	toSerialize["status"] = o.Status
	toSerialize["piiScreen"] = o.PiiScreen.Get()
	toSerialize["timesAsked"] = o.TimesAsked.Get()
	toSerialize["timesCorrect"] = o.TimesCorrect.Get()
	toSerialize["retiredReason"] = o.RetiredReason.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"question",
		"status",
		"piiScreen",
		"timesAsked",
		"timesCorrect",
		"retiredReason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response := _ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response{}

	err = json.Unmarshal(data, &varApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response)

	if err != nil {
		return err
	}

	*o = ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response(varApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "question")
		delete(additionalProperties, "status")
		delete(additionalProperties, "piiScreen")
		delete(additionalProperties, "timesAsked")
		delete(additionalProperties, "timesCorrect")
		delete(additionalProperties, "retiredReason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response struct {
	value *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response
	isSet bool
}

func (v NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) Get() *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response {
	return v.value
}

func (v *NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) Set(val *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response(val *ApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) *NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response {
	return &NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response{value: val, isSet: true}
}

func (v NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTenantIdStudioCampaignsCampaignIdQuestionsPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


