/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// PartialRedemptionPolicy What happens when a voucher is spent below its face value (docs/09 section 8.2).
type PartialRedemptionPolicy string

// List of PartialRedemptionPolicy
const (
	PARTIALREDEMPTIONPOLICY_BALANCE_CARRYING PartialRedemptionPolicy = "balance_carrying"
	PARTIALREDEMPTIONPOLICY_SINGLE_USE_FORFEIT PartialRedemptionPolicy = "single_use_forfeit"
	PARTIALREDEMPTIONPOLICY_MINIMUM_SPEND PartialRedemptionPolicy = "minimum_spend"
)

// All allowed values of PartialRedemptionPolicy enum
var AllowedPartialRedemptionPolicyEnumValues = []PartialRedemptionPolicy{
	"balance_carrying",
	"single_use_forfeit",
	"minimum_spend",
}

func (v *PartialRedemptionPolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PartialRedemptionPolicy(value)
	for _, existing := range AllowedPartialRedemptionPolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PartialRedemptionPolicy", value)
}

// NewPartialRedemptionPolicyFromValue returns a pointer to a valid PartialRedemptionPolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPartialRedemptionPolicyFromValue(v string) (*PartialRedemptionPolicy, error) {
	ev := PartialRedemptionPolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PartialRedemptionPolicy: valid values are %v", v, AllowedPartialRedemptionPolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PartialRedemptionPolicy) IsValid() bool {
	for _, existing := range AllowedPartialRedemptionPolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PartialRedemptionPolicy value
func (v PartialRedemptionPolicy) Ptr() *PartialRedemptionPolicy {
	return &v
}

type NullablePartialRedemptionPolicy struct {
	value *PartialRedemptionPolicy
	isSet bool
}

func (v NullablePartialRedemptionPolicy) Get() *PartialRedemptionPolicy {
	return v.value
}

func (v *NullablePartialRedemptionPolicy) Set(val *PartialRedemptionPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullablePartialRedemptionPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullablePartialRedemptionPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartialRedemptionPolicy(val *PartialRedemptionPolicy) *NullablePartialRedemptionPolicy {
	return &NullablePartialRedemptionPolicy{value: val, isSet: true}
}

func (v NullablePartialRedemptionPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartialRedemptionPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

