/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// WalletHistoryEntryKind What kind of ledger event this history entry reflects (YT-0504).
type WalletHistoryEntryKind string

// List of WalletHistoryEntryKind
const (
	WALLETHISTORYENTRYKIND_EARN WalletHistoryEntryKind = "earn"
	WALLETHISTORYENTRYKIND_BURN WalletHistoryEntryKind = "burn"
	WALLETHISTORYENTRYKIND_EXPIRY WalletHistoryEntryKind = "expiry"
	WALLETHISTORYENTRYKIND_REVERSAL WalletHistoryEntryKind = "reversal"
	WALLETHISTORYENTRYKIND_ADJUSTMENT WalletHistoryEntryKind = "adjustment"
)

// All allowed values of WalletHistoryEntryKind enum
var AllowedWalletHistoryEntryKindEnumValues = []WalletHistoryEntryKind{
	"earn",
	"burn",
	"expiry",
	"reversal",
	"adjustment",
}

func (v *WalletHistoryEntryKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WalletHistoryEntryKind(value)
	for _, existing := range AllowedWalletHistoryEntryKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WalletHistoryEntryKind", value)
}

// NewWalletHistoryEntryKindFromValue returns a pointer to a valid WalletHistoryEntryKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWalletHistoryEntryKindFromValue(v string) (*WalletHistoryEntryKind, error) {
	ev := WalletHistoryEntryKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WalletHistoryEntryKind: valid values are %v", v, AllowedWalletHistoryEntryKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WalletHistoryEntryKind) IsValid() bool {
	for _, existing := range AllowedWalletHistoryEntryKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WalletHistoryEntryKind value
func (v WalletHistoryEntryKind) Ptr() *WalletHistoryEntryKind {
	return &v
}

type NullableWalletHistoryEntryKind struct {
	value *WalletHistoryEntryKind
	isSet bool
}

func (v NullableWalletHistoryEntryKind) Get() *WalletHistoryEntryKind {
	return v.value
}

func (v *NullableWalletHistoryEntryKind) Set(val *WalletHistoryEntryKind) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletHistoryEntryKind) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletHistoryEntryKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletHistoryEntryKind(val *WalletHistoryEntryKind) *NullableWalletHistoryEntryKind {
	return &NullableWalletHistoryEntryKind{value: val, isSet: true}
}

func (v NullableWalletHistoryEntryKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletHistoryEntryKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

