/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ApiStaffUsersUserIdGoodwillPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffUsersUserIdGoodwillPost201Response{}

// ApiStaffUsersUserIdGoodwillPost201Response struct for ApiStaffUsersUserIdGoodwillPost201Response
type ApiStaffUsersUserIdGoodwillPost201Response struct {
	GrantId string `json:"grantId"`
	Points int64 `json:"points"`
	UnlockAt time.Time `json:"unlockAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffUsersUserIdGoodwillPost201Response ApiStaffUsersUserIdGoodwillPost201Response

// NewApiStaffUsersUserIdGoodwillPost201Response instantiates a new ApiStaffUsersUserIdGoodwillPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffUsersUserIdGoodwillPost201Response(grantId string, points int64, unlockAt time.Time) *ApiStaffUsersUserIdGoodwillPost201Response {
	this := ApiStaffUsersUserIdGoodwillPost201Response{}
	this.GrantId = grantId
	this.Points = points
	this.UnlockAt = unlockAt
	return &this
}

// NewApiStaffUsersUserIdGoodwillPost201ResponseWithDefaults instantiates a new ApiStaffUsersUserIdGoodwillPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffUsersUserIdGoodwillPost201ResponseWithDefaults() *ApiStaffUsersUserIdGoodwillPost201Response {
	this := ApiStaffUsersUserIdGoodwillPost201Response{}
	return &this
}

// GetGrantId returns the GrantId field value
func (o *ApiStaffUsersUserIdGoodwillPost201Response) GetGrantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantId
}

// GetGrantIdOk returns a tuple with the GrantId field value
// and a boolean to check if the value has been set.
func (o *ApiStaffUsersUserIdGoodwillPost201Response) GetGrantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantId, true
}

// SetGrantId sets field value
func (o *ApiStaffUsersUserIdGoodwillPost201Response) SetGrantId(v string) {
	o.GrantId = v
}

// GetPoints returns the Points field value
func (o *ApiStaffUsersUserIdGoodwillPost201Response) GetPoints() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *ApiStaffUsersUserIdGoodwillPost201Response) GetPointsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Points, true
}

// SetPoints sets field value
func (o *ApiStaffUsersUserIdGoodwillPost201Response) SetPoints(v int64) {
	o.Points = v
}

// GetUnlockAt returns the UnlockAt field value
func (o *ApiStaffUsersUserIdGoodwillPost201Response) GetUnlockAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UnlockAt
}

// GetUnlockAtOk returns a tuple with the UnlockAt field value
// and a boolean to check if the value has been set.
func (o *ApiStaffUsersUserIdGoodwillPost201Response) GetUnlockAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnlockAt, true
}

// SetUnlockAt sets field value
func (o *ApiStaffUsersUserIdGoodwillPost201Response) SetUnlockAt(v time.Time) {
	o.UnlockAt = v
}

func (o ApiStaffUsersUserIdGoodwillPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffUsersUserIdGoodwillPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grantId"] = o.GrantId
	toSerialize["points"] = o.Points
	toSerialize["unlockAt"] = o.UnlockAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffUsersUserIdGoodwillPost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grantId",
		"points",
		"unlockAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffUsersUserIdGoodwillPost201Response := _ApiStaffUsersUserIdGoodwillPost201Response{}

	err = json.Unmarshal(data, &varApiStaffUsersUserIdGoodwillPost201Response)

	if err != nil {
		return err
	}

	*o = ApiStaffUsersUserIdGoodwillPost201Response(varApiStaffUsersUserIdGoodwillPost201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grantId")
		delete(additionalProperties, "points")
		delete(additionalProperties, "unlockAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffUsersUserIdGoodwillPost201Response struct {
	value *ApiStaffUsersUserIdGoodwillPost201Response
	isSet bool
}

func (v NullableApiStaffUsersUserIdGoodwillPost201Response) Get() *ApiStaffUsersUserIdGoodwillPost201Response {
	return v.value
}

func (v *NullableApiStaffUsersUserIdGoodwillPost201Response) Set(val *ApiStaffUsersUserIdGoodwillPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffUsersUserIdGoodwillPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffUsersUserIdGoodwillPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffUsersUserIdGoodwillPost201Response(val *ApiStaffUsersUserIdGoodwillPost201Response) *NullableApiStaffUsersUserIdGoodwillPost201Response {
	return &NullableApiStaffUsersUserIdGoodwillPost201Response{value: val, isSet: true}
}

func (v NullableApiStaffUsersUserIdGoodwillPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffUsersUserIdGoodwillPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


