/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the StudioRedemptionEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StudioRedemptionEntry{}

// StudioRedemptionEntry One row of GET /api/:tenantId/studio/redemptions (8.2.g) — recent captures per location and device.
type StudioRedemptionEntry struct {
	CaptureId string `json:"captureId"`
	DeviceId string `json:"deviceId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	DeviceLabel string `json:"deviceLabel"`
	LocationId string `json:"locationId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	LocationName string `json:"locationName"`
	VoucherId string `json:"voucherId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	// A whole number of some currency's minor unit, WITHOUT saying which (YT-0513). The currency is a sibling field on the same record — listingSchema.currency, voucherSchema.currency — one per record, so an amount can never be stored without its currency and two amounts on one record can never disagree. This replaced IdrMinorUnits on the wire: that brand named a currency it did not always hold, and AU fixtures stored AUD cents in a field typed IdrMinorUnits. Not a nested Money object, because the contracts-to-migrations drift gate maps each field to a snake_case column and a nested object needs columns corresponding to nothing; callers compose money(record.fooMinor, record.currency) at the point of use.
	AmountMinor int64 `json:"amountMinor"`
	Currency Currency `json:"currency"`
	OrderRef string `json:"orderRef"`
	CapturedAt time.Time `json:"capturedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _StudioRedemptionEntry StudioRedemptionEntry

// NewStudioRedemptionEntry instantiates a new StudioRedemptionEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStudioRedemptionEntry(captureId string, deviceId string, deviceLabel string, locationId string, locationName string, voucherId string, amountMinor int64, currency Currency, orderRef string, capturedAt time.Time) *StudioRedemptionEntry {
	this := StudioRedemptionEntry{}
	this.CaptureId = captureId
	this.DeviceId = deviceId
	this.DeviceLabel = deviceLabel
	this.LocationId = locationId
	this.LocationName = locationName
	this.VoucherId = voucherId
	this.AmountMinor = amountMinor
	this.Currency = currency
	this.OrderRef = orderRef
	this.CapturedAt = capturedAt
	return &this
}

// NewStudioRedemptionEntryWithDefaults instantiates a new StudioRedemptionEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStudioRedemptionEntryWithDefaults() *StudioRedemptionEntry {
	this := StudioRedemptionEntry{}
	return &this
}

// GetCaptureId returns the CaptureId field value
func (o *StudioRedemptionEntry) GetCaptureId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CaptureId
}

// GetCaptureIdOk returns a tuple with the CaptureId field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetCaptureIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaptureId, true
}

// SetCaptureId sets field value
func (o *StudioRedemptionEntry) SetCaptureId(v string) {
	o.CaptureId = v
}

// GetDeviceId returns the DeviceId field value
func (o *StudioRedemptionEntry) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *StudioRedemptionEntry) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetDeviceLabel returns the DeviceLabel field value
func (o *StudioRedemptionEntry) GetDeviceLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceLabel
}

// GetDeviceLabelOk returns a tuple with the DeviceLabel field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetDeviceLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceLabel, true
}

// SetDeviceLabel sets field value
func (o *StudioRedemptionEntry) SetDeviceLabel(v string) {
	o.DeviceLabel = v
}

// GetLocationId returns the LocationId field value
func (o *StudioRedemptionEntry) GetLocationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *StudioRedemptionEntry) SetLocationId(v string) {
	o.LocationId = v
}

// GetLocationName returns the LocationName field value
func (o *StudioRedemptionEntry) GetLocationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationName
}

// GetLocationNameOk returns a tuple with the LocationName field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetLocationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationName, true
}

// SetLocationName sets field value
func (o *StudioRedemptionEntry) SetLocationName(v string) {
	o.LocationName = v
}

// GetVoucherId returns the VoucherId field value
func (o *StudioRedemptionEntry) GetVoucherId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VoucherId
}

// GetVoucherIdOk returns a tuple with the VoucherId field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetVoucherIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VoucherId, true
}

// SetVoucherId sets field value
func (o *StudioRedemptionEntry) SetVoucherId(v string) {
	o.VoucherId = v
}

// GetAmountMinor returns the AmountMinor field value
func (o *StudioRedemptionEntry) GetAmountMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetAmountMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountMinor, true
}

// SetAmountMinor sets field value
func (o *StudioRedemptionEntry) SetAmountMinor(v int64) {
	o.AmountMinor = v
}

// GetCurrency returns the Currency field value
func (o *StudioRedemptionEntry) GetCurrency() Currency {
	if o == nil {
		var ret Currency
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetCurrencyOk() (*Currency, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *StudioRedemptionEntry) SetCurrency(v Currency) {
	o.Currency = v
}

// GetOrderRef returns the OrderRef field value
func (o *StudioRedemptionEntry) GetOrderRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderRef
}

// GetOrderRefOk returns a tuple with the OrderRef field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetOrderRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderRef, true
}

// SetOrderRef sets field value
func (o *StudioRedemptionEntry) SetOrderRef(v string) {
	o.OrderRef = v
}

// GetCapturedAt returns the CapturedAt field value
func (o *StudioRedemptionEntry) GetCapturedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CapturedAt
}

// GetCapturedAtOk returns a tuple with the CapturedAt field value
// and a boolean to check if the value has been set.
func (o *StudioRedemptionEntry) GetCapturedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapturedAt, true
}

// SetCapturedAt sets field value
func (o *StudioRedemptionEntry) SetCapturedAt(v time.Time) {
	o.CapturedAt = v
}

func (o StudioRedemptionEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StudioRedemptionEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["captureId"] = o.CaptureId
	toSerialize["deviceId"] = o.DeviceId
	toSerialize["deviceLabel"] = o.DeviceLabel
	toSerialize["locationId"] = o.LocationId
	toSerialize["locationName"] = o.LocationName
	toSerialize["voucherId"] = o.VoucherId
	toSerialize["amountMinor"] = o.AmountMinor
	toSerialize["currency"] = o.Currency
	toSerialize["orderRef"] = o.OrderRef
	toSerialize["capturedAt"] = o.CapturedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StudioRedemptionEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"captureId",
		"deviceId",
		"deviceLabel",
		"locationId",
		"locationName",
		"voucherId",
		"amountMinor",
		"currency",
		"orderRef",
		"capturedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStudioRedemptionEntry := _StudioRedemptionEntry{}

	err = json.Unmarshal(data, &varStudioRedemptionEntry)

	if err != nil {
		return err
	}

	*o = StudioRedemptionEntry(varStudioRedemptionEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "captureId")
		delete(additionalProperties, "deviceId")
		delete(additionalProperties, "deviceLabel")
		delete(additionalProperties, "locationId")
		delete(additionalProperties, "locationName")
		delete(additionalProperties, "voucherId")
		delete(additionalProperties, "amountMinor")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "orderRef")
		delete(additionalProperties, "capturedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStudioRedemptionEntry struct {
	value *StudioRedemptionEntry
	isSet bool
}

func (v NullableStudioRedemptionEntry) Get() *StudioRedemptionEntry {
	return v.value
}

func (v *NullableStudioRedemptionEntry) Set(val *StudioRedemptionEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableStudioRedemptionEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableStudioRedemptionEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStudioRedemptionEntry(val *StudioRedemptionEntry) *NullableStudioRedemptionEntry {
	return &NullableStudioRedemptionEntry{value: val, isSet: true}
}

func (v NullableStudioRedemptionEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStudioRedemptionEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


