/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552). Do not edit by hand.  `paths` covers every route the business module serves (apps/api/src/modules/business), hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the campaign and watch modules are separate, concurrently in-flight streams (YT-0101/YT-0120/YT-0548) this ticket did not give a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a business-module controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Listing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Listing{}

// Listing A store listing: what it costs in points, what it settles at, and its stock.  Rules NOT enforced by this schema (they cannot be expressed in JSON Schema, and are enforced only by the Zod schema in @yourtal/contracts):   - stockRemaining cannot exceed stockTotal.   - settlementValueIdr (what the merchant is paid) cannot exceed faceValueIdr (docs/09 section 3).   - A sold_out listing must have zero stockRemaining.   - minimumSpendIdr is set if and only if the policy is minimum_spend.   - location ids must be unique within a listing.
type Listing struct {
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	MerchantId string `json:"merchantId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	MerchantName string `json:"merchantName"`
	Title string `json:"title"`
	Description string `json:"description"`
	Category ListingCategory `json:"category"`
	Locations []MerchantLocation `json:"locations"`
	// Indonesian Rupiah as an integer number of SEN — one hundredth of a Rupiah. Rp 45.000 is 4500000. Settled by YT-0506 on 2026-09-20: ISO 4217 gives IDR a sen minor unit, Indonesian banking uses it (amounts appear as Rp 1.000,26), and Stripe treats IDR as two-decimal. This settles what we STORE, not what a processor accepts: Xendit publishes no amount-unit spec and Adyen flags IDR as diverging from ISO, so conversion belongs in each PSP adapter. Prefer Money, which carries its own currency.
	FaceValueIdr int64 `json:"faceValueIdr"`
	// Indonesian Rupiah as an integer number of SEN — one hundredth of a Rupiah. Rp 45.000 is 4500000. Settled by YT-0506 on 2026-09-20: ISO 4217 gives IDR a sen minor unit, Indonesian banking uses it (amounts appear as Rp 1.000,26), and Stripe treats IDR as two-decimal. This settles what we STORE, not what a processor accepts: Xendit publishes no amount-unit spec and Adyen flags IDR as diverging from ISO, so conversion belongs in each PSP adapter. Prefer Money, which carries its own currency.
	SettlementValueIdr int64 `json:"settlementValueIdr"`
	// Platform points. Always a whole number; there is no fractional point.
	PriceInPoints int64 `json:"priceInPoints"`
	StockRemaining int64 `json:"stockRemaining"`
	StockTotal int64 `json:"stockTotal"`
	Transferable bool `json:"transferable"`
	PartialRedemptionPolicy PartialRedemptionPolicy `json:"partialRedemptionPolicy"`
	MinimumSpendIdr ListingMinimumSpendIdr `json:"minimumSpendIdr"`
	ExpiresAt time.Time `json:"expiresAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d:[0-5]\\\\d(?:\\\\.\\\\d+)?(?:Z))$"`
	Status ListingStatus `json:"status"`
	PerUserLimit *int64 `json:"perUserLimit,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Listing Listing

// NewListing instantiates a new Listing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListing(id string, merchantId string, merchantName string, title string, description string, category ListingCategory, locations []MerchantLocation, faceValueIdr int64, settlementValueIdr int64, priceInPoints int64, stockRemaining int64, stockTotal int64, transferable bool, partialRedemptionPolicy PartialRedemptionPolicy, minimumSpendIdr ListingMinimumSpendIdr, expiresAt time.Time, status ListingStatus) *Listing {
	this := Listing{}
	this.Id = id
	this.MerchantId = merchantId
	this.MerchantName = merchantName
	this.Title = title
	this.Description = description
	this.Category = category
	this.Locations = locations
	this.FaceValueIdr = faceValueIdr
	this.SettlementValueIdr = settlementValueIdr
	this.PriceInPoints = priceInPoints
	this.StockRemaining = stockRemaining
	this.StockTotal = stockTotal
	this.Transferable = transferable
	this.PartialRedemptionPolicy = partialRedemptionPolicy
	this.MinimumSpendIdr = minimumSpendIdr
	this.ExpiresAt = expiresAt
	this.Status = status
	return &this
}

// NewListingWithDefaults instantiates a new Listing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListingWithDefaults() *Listing {
	this := Listing{}
	return &this
}

// GetId returns the Id field value
func (o *Listing) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Listing) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Listing) SetId(v string) {
	o.Id = v
}

// GetMerchantId returns the MerchantId field value
func (o *Listing) GetMerchantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value
// and a boolean to check if the value has been set.
func (o *Listing) GetMerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantId, true
}

// SetMerchantId sets field value
func (o *Listing) SetMerchantId(v string) {
	o.MerchantId = v
}

// GetMerchantName returns the MerchantName field value
func (o *Listing) GetMerchantName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantName
}

// GetMerchantNameOk returns a tuple with the MerchantName field value
// and a boolean to check if the value has been set.
func (o *Listing) GetMerchantNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantName, true
}

// SetMerchantName sets field value
func (o *Listing) SetMerchantName(v string) {
	o.MerchantName = v
}

// GetTitle returns the Title field value
func (o *Listing) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Listing) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Listing) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value
func (o *Listing) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Listing) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Listing) SetDescription(v string) {
	o.Description = v
}

// GetCategory returns the Category field value
func (o *Listing) GetCategory() ListingCategory {
	if o == nil {
		var ret ListingCategory
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *Listing) GetCategoryOk() (*ListingCategory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *Listing) SetCategory(v ListingCategory) {
	o.Category = v
}

// GetLocations returns the Locations field value
func (o *Listing) GetLocations() []MerchantLocation {
	if o == nil {
		var ret []MerchantLocation
		return ret
	}

	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value
// and a boolean to check if the value has been set.
func (o *Listing) GetLocationsOk() ([]MerchantLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locations, true
}

// SetLocations sets field value
func (o *Listing) SetLocations(v []MerchantLocation) {
	o.Locations = v
}

// GetFaceValueIdr returns the FaceValueIdr field value
func (o *Listing) GetFaceValueIdr() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FaceValueIdr
}

// GetFaceValueIdrOk returns a tuple with the FaceValueIdr field value
// and a boolean to check if the value has been set.
func (o *Listing) GetFaceValueIdrOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FaceValueIdr, true
}

// SetFaceValueIdr sets field value
func (o *Listing) SetFaceValueIdr(v int64) {
	o.FaceValueIdr = v
}

// GetSettlementValueIdr returns the SettlementValueIdr field value
func (o *Listing) GetSettlementValueIdr() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SettlementValueIdr
}

// GetSettlementValueIdrOk returns a tuple with the SettlementValueIdr field value
// and a boolean to check if the value has been set.
func (o *Listing) GetSettlementValueIdrOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementValueIdr, true
}

// SetSettlementValueIdr sets field value
func (o *Listing) SetSettlementValueIdr(v int64) {
	o.SettlementValueIdr = v
}

// GetPriceInPoints returns the PriceInPoints field value
func (o *Listing) GetPriceInPoints() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PriceInPoints
}

// GetPriceInPointsOk returns a tuple with the PriceInPoints field value
// and a boolean to check if the value has been set.
func (o *Listing) GetPriceInPointsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceInPoints, true
}

// SetPriceInPoints sets field value
func (o *Listing) SetPriceInPoints(v int64) {
	o.PriceInPoints = v
}

// GetStockRemaining returns the StockRemaining field value
func (o *Listing) GetStockRemaining() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StockRemaining
}

// GetStockRemainingOk returns a tuple with the StockRemaining field value
// and a boolean to check if the value has been set.
func (o *Listing) GetStockRemainingOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StockRemaining, true
}

// SetStockRemaining sets field value
func (o *Listing) SetStockRemaining(v int64) {
	o.StockRemaining = v
}

// GetStockTotal returns the StockTotal field value
func (o *Listing) GetStockTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StockTotal
}

// GetStockTotalOk returns a tuple with the StockTotal field value
// and a boolean to check if the value has been set.
func (o *Listing) GetStockTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StockTotal, true
}

// SetStockTotal sets field value
func (o *Listing) SetStockTotal(v int64) {
	o.StockTotal = v
}

// GetTransferable returns the Transferable field value
func (o *Listing) GetTransferable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Transferable
}

// GetTransferableOk returns a tuple with the Transferable field value
// and a boolean to check if the value has been set.
func (o *Listing) GetTransferableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transferable, true
}

// SetTransferable sets field value
func (o *Listing) SetTransferable(v bool) {
	o.Transferable = v
}

// GetPartialRedemptionPolicy returns the PartialRedemptionPolicy field value
func (o *Listing) GetPartialRedemptionPolicy() PartialRedemptionPolicy {
	if o == nil {
		var ret PartialRedemptionPolicy
		return ret
	}

	return o.PartialRedemptionPolicy
}

// GetPartialRedemptionPolicyOk returns a tuple with the PartialRedemptionPolicy field value
// and a boolean to check if the value has been set.
func (o *Listing) GetPartialRedemptionPolicyOk() (*PartialRedemptionPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartialRedemptionPolicy, true
}

// SetPartialRedemptionPolicy sets field value
func (o *Listing) SetPartialRedemptionPolicy(v PartialRedemptionPolicy) {
	o.PartialRedemptionPolicy = v
}

// GetMinimumSpendIdr returns the MinimumSpendIdr field value
func (o *Listing) GetMinimumSpendIdr() ListingMinimumSpendIdr {
	if o == nil {
		var ret ListingMinimumSpendIdr
		return ret
	}

	return o.MinimumSpendIdr
}

// GetMinimumSpendIdrOk returns a tuple with the MinimumSpendIdr field value
// and a boolean to check if the value has been set.
func (o *Listing) GetMinimumSpendIdrOk() (*ListingMinimumSpendIdr, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumSpendIdr, true
}

// SetMinimumSpendIdr sets field value
func (o *Listing) SetMinimumSpendIdr(v ListingMinimumSpendIdr) {
	o.MinimumSpendIdr = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *Listing) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *Listing) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *Listing) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetStatus returns the Status field value
func (o *Listing) GetStatus() ListingStatus {
	if o == nil {
		var ret ListingStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Listing) GetStatusOk() (*ListingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Listing) SetStatus(v ListingStatus) {
	o.Status = v
}

// GetPerUserLimit returns the PerUserLimit field value if set, zero value otherwise.
func (o *Listing) GetPerUserLimit() int64 {
	if o == nil || IsNil(o.PerUserLimit) {
		var ret int64
		return ret
	}
	return *o.PerUserLimit
}

// GetPerUserLimitOk returns a tuple with the PerUserLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetPerUserLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.PerUserLimit) {
		return nil, false
	}
	return o.PerUserLimit, true
}

// HasPerUserLimit returns a boolean if a field has been set.
func (o *Listing) HasPerUserLimit() bool {
	if o != nil && !IsNil(o.PerUserLimit) {
		return true
	}

	return false
}

// SetPerUserLimit gets a reference to the given int64 and assigns it to the PerUserLimit field.
func (o *Listing) SetPerUserLimit(v int64) {
	o.PerUserLimit = &v
}

func (o Listing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Listing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["merchantId"] = o.MerchantId
	toSerialize["merchantName"] = o.MerchantName
	toSerialize["title"] = o.Title
	toSerialize["description"] = o.Description
	toSerialize["category"] = o.Category
	toSerialize["locations"] = o.Locations
	toSerialize["faceValueIdr"] = o.FaceValueIdr
	toSerialize["settlementValueIdr"] = o.SettlementValueIdr
	toSerialize["priceInPoints"] = o.PriceInPoints
	toSerialize["stockRemaining"] = o.StockRemaining
	toSerialize["stockTotal"] = o.StockTotal
	toSerialize["transferable"] = o.Transferable
	toSerialize["partialRedemptionPolicy"] = o.PartialRedemptionPolicy
	toSerialize["minimumSpendIdr"] = o.MinimumSpendIdr
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["status"] = o.Status
	if !IsNil(o.PerUserLimit) {
		toSerialize["perUserLimit"] = o.PerUserLimit
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Listing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"merchantId",
		"merchantName",
		"title",
		"description",
		"category",
		"locations",
		"faceValueIdr",
		"settlementValueIdr",
		"priceInPoints",
		"stockRemaining",
		"stockTotal",
		"transferable",
		"partialRedemptionPolicy",
		"minimumSpendIdr",
		"expiresAt",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListing := _Listing{}

	err = json.Unmarshal(data, &varListing)

	if err != nil {
		return err
	}

	*o = Listing(varListing)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "merchantId")
		delete(additionalProperties, "merchantName")
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "category")
		delete(additionalProperties, "locations")
		delete(additionalProperties, "faceValueIdr")
		delete(additionalProperties, "settlementValueIdr")
		delete(additionalProperties, "priceInPoints")
		delete(additionalProperties, "stockRemaining")
		delete(additionalProperties, "stockTotal")
		delete(additionalProperties, "transferable")
		delete(additionalProperties, "partialRedemptionPolicy")
		delete(additionalProperties, "minimumSpendIdr")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "status")
		delete(additionalProperties, "perUserLimit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListing struct {
	value *Listing
	isSet bool
}

func (v NullableListing) Get() *Listing {
	return v.value
}

func (v *NullableListing) Set(val *Listing) {
	v.value = val
	v.isSet = true
}

func (v NullableListing) IsSet() bool {
	return v.isSet
}

func (v *NullableListing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListing(val *Listing) *NullableListing {
	return &NullableListing{value: val, isSet: true}
}

func (v NullableListing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


