/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiDevClockRunJobPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDevClockRunJobPostRequest{}

// ApiDevClockRunJobPostRequest struct for ApiDevClockRunJobPostRequest
type ApiDevClockRunJobPostRequest struct {
	Job string `json:"job"`
	AdditionalProperties map[string]interface{}
}

type _ApiDevClockRunJobPostRequest ApiDevClockRunJobPostRequest

// NewApiDevClockRunJobPostRequest instantiates a new ApiDevClockRunJobPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDevClockRunJobPostRequest(job string) *ApiDevClockRunJobPostRequest {
	this := ApiDevClockRunJobPostRequest{}
	this.Job = job
	return &this
}

// NewApiDevClockRunJobPostRequestWithDefaults instantiates a new ApiDevClockRunJobPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDevClockRunJobPostRequestWithDefaults() *ApiDevClockRunJobPostRequest {
	this := ApiDevClockRunJobPostRequest{}
	return &this
}

// GetJob returns the Job field value
func (o *ApiDevClockRunJobPostRequest) GetJob() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *ApiDevClockRunJobPostRequest) GetJobOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *ApiDevClockRunJobPostRequest) SetJob(v string) {
	o.Job = v
}

func (o ApiDevClockRunJobPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDevClockRunJobPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job"] = o.Job

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiDevClockRunJobPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiDevClockRunJobPostRequest := _ApiDevClockRunJobPostRequest{}

	err = json.Unmarshal(data, &varApiDevClockRunJobPostRequest)

	if err != nil {
		return err
	}

	*o = ApiDevClockRunJobPostRequest(varApiDevClockRunJobPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "job")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiDevClockRunJobPostRequest struct {
	value *ApiDevClockRunJobPostRequest
	isSet bool
}

func (v NullableApiDevClockRunJobPostRequest) Get() *ApiDevClockRunJobPostRequest {
	return v.value
}

func (v *NullableApiDevClockRunJobPostRequest) Set(val *ApiDevClockRunJobPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDevClockRunJobPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDevClockRunJobPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDevClockRunJobPostRequest(val *ApiDevClockRunJobPostRequest) *NullableApiDevClockRunJobPostRequest {
	return &NullableApiDevClockRunJobPostRequest{value: val, isSet: true}
}

func (v NullableApiDevClockRunJobPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDevClockRunJobPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


