/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WalletVoucherDetailLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletVoucherDetailLocation{}

// WalletVoucherDetailLocation struct for WalletVoucherDetailLocation
type WalletVoucherDetailLocation struct {
	Name string `json:"name"`
	Address string `json:"address"`
	District string `json:"district"`
}

type _WalletVoucherDetailLocation WalletVoucherDetailLocation

// NewWalletVoucherDetailLocation instantiates a new WalletVoucherDetailLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletVoucherDetailLocation(name string, address string, district string) *WalletVoucherDetailLocation {
	this := WalletVoucherDetailLocation{}
	this.Name = name
	this.Address = address
	this.District = district
	return &this
}

// NewWalletVoucherDetailLocationWithDefaults instantiates a new WalletVoucherDetailLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletVoucherDetailLocationWithDefaults() *WalletVoucherDetailLocation {
	this := WalletVoucherDetailLocation{}
	return &this
}

// GetName returns the Name field value
func (o *WalletVoucherDetailLocation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WalletVoucherDetailLocation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WalletVoucherDetailLocation) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *WalletVoucherDetailLocation) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *WalletVoucherDetailLocation) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *WalletVoucherDetailLocation) SetAddress(v string) {
	o.Address = v
}

// GetDistrict returns the District field value
func (o *WalletVoucherDetailLocation) GetDistrict() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.District
}

// GetDistrictOk returns a tuple with the District field value
// and a boolean to check if the value has been set.
func (o *WalletVoucherDetailLocation) GetDistrictOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.District, true
}

// SetDistrict sets field value
func (o *WalletVoucherDetailLocation) SetDistrict(v string) {
	o.District = v
}

func (o WalletVoucherDetailLocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletVoucherDetailLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	toSerialize["district"] = o.District
	return toSerialize, nil
}

func (o *WalletVoucherDetailLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"address",
		"district",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletVoucherDetailLocation := _WalletVoucherDetailLocation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWalletVoucherDetailLocation)

	if err != nil {
		return err
	}

	*o = WalletVoucherDetailLocation(varWalletVoucherDetailLocation)

	return err
}

type NullableWalletVoucherDetailLocation struct {
	value *WalletVoucherDetailLocation
	isSet bool
}

func (v NullableWalletVoucherDetailLocation) Get() *WalletVoucherDetailLocation {
	return v.value
}

func (v *NullableWalletVoucherDetailLocation) Set(val *WalletVoucherDetailLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletVoucherDetailLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletVoucherDetailLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletVoucherDetailLocation(val *WalletVoucherDetailLocation) *NullableWalletVoucherDetailLocation {
	return &NullableWalletVoucherDetailLocation{value: val, isSet: true}
}

func (v NullableWalletVoucherDetailLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletVoucherDetailLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


