/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiStaffBusinessesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffBusinessesGet200Response{}

// ApiStaffBusinessesGet200Response struct for ApiStaffBusinessesGet200Response
type ApiStaffBusinessesGet200Response struct {
	Businesses []ApiStaffBusinessesGet200ResponseBusinessesInner `json:"businesses"`
	Total NullableInt32 `json:"total"`
}

type _ApiStaffBusinessesGet200Response ApiStaffBusinessesGet200Response

// NewApiStaffBusinessesGet200Response instantiates a new ApiStaffBusinessesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffBusinessesGet200Response(businesses []ApiStaffBusinessesGet200ResponseBusinessesInner, total NullableInt32) *ApiStaffBusinessesGet200Response {
	this := ApiStaffBusinessesGet200Response{}
	this.Businesses = businesses
	this.Total = total
	return &this
}

// NewApiStaffBusinessesGet200ResponseWithDefaults instantiates a new ApiStaffBusinessesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffBusinessesGet200ResponseWithDefaults() *ApiStaffBusinessesGet200Response {
	this := ApiStaffBusinessesGet200Response{}
	return &this
}

// GetBusinesses returns the Businesses field value
func (o *ApiStaffBusinessesGet200Response) GetBusinesses() []ApiStaffBusinessesGet200ResponseBusinessesInner {
	if o == nil {
		var ret []ApiStaffBusinessesGet200ResponseBusinessesInner
		return ret
	}

	return o.Businesses
}

// GetBusinessesOk returns a tuple with the Businesses field value
// and a boolean to check if the value has been set.
func (o *ApiStaffBusinessesGet200Response) GetBusinessesOk() ([]ApiStaffBusinessesGet200ResponseBusinessesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Businesses, true
}

// SetBusinesses sets field value
func (o *ApiStaffBusinessesGet200Response) SetBusinesses(v []ApiStaffBusinessesGet200ResponseBusinessesInner) {
	o.Businesses = v
}

// GetTotal returns the Total field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ApiStaffBusinessesGet200Response) GetTotal() int32 {
	if o == nil || o.Total.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffBusinessesGet200Response) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// SetTotal sets field value
func (o *ApiStaffBusinessesGet200Response) SetTotal(v int32) {
	o.Total.Set(&v)
}

func (o ApiStaffBusinessesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffBusinessesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["businesses"] = o.Businesses
	toSerialize["total"] = o.Total.Get()
	return toSerialize, nil
}

func (o *ApiStaffBusinessesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"businesses",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffBusinessesGet200Response := _ApiStaffBusinessesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiStaffBusinessesGet200Response)

	if err != nil {
		return err
	}

	*o = ApiStaffBusinessesGet200Response(varApiStaffBusinessesGet200Response)

	return err
}

type NullableApiStaffBusinessesGet200Response struct {
	value *ApiStaffBusinessesGet200Response
	isSet bool
}

func (v NullableApiStaffBusinessesGet200Response) Get() *ApiStaffBusinessesGet200Response {
	return v.value
}

func (v *NullableApiStaffBusinessesGet200Response) Set(val *ApiStaffBusinessesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffBusinessesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffBusinessesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffBusinessesGet200Response(val *ApiStaffBusinessesGet200Response) *NullableApiStaffBusinessesGet200Response {
	return &NullableApiStaffBusinessesGet200Response{value: val, isSet: true}
}

func (v NullableApiStaffBusinessesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffBusinessesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


