/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ApiHealthGet200ResponseChecksPdp - struct for ApiHealthGet200ResponseChecksPdp
type ApiHealthGet200ResponseChecksPdp struct {
	ApiHealthGet200ResponseChecksPdpOneOf *ApiHealthGet200ResponseChecksPdpOneOf
	ApiHealthGet200ResponseChecksPdpOneOf1 *ApiHealthGet200ResponseChecksPdpOneOf1
}

// ApiHealthGet200ResponseChecksPdpOneOfAsApiHealthGet200ResponseChecksPdp is a convenience function that returns ApiHealthGet200ResponseChecksPdpOneOf wrapped in ApiHealthGet200ResponseChecksPdp
func ApiHealthGet200ResponseChecksPdpOneOfAsApiHealthGet200ResponseChecksPdp(v *ApiHealthGet200ResponseChecksPdpOneOf) ApiHealthGet200ResponseChecksPdp {
	return ApiHealthGet200ResponseChecksPdp{
		ApiHealthGet200ResponseChecksPdpOneOf: v,
	}
}

// ApiHealthGet200ResponseChecksPdpOneOf1AsApiHealthGet200ResponseChecksPdp is a convenience function that returns ApiHealthGet200ResponseChecksPdpOneOf1 wrapped in ApiHealthGet200ResponseChecksPdp
func ApiHealthGet200ResponseChecksPdpOneOf1AsApiHealthGet200ResponseChecksPdp(v *ApiHealthGet200ResponseChecksPdpOneOf1) ApiHealthGet200ResponseChecksPdp {
	return ApiHealthGet200ResponseChecksPdp{
		ApiHealthGet200ResponseChecksPdpOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApiHealthGet200ResponseChecksPdp) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ApiHealthGet200ResponseChecksPdpOneOf
	err = newStrictDecoder(data).Decode(&dst.ApiHealthGet200ResponseChecksPdpOneOf)
	if err == nil {
		jsonApiHealthGet200ResponseChecksPdpOneOf, _ := json.Marshal(dst.ApiHealthGet200ResponseChecksPdpOneOf)
		if string(jsonApiHealthGet200ResponseChecksPdpOneOf) == "{}" { // empty struct
			dst.ApiHealthGet200ResponseChecksPdpOneOf = nil
		} else {
			if err = validator.Validate(dst.ApiHealthGet200ResponseChecksPdpOneOf); err != nil {
				dst.ApiHealthGet200ResponseChecksPdpOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiHealthGet200ResponseChecksPdpOneOf = nil
	}

	// try to unmarshal data into ApiHealthGet200ResponseChecksPdpOneOf1
	err = newStrictDecoder(data).Decode(&dst.ApiHealthGet200ResponseChecksPdpOneOf1)
	if err == nil {
		jsonApiHealthGet200ResponseChecksPdpOneOf1, _ := json.Marshal(dst.ApiHealthGet200ResponseChecksPdpOneOf1)
		if string(jsonApiHealthGet200ResponseChecksPdpOneOf1) == "{}" { // empty struct
			dst.ApiHealthGet200ResponseChecksPdpOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ApiHealthGet200ResponseChecksPdpOneOf1); err != nil {
				dst.ApiHealthGet200ResponseChecksPdpOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiHealthGet200ResponseChecksPdpOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ApiHealthGet200ResponseChecksPdpOneOf = nil
		dst.ApiHealthGet200ResponseChecksPdpOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ApiHealthGet200ResponseChecksPdp)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(ApiHealthGet200ResponseChecksPdp): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(ApiHealthGet200ResponseChecksPdp)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApiHealthGet200ResponseChecksPdp) MarshalJSON() ([]byte, error) {
	if src.ApiHealthGet200ResponseChecksPdpOneOf != nil {
		return json.Marshal(&src.ApiHealthGet200ResponseChecksPdpOneOf)
	}

	if src.ApiHealthGet200ResponseChecksPdpOneOf1 != nil {
		return json.Marshal(&src.ApiHealthGet200ResponseChecksPdpOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApiHealthGet200ResponseChecksPdp) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApiHealthGet200ResponseChecksPdpOneOf != nil {
		return obj.ApiHealthGet200ResponseChecksPdpOneOf
	}

	if obj.ApiHealthGet200ResponseChecksPdpOneOf1 != nil {
		return obj.ApiHealthGet200ResponseChecksPdpOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ApiHealthGet200ResponseChecksPdp) GetActualInstanceValue() (interface{}) {
	if obj.ApiHealthGet200ResponseChecksPdpOneOf != nil {
		return *obj.ApiHealthGet200ResponseChecksPdpOneOf
	}

	if obj.ApiHealthGet200ResponseChecksPdpOneOf1 != nil {
		return *obj.ApiHealthGet200ResponseChecksPdpOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableApiHealthGet200ResponseChecksPdp struct {
	value *ApiHealthGet200ResponseChecksPdp
	isSet bool
}

func (v NullableApiHealthGet200ResponseChecksPdp) Get() *ApiHealthGet200ResponseChecksPdp {
	return v.value
}

func (v *NullableApiHealthGet200ResponseChecksPdp) Set(val *ApiHealthGet200ResponseChecksPdp) {
	v.value = val
	v.isSet = true
}

func (v NullableApiHealthGet200ResponseChecksPdp) IsSet() bool {
	return v.isSet
}

func (v *NullableApiHealthGet200ResponseChecksPdp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiHealthGet200ResponseChecksPdp(val *ApiHealthGet200ResponseChecksPdp) *NullableApiHealthGet200ResponseChecksPdp {
	return &NullableApiHealthGet200ResponseChecksPdp{value: val, isSet: true}
}

func (v NullableApiHealthGet200ResponseChecksPdp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiHealthGet200ResponseChecksPdp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


