/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// CampaignLifecycleState A campaign's AUTHORING state, owned by the advertiser console (YT-0101). Distinct from CampaignStatus, which is what a viewer sees: draft, in_review and rejected have no public form at all. The set is the union of two incomplete ones — 'rejected' (review said no, it never ran) and 'ended' (it ran and finished) are different facts and a model needs both. Transitions are enumerated, not ad hoc: there is deliberately no draft->live, because a campaign that can publish itself makes review advisory.
type CampaignLifecycleState string

// List of CampaignLifecycleState
const (
	CAMPAIGNLIFECYCLESTATE_DRAFT CampaignLifecycleState = "draft"
	CAMPAIGNLIFECYCLESTATE_IN_REVIEW CampaignLifecycleState = "in_review"
	CAMPAIGNLIFECYCLESTATE_REJECTED CampaignLifecycleState = "rejected"
	CAMPAIGNLIFECYCLESTATE_LIVE CampaignLifecycleState = "live"
	CAMPAIGNLIFECYCLESTATE_PAUSED CampaignLifecycleState = "paused"
	CAMPAIGNLIFECYCLESTATE_ENDED CampaignLifecycleState = "ended"
)

// All allowed values of CampaignLifecycleState enum
var AllowedCampaignLifecycleStateEnumValues = []CampaignLifecycleState{
	"draft",
	"in_review",
	"rejected",
	"live",
	"paused",
	"ended",
}

func (v *CampaignLifecycleState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CampaignLifecycleState(value)
	for _, existing := range AllowedCampaignLifecycleStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CampaignLifecycleState", value)
}

// NewCampaignLifecycleStateFromValue returns a pointer to a valid CampaignLifecycleState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCampaignLifecycleStateFromValue(v string) (*CampaignLifecycleState, error) {
	ev := CampaignLifecycleState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CampaignLifecycleState: valid values are %v", v, AllowedCampaignLifecycleStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CampaignLifecycleState) IsValid() bool {
	for _, existing := range AllowedCampaignLifecycleStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CampaignLifecycleState value
func (v CampaignLifecycleState) Ptr() *CampaignLifecycleState {
	return &v
}

type NullableCampaignLifecycleState struct {
	value *CampaignLifecycleState
	isSet bool
}

func (v NullableCampaignLifecycleState) Get() *CampaignLifecycleState {
	return v.value
}

func (v *NullableCampaignLifecycleState) Set(val *CampaignLifecycleState) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignLifecycleState) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignLifecycleState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignLifecycleState(val *CampaignLifecycleState) *NullableCampaignLifecycleState {
	return &NullableCampaignLifecycleState{value: val, isSet: true}
}

func (v NullableCampaignLifecycleState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignLifecycleState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

