/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiGuardianTokenGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGuardianTokenGet200Response{}

// ApiGuardianTokenGet200Response struct for ApiGuardianTokenGet200Response
type ApiGuardianTokenGet200Response struct {
	Status string `json:"status"`
	DisplayName NullableString `json:"displayName"`
	Region string `json:"region"`
	Locale string `json:"locale"`
	AdditionalProperties map[string]interface{}
}

type _ApiGuardianTokenGet200Response ApiGuardianTokenGet200Response

// NewApiGuardianTokenGet200Response instantiates a new ApiGuardianTokenGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGuardianTokenGet200Response(status string, displayName NullableString, region string, locale string) *ApiGuardianTokenGet200Response {
	this := ApiGuardianTokenGet200Response{}
	this.Status = status
	this.DisplayName = displayName
	this.Region = region
	this.Locale = locale
	return &this
}

// NewApiGuardianTokenGet200ResponseWithDefaults instantiates a new ApiGuardianTokenGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGuardianTokenGet200ResponseWithDefaults() *ApiGuardianTokenGet200Response {
	this := ApiGuardianTokenGet200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *ApiGuardianTokenGet200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiGuardianTokenGet200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiGuardianTokenGet200Response) SetStatus(v string) {
	o.Status = v
}

// GetDisplayName returns the DisplayName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiGuardianTokenGet200Response) GetDisplayName() string {
	if o == nil || o.DisplayName.Get() == nil {
		var ret string
		return ret
	}

	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiGuardianTokenGet200Response) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// SetDisplayName sets field value
func (o *ApiGuardianTokenGet200Response) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// GetRegion returns the Region field value
func (o *ApiGuardianTokenGet200Response) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *ApiGuardianTokenGet200Response) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *ApiGuardianTokenGet200Response) SetRegion(v string) {
	o.Region = v
}

// GetLocale returns the Locale field value
func (o *ApiGuardianTokenGet200Response) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *ApiGuardianTokenGet200Response) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *ApiGuardianTokenGet200Response) SetLocale(v string) {
	o.Locale = v
}

func (o ApiGuardianTokenGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGuardianTokenGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["displayName"] = o.DisplayName.Get()
	toSerialize["region"] = o.Region
	toSerialize["locale"] = o.Locale

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiGuardianTokenGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"displayName",
		"region",
		"locale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGuardianTokenGet200Response := _ApiGuardianTokenGet200Response{}

	err = json.Unmarshal(data, &varApiGuardianTokenGet200Response)

	if err != nil {
		return err
	}

	*o = ApiGuardianTokenGet200Response(varApiGuardianTokenGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "region")
		delete(additionalProperties, "locale")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiGuardianTokenGet200Response struct {
	value *ApiGuardianTokenGet200Response
	isSet bool
}

func (v NullableApiGuardianTokenGet200Response) Get() *ApiGuardianTokenGet200Response {
	return v.value
}

func (v *NullableApiGuardianTokenGet200Response) Set(val *ApiGuardianTokenGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGuardianTokenGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGuardianTokenGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGuardianTokenGet200Response(val *ApiGuardianTokenGet200Response) *NullableApiGuardianTokenGet200Response {
	return &NullableApiGuardianTokenGet200Response{value: val, isSet: true}
}

func (v NullableApiGuardianTokenGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGuardianTokenGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


