/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckoutQuoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutQuoteRequest{}

// CheckoutQuoteRequest Ask for a listing's points price, held for 15 minutes (4.7).
type CheckoutQuoteRequest struct {
	ListingId string `json:"listingId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
}

type _CheckoutQuoteRequest CheckoutQuoteRequest

// NewCheckoutQuoteRequest instantiates a new CheckoutQuoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutQuoteRequest(listingId string) *CheckoutQuoteRequest {
	this := CheckoutQuoteRequest{}
	this.ListingId = listingId
	return &this
}

// NewCheckoutQuoteRequestWithDefaults instantiates a new CheckoutQuoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutQuoteRequestWithDefaults() *CheckoutQuoteRequest {
	this := CheckoutQuoteRequest{}
	return &this
}

// GetListingId returns the ListingId field value
func (o *CheckoutQuoteRequest) GetListingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ListingId
}

// GetListingIdOk returns a tuple with the ListingId field value
// and a boolean to check if the value has been set.
func (o *CheckoutQuoteRequest) GetListingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListingId, true
}

// SetListingId sets field value
func (o *CheckoutQuoteRequest) SetListingId(v string) {
	o.ListingId = v
}

func (o CheckoutQuoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutQuoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["listingId"] = o.ListingId
	return toSerialize, nil
}

func (o *CheckoutQuoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"listingId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckoutQuoteRequest := _CheckoutQuoteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckoutQuoteRequest)

	if err != nil {
		return err
	}

	*o = CheckoutQuoteRequest(varCheckoutQuoteRequest)

	return err
}

type NullableCheckoutQuoteRequest struct {
	value *CheckoutQuoteRequest
	isSet bool
}

func (v NullableCheckoutQuoteRequest) Get() *CheckoutQuoteRequest {
	return v.value
}

func (v *NullableCheckoutQuoteRequest) Set(val *CheckoutQuoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutQuoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutQuoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutQuoteRequest(val *CheckoutQuoteRequest) *NullableCheckoutQuoteRequest {
	return &NullableCheckoutQuoteRequest{value: val, isSet: true}
}

func (v NullableCheckoutQuoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutQuoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


