/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiTenantIdStudioDevelopersWebhooksPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTenantIdStudioDevelopersWebhooksPostRequest{}

// ApiTenantIdStudioDevelopersWebhooksPostRequest struct for ApiTenantIdStudioDevelopersWebhooksPostRequest
type ApiTenantIdStudioDevelopersWebhooksPostRequest struct {
	Url NullableString `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _ApiTenantIdStudioDevelopersWebhooksPostRequest ApiTenantIdStudioDevelopersWebhooksPostRequest

// NewApiTenantIdStudioDevelopersWebhooksPostRequest instantiates a new ApiTenantIdStudioDevelopersWebhooksPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTenantIdStudioDevelopersWebhooksPostRequest(url NullableString) *ApiTenantIdStudioDevelopersWebhooksPostRequest {
	this := ApiTenantIdStudioDevelopersWebhooksPostRequest{}
	this.Url = url
	return &this
}

// NewApiTenantIdStudioDevelopersWebhooksPostRequestWithDefaults instantiates a new ApiTenantIdStudioDevelopersWebhooksPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTenantIdStudioDevelopersWebhooksPostRequestWithDefaults() *ApiTenantIdStudioDevelopersWebhooksPostRequest {
	this := ApiTenantIdStudioDevelopersWebhooksPostRequest{}
	return &this
}

// GetUrl returns the Url field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiTenantIdStudioDevelopersWebhooksPostRequest) GetUrl() string {
	if o == nil || o.Url.Get() == nil {
		var ret string
		return ret
	}

	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTenantIdStudioDevelopersWebhooksPostRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// SetUrl sets field value
func (o *ApiTenantIdStudioDevelopersWebhooksPostRequest) SetUrl(v string) {
	o.Url.Set(&v)
}

func (o ApiTenantIdStudioDevelopersWebhooksPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTenantIdStudioDevelopersWebhooksPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiTenantIdStudioDevelopersWebhooksPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTenantIdStudioDevelopersWebhooksPostRequest := _ApiTenantIdStudioDevelopersWebhooksPostRequest{}

	err = json.Unmarshal(data, &varApiTenantIdStudioDevelopersWebhooksPostRequest)

	if err != nil {
		return err
	}

	*o = ApiTenantIdStudioDevelopersWebhooksPostRequest(varApiTenantIdStudioDevelopersWebhooksPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiTenantIdStudioDevelopersWebhooksPostRequest struct {
	value *ApiTenantIdStudioDevelopersWebhooksPostRequest
	isSet bool
}

func (v NullableApiTenantIdStudioDevelopersWebhooksPostRequest) Get() *ApiTenantIdStudioDevelopersWebhooksPostRequest {
	return v.value
}

func (v *NullableApiTenantIdStudioDevelopersWebhooksPostRequest) Set(val *ApiTenantIdStudioDevelopersWebhooksPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTenantIdStudioDevelopersWebhooksPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTenantIdStudioDevelopersWebhooksPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTenantIdStudioDevelopersWebhooksPostRequest(val *ApiTenantIdStudioDevelopersWebhooksPostRequest) *NullableApiTenantIdStudioDevelopersWebhooksPostRequest {
	return &NullableApiTenantIdStudioDevelopersWebhooksPostRequest{value: val, isSet: true}
}

func (v NullableApiTenantIdStudioDevelopersWebhooksPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTenantIdStudioDevelopersWebhooksPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


