/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner{}

// ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner struct for ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner
type ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner struct {
	Id NullableString `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	ListingId NullableString `json:"listingId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	MerchantId NullableString `json:"merchantId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Quantity int64 `json:"quantity"`
	RequestedBy NullableString `json:"requestedBy" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Reason NullableString `json:"reason"`
	State string `json:"state"`
	ApprovedBy NullableString `json:"approvedBy" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	DecidedAt NullableTime `json:"decidedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"`
	MintedBatchId NullableString `json:"mintedBatchId"`
	CreatedAt time.Time `json:"createdAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner

// NewApiStaffModerationVoucherBatchesGet200ResponseRequestsInner instantiates a new ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffModerationVoucherBatchesGet200ResponseRequestsInner(id NullableString, listingId NullableString, merchantId NullableString, quantity int64, requestedBy NullableString, reason NullableString, state string, approvedBy NullableString, decidedAt NullableTime, mintedBatchId NullableString, createdAt time.Time) *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner {
	this := ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner{}
	this.Id = id
	this.ListingId = listingId
	this.MerchantId = merchantId
	this.Quantity = quantity
	this.RequestedBy = requestedBy
	this.Reason = reason
	this.State = state
	this.ApprovedBy = approvedBy
	this.DecidedAt = decidedAt
	this.MintedBatchId = mintedBatchId
	this.CreatedAt = createdAt
	return &this
}

// NewApiStaffModerationVoucherBatchesGet200ResponseRequestsInnerWithDefaults instantiates a new ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffModerationVoucherBatchesGet200ResponseRequestsInnerWithDefaults() *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner {
	this := ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetId(v string) {
	o.Id.Set(&v)
}

// GetListingId returns the ListingId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetListingId() string {
	if o == nil || o.ListingId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ListingId.Get()
}

// GetListingIdOk returns a tuple with the ListingId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetListingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ListingId.Get(), o.ListingId.IsSet()
}

// SetListingId sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetListingId(v string) {
	o.ListingId.Set(&v)
}

// GetMerchantId returns the MerchantId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetMerchantId() string {
	if o == nil || o.MerchantId.Get() == nil {
		var ret string
		return ret
	}

	return *o.MerchantId.Get()
}

// GetMerchantIdOk returns a tuple with the MerchantId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetMerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantId.Get(), o.MerchantId.IsSet()
}

// SetMerchantId sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetMerchantId(v string) {
	o.MerchantId.Set(&v)
}

// GetQuantity returns the Quantity field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetQuantity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetQuantityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetQuantity(v int64) {
	o.Quantity = v
}

// GetRequestedBy returns the RequestedBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetRequestedBy() string {
	if o == nil || o.RequestedBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.RequestedBy.Get()
}

// GetRequestedByOk returns a tuple with the RequestedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetRequestedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestedBy.Get(), o.RequestedBy.IsSet()
}

// SetRequestedBy sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetRequestedBy(v string) {
	o.RequestedBy.Set(&v)
}

// GetReason returns the Reason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetReason() string {
	if o == nil || o.Reason.Get() == nil {
		var ret string
		return ret
	}

	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// SetReason sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetReason(v string) {
	o.Reason.Set(&v)
}

// GetState returns the State field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetState(v string) {
	o.State = v
}

// GetApprovedBy returns the ApprovedBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetApprovedBy() string {
	if o == nil || o.ApprovedBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApprovedBy.Get()
}

// GetApprovedByOk returns a tuple with the ApprovedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetApprovedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApprovedBy.Get(), o.ApprovedBy.IsSet()
}

// SetApprovedBy sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetApprovedBy(v string) {
	o.ApprovedBy.Set(&v)
}

// GetDecidedAt returns the DecidedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetDecidedAt() time.Time {
	if o == nil || o.DecidedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DecidedAt.Get()
}

// GetDecidedAtOk returns a tuple with the DecidedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetDecidedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DecidedAt.Get(), o.DecidedAt.IsSet()
}

// SetDecidedAt sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetDecidedAt(v time.Time) {
	o.DecidedAt.Set(&v)
}

// GetMintedBatchId returns the MintedBatchId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetMintedBatchId() string {
	if o == nil || o.MintedBatchId.Get() == nil {
		var ret string
		return ret
	}

	return *o.MintedBatchId.Get()
}

// GetMintedBatchIdOk returns a tuple with the MintedBatchId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetMintedBatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MintedBatchId.Get(), o.MintedBatchId.IsSet()
}

// SetMintedBatchId sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetMintedBatchId(v string) {
	o.MintedBatchId.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	toSerialize["listingId"] = o.ListingId.Get()
	toSerialize["merchantId"] = o.MerchantId.Get()
	toSerialize["quantity"] = o.Quantity
	toSerialize["requestedBy"] = o.RequestedBy.Get()
	toSerialize["reason"] = o.Reason.Get()
	toSerialize["state"] = o.State
	toSerialize["approvedBy"] = o.ApprovedBy.Get()
	toSerialize["decidedAt"] = o.DecidedAt.Get()
	toSerialize["mintedBatchId"] = o.MintedBatchId.Get()
	toSerialize["createdAt"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"listingId",
		"merchantId",
		"quantity",
		"requestedBy",
		"reason",
		"state",
		"approvedBy",
		"decidedAt",
		"mintedBatchId",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffModerationVoucherBatchesGet200ResponseRequestsInner := _ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner{}

	err = json.Unmarshal(data, &varApiStaffModerationVoucherBatchesGet200ResponseRequestsInner)

	if err != nil {
		return err
	}

	*o = ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner(varApiStaffModerationVoucherBatchesGet200ResponseRequestsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "listingId")
		delete(additionalProperties, "merchantId")
		delete(additionalProperties, "quantity")
		delete(additionalProperties, "requestedBy")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "state")
		delete(additionalProperties, "approvedBy")
		delete(additionalProperties, "decidedAt")
		delete(additionalProperties, "mintedBatchId")
		delete(additionalProperties, "createdAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner struct {
	value *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner
	isSet bool
}

func (v NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) Get() *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner {
	return v.value
}

func (v *NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) Set(val *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner(val *ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) *NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner {
	return &NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner{value: val, isSet: true}
}

func (v NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


