/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CounterLogEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CounterLogEntry{}

// CounterLogEntry One row of GET /api/counter/log — today's captures at this device only.
type CounterLogEntry struct {
	CaptureId string `json:"captureId"`
	VoucherId NullableString `json:"voucherId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	// A whole number of some currency's minor unit, WITHOUT saying which (YT-0513). The currency is a sibling field on the same record — listingSchema.currency, voucherSchema.currency — one per record, so an amount can never be stored without its currency and two amounts on one record can never disagree. This replaced IdrMinorUnits on the wire: that brand named a currency it did not always hold, and AU fixtures stored AUD cents in a field typed IdrMinorUnits. Not a nested Money object, because the contracts-to-migrations drift gate maps each field to a snake_case column and a nested object needs columns corresponding to nothing; callers compose money(record.fooMinor, record.currency) at the point of use.
	AmountMinor int64 `json:"amountMinor"`
	Currency Currency `json:"currency"`
	CapturedAt time.Time `json:"capturedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	OrderRef string `json:"orderRef"`
	AuthorizedAt time.Time `json:"authorizedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _CounterLogEntry CounterLogEntry

// NewCounterLogEntry instantiates a new CounterLogEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCounterLogEntry(captureId string, voucherId NullableString, amountMinor int64, currency Currency, capturedAt time.Time, orderRef string, authorizedAt time.Time) *CounterLogEntry {
	this := CounterLogEntry{}
	this.CaptureId = captureId
	this.VoucherId = voucherId
	this.AmountMinor = amountMinor
	this.Currency = currency
	this.CapturedAt = capturedAt
	this.OrderRef = orderRef
	this.AuthorizedAt = authorizedAt
	return &this
}

// NewCounterLogEntryWithDefaults instantiates a new CounterLogEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCounterLogEntryWithDefaults() *CounterLogEntry {
	this := CounterLogEntry{}
	return &this
}

// GetCaptureId returns the CaptureId field value
func (o *CounterLogEntry) GetCaptureId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CaptureId
}

// GetCaptureIdOk returns a tuple with the CaptureId field value
// and a boolean to check if the value has been set.
func (o *CounterLogEntry) GetCaptureIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaptureId, true
}

// SetCaptureId sets field value
func (o *CounterLogEntry) SetCaptureId(v string) {
	o.CaptureId = v
}

// GetVoucherId returns the VoucherId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CounterLogEntry) GetVoucherId() string {
	if o == nil || o.VoucherId.Get() == nil {
		var ret string
		return ret
	}

	return *o.VoucherId.Get()
}

// GetVoucherIdOk returns a tuple with the VoucherId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CounterLogEntry) GetVoucherIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherId.Get(), o.VoucherId.IsSet()
}

// SetVoucherId sets field value
func (o *CounterLogEntry) SetVoucherId(v string) {
	o.VoucherId.Set(&v)
}

// GetAmountMinor returns the AmountMinor field value
func (o *CounterLogEntry) GetAmountMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value
// and a boolean to check if the value has been set.
func (o *CounterLogEntry) GetAmountMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountMinor, true
}

// SetAmountMinor sets field value
func (o *CounterLogEntry) SetAmountMinor(v int64) {
	o.AmountMinor = v
}

// GetCurrency returns the Currency field value
func (o *CounterLogEntry) GetCurrency() Currency {
	if o == nil {
		var ret Currency
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CounterLogEntry) GetCurrencyOk() (*Currency, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CounterLogEntry) SetCurrency(v Currency) {
	o.Currency = v
}

// GetCapturedAt returns the CapturedAt field value
func (o *CounterLogEntry) GetCapturedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CapturedAt
}

// GetCapturedAtOk returns a tuple with the CapturedAt field value
// and a boolean to check if the value has been set.
func (o *CounterLogEntry) GetCapturedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapturedAt, true
}

// SetCapturedAt sets field value
func (o *CounterLogEntry) SetCapturedAt(v time.Time) {
	o.CapturedAt = v
}

// GetOrderRef returns the OrderRef field value
func (o *CounterLogEntry) GetOrderRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderRef
}

// GetOrderRefOk returns a tuple with the OrderRef field value
// and a boolean to check if the value has been set.
func (o *CounterLogEntry) GetOrderRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderRef, true
}

// SetOrderRef sets field value
func (o *CounterLogEntry) SetOrderRef(v string) {
	o.OrderRef = v
}

// GetAuthorizedAt returns the AuthorizedAt field value
func (o *CounterLogEntry) GetAuthorizedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AuthorizedAt
}

// GetAuthorizedAtOk returns a tuple with the AuthorizedAt field value
// and a boolean to check if the value has been set.
func (o *CounterLogEntry) GetAuthorizedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizedAt, true
}

// SetAuthorizedAt sets field value
func (o *CounterLogEntry) SetAuthorizedAt(v time.Time) {
	o.AuthorizedAt = v
}

func (o CounterLogEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CounterLogEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["captureId"] = o.CaptureId
	toSerialize["voucherId"] = o.VoucherId.Get()
	toSerialize["amountMinor"] = o.AmountMinor
	toSerialize["currency"] = o.Currency
	toSerialize["capturedAt"] = o.CapturedAt
	toSerialize["orderRef"] = o.OrderRef
	toSerialize["authorizedAt"] = o.AuthorizedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CounterLogEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"captureId",
		"voucherId",
		"amountMinor",
		"currency",
		"capturedAt",
		"orderRef",
		"authorizedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCounterLogEntry := _CounterLogEntry{}

	err = json.Unmarshal(data, &varCounterLogEntry)

	if err != nil {
		return err
	}

	*o = CounterLogEntry(varCounterLogEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "captureId")
		delete(additionalProperties, "voucherId")
		delete(additionalProperties, "amountMinor")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "capturedAt")
		delete(additionalProperties, "orderRef")
		delete(additionalProperties, "authorizedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCounterLogEntry struct {
	value *CounterLogEntry
	isSet bool
}

func (v NullableCounterLogEntry) Get() *CounterLogEntry {
	return v.value
}

func (v *NullableCounterLogEntry) Set(val *CounterLogEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableCounterLogEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableCounterLogEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCounterLogEntry(val *CounterLogEntry) *NullableCounterLogEntry {
	return &NullableCounterLogEntry{value: val, isSet: true}
}

func (v NullableCounterLogEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCounterLogEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


