/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiateMediaUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateMediaUploadRequest{}

// InitiateMediaUploadRequest Starts a presigned multipart upload of a campaign's video, to MinIO's raw/ prefix.
type InitiateMediaUploadRequest struct {
	CampaignId string `json:"campaignId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Filename string `json:"filename"`
	ContentType string `json:"contentType"`
	SizeBytes int32 `json:"sizeBytes"`
	TeaserStartSeconds int64 `json:"teaserStartSeconds"`
}

type _InitiateMediaUploadRequest InitiateMediaUploadRequest

// NewInitiateMediaUploadRequest instantiates a new InitiateMediaUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateMediaUploadRequest(campaignId string, filename string, contentType string, sizeBytes int32, teaserStartSeconds int64) *InitiateMediaUploadRequest {
	this := InitiateMediaUploadRequest{}
	this.CampaignId = campaignId
	this.Filename = filename
	this.ContentType = contentType
	this.SizeBytes = sizeBytes
	this.TeaserStartSeconds = teaserStartSeconds
	return &this
}

// NewInitiateMediaUploadRequestWithDefaults instantiates a new InitiateMediaUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateMediaUploadRequestWithDefaults() *InitiateMediaUploadRequest {
	this := InitiateMediaUploadRequest{}
	var teaserStartSeconds int64 = 0
	this.TeaserStartSeconds = teaserStartSeconds
	return &this
}

// GetCampaignId returns the CampaignId field value
func (o *InitiateMediaUploadRequest) GetCampaignId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *InitiateMediaUploadRequest) GetCampaignIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *InitiateMediaUploadRequest) SetCampaignId(v string) {
	o.CampaignId = v
}

// GetFilename returns the Filename field value
func (o *InitiateMediaUploadRequest) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *InitiateMediaUploadRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *InitiateMediaUploadRequest) SetFilename(v string) {
	o.Filename = v
}

// GetContentType returns the ContentType field value
func (o *InitiateMediaUploadRequest) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *InitiateMediaUploadRequest) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *InitiateMediaUploadRequest) SetContentType(v string) {
	o.ContentType = v
}

// GetSizeBytes returns the SizeBytes field value
func (o *InitiateMediaUploadRequest) GetSizeBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *InitiateMediaUploadRequest) GetSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *InitiateMediaUploadRequest) SetSizeBytes(v int32) {
	o.SizeBytes = v
}

// GetTeaserStartSeconds returns the TeaserStartSeconds field value
func (o *InitiateMediaUploadRequest) GetTeaserStartSeconds() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TeaserStartSeconds
}

// GetTeaserStartSecondsOk returns a tuple with the TeaserStartSeconds field value
// and a boolean to check if the value has been set.
func (o *InitiateMediaUploadRequest) GetTeaserStartSecondsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeaserStartSeconds, true
}

// SetTeaserStartSeconds sets field value
func (o *InitiateMediaUploadRequest) SetTeaserStartSeconds(v int64) {
	o.TeaserStartSeconds = v
}

func (o InitiateMediaUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateMediaUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaignId"] = o.CampaignId
	toSerialize["filename"] = o.Filename
	toSerialize["contentType"] = o.ContentType
	toSerialize["sizeBytes"] = o.SizeBytes
	toSerialize["teaserStartSeconds"] = o.TeaserStartSeconds
	return toSerialize, nil
}

func (o *InitiateMediaUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"campaignId",
		"filename",
		"contentType",
		"sizeBytes",
		"teaserStartSeconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiateMediaUploadRequest := _InitiateMediaUploadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiateMediaUploadRequest)

	if err != nil {
		return err
	}

	*o = InitiateMediaUploadRequest(varInitiateMediaUploadRequest)

	return err
}

type NullableInitiateMediaUploadRequest struct {
	value *InitiateMediaUploadRequest
	isSet bool
}

func (v NullableInitiateMediaUploadRequest) Get() *InitiateMediaUploadRequest {
	return v.value
}

func (v *NullableInitiateMediaUploadRequest) Set(val *InitiateMediaUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateMediaUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateMediaUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateMediaUploadRequest(val *InitiateMediaUploadRequest) *NullableInitiateMediaUploadRequest {
	return &NullableInitiateMediaUploadRequest{value: val, isSet: true}
}

func (v NullableInitiateMediaUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateMediaUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


