/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// DisputeReason Why a voucher was not honoured. A closed list: no viewer free text reaches staff.
type DisputeReason string

// List of DisputeReason
const (
	DISPUTEREASON_NOT_HONOURED DisputeReason = "not_honoured"
	DISPUTEREASON_MERCHANT_CLOSED DisputeReason = "merchant_closed"
	DISPUTEREASON_OTHER DisputeReason = "other"
)

// All allowed values of DisputeReason enum
var AllowedDisputeReasonEnumValues = []DisputeReason{
	"not_honoured",
	"merchant_closed",
	"other",
}

func (v *DisputeReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DisputeReason(value)
	for _, existing := range AllowedDisputeReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DisputeReason", value)
}

// NewDisputeReasonFromValue returns a pointer to a valid DisputeReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDisputeReasonFromValue(v string) (*DisputeReason, error) {
	ev := DisputeReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DisputeReason: valid values are %v", v, AllowedDisputeReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DisputeReason) IsValid() bool {
	for _, existing := range AllowedDisputeReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DisputeReason value
func (v DisputeReason) Ptr() *DisputeReason {
	return &v
}

type NullableDisputeReason struct {
	value *DisputeReason
	isSet bool
}

func (v NullableDisputeReason) Get() *DisputeReason {
	return v.value
}

func (v *NullableDisputeReason) Set(val *DisputeReason) {
	v.value = val
	v.isSet = true
}

func (v NullableDisputeReason) IsSet() bool {
	return v.isSet
}

func (v *NullableDisputeReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisputeReason(val *DisputeReason) *NullableDisputeReason {
	return &NullableDisputeReason{value: val, isSet: true}
}

func (v NullableDisputeReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisputeReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

