/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BoostDay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoostDay{}

// BoostDay One region-local day of boost delivery and its spend, rounded up to a minor unit.
type BoostDay struct {
	Day string `json:"day" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"`
	Impressions int64 `json:"impressions"`
	SpendMinor int64 `json:"spendMinor"`
}

type _BoostDay BoostDay

// NewBoostDay instantiates a new BoostDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoostDay(day string, impressions int64, spendMinor int64) *BoostDay {
	this := BoostDay{}
	this.Day = day
	this.Impressions = impressions
	this.SpendMinor = spendMinor
	return &this
}

// NewBoostDayWithDefaults instantiates a new BoostDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoostDayWithDefaults() *BoostDay {
	this := BoostDay{}
	return &this
}

// GetDay returns the Day field value
func (o *BoostDay) GetDay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *BoostDay) GetDayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *BoostDay) SetDay(v string) {
	o.Day = v
}

// GetImpressions returns the Impressions field value
func (o *BoostDay) GetImpressions() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Impressions
}

// GetImpressionsOk returns a tuple with the Impressions field value
// and a boolean to check if the value has been set.
func (o *BoostDay) GetImpressionsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Impressions, true
}

// SetImpressions sets field value
func (o *BoostDay) SetImpressions(v int64) {
	o.Impressions = v
}

// GetSpendMinor returns the SpendMinor field value
func (o *BoostDay) GetSpendMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SpendMinor
}

// GetSpendMinorOk returns a tuple with the SpendMinor field value
// and a boolean to check if the value has been set.
func (o *BoostDay) GetSpendMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpendMinor, true
}

// SetSpendMinor sets field value
func (o *BoostDay) SetSpendMinor(v int64) {
	o.SpendMinor = v
}

func (o BoostDay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoostDay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["day"] = o.Day
	toSerialize["impressions"] = o.Impressions
	toSerialize["spendMinor"] = o.SpendMinor
	return toSerialize, nil
}

func (o *BoostDay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"day",
		"impressions",
		"spendMinor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoostDay := _BoostDay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBoostDay)

	if err != nil {
		return err
	}

	*o = BoostDay(varBoostDay)

	return err
}

type NullableBoostDay struct {
	value *BoostDay
	isSet bool
}

func (v NullableBoostDay) Get() *BoostDay {
	return v.value
}

func (v *NullableBoostDay) Set(val *BoostDay) {
	v.value = val
	v.isSet = true
}

func (v NullableBoostDay) IsSet() bool {
	return v.isSet
}

func (v *NullableBoostDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoostDay(val *BoostDay) *NullableBoostDay {
	return &NullableBoostDay{value: val, isSet: true}
}

func (v NullableBoostDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoostDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


