/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// AuctionRefusal Why a listing or a bid was refused (409).
type AuctionRefusal string

// List of AuctionRefusal
const (
	AUCTIONREFUSAL_CHARITY_UNAVAILABLE AuctionRefusal = "charity_unavailable"
	AUCTIONREFUSAL_VOUCHER_NOT_UNUSED AuctionRefusal = "voucher_not_unused"
	AUCTIONREFUSAL_VOUCHER_NOT_TRANSFERABLE AuctionRefusal = "voucher_not_transferable"
	AUCTIONREFUSAL_VOUCHER_ALREADY_TRANSFERRED AuctionRefusal = "voucher_already_transferred"
	AUCTIONREFUSAL_SELLER_INELIGIBLE AuctionRefusal = "seller_ineligible"
	AUCTIONREFUSAL_BIDDER_INELIGIBLE AuctionRefusal = "bidder_ineligible"
	AUCTIONREFUSAL_OWN_AUCTION AuctionRefusal = "own_auction"
	AUCTIONREFUSAL_AUCTION_CLOSED AuctionRefusal = "auction_closed"
	AUCTIONREFUSAL_BID_TOO_LOW AuctionRefusal = "bid_too_low"
	AUCTIONREFUSAL_PAYMENT_DECLINED AuctionRefusal = "payment_declined"
)

// All allowed values of AuctionRefusal enum
var AllowedAuctionRefusalEnumValues = []AuctionRefusal{
	"charity_unavailable",
	"voucher_not_unused",
	"voucher_not_transferable",
	"voucher_already_transferred",
	"seller_ineligible",
	"bidder_ineligible",
	"own_auction",
	"auction_closed",
	"bid_too_low",
	"payment_declined",
}

func (v *AuctionRefusal) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuctionRefusal(value)
	for _, existing := range AllowedAuctionRefusalEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuctionRefusal", value)
}

// NewAuctionRefusalFromValue returns a pointer to a valid AuctionRefusal
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuctionRefusalFromValue(v string) (*AuctionRefusal, error) {
	ev := AuctionRefusal(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuctionRefusal: valid values are %v", v, AllowedAuctionRefusalEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuctionRefusal) IsValid() bool {
	for _, existing := range AllowedAuctionRefusalEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuctionRefusal value
func (v AuctionRefusal) Ptr() *AuctionRefusal {
	return &v
}

type NullableAuctionRefusal struct {
	value *AuctionRefusal
	isSet bool
}

func (v NullableAuctionRefusal) Get() *AuctionRefusal {
	return v.value
}

func (v *NullableAuctionRefusal) Set(val *AuctionRefusal) {
	v.value = val
	v.isSet = true
}

func (v NullableAuctionRefusal) IsSet() bool {
	return v.isSet
}

func (v *NullableAuctionRefusal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuctionRefusal(val *AuctionRefusal) *NullableAuctionRefusal {
	return &NullableAuctionRefusal{value: val, isSet: true}
}

func (v NullableAuctionRefusal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuctionRefusal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

