/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicCharity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicCharity{}

// PublicCharity An approved charity as a viewer in its region sees it.
type PublicCharity struct {
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Region Region `json:"region"`
	Name string `json:"name"`
	Cause CharityCause `json:"cause"`
	Summary string `json:"summary"`
	LogoUrl NullableString `json:"logoUrl"`
}

type _PublicCharity PublicCharity

// NewPublicCharity instantiates a new PublicCharity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicCharity(id string, region Region, name string, cause CharityCause, summary string, logoUrl NullableString) *PublicCharity {
	this := PublicCharity{}
	this.Id = id
	this.Region = region
	this.Name = name
	this.Cause = cause
	this.Summary = summary
	this.LogoUrl = logoUrl
	return &this
}

// NewPublicCharityWithDefaults instantiates a new PublicCharity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicCharityWithDefaults() *PublicCharity {
	this := PublicCharity{}
	return &this
}

// GetId returns the Id field value
func (o *PublicCharity) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublicCharity) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublicCharity) SetId(v string) {
	o.Id = v
}

// GetRegion returns the Region field value
func (o *PublicCharity) GetRegion() Region {
	if o == nil {
		var ret Region
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *PublicCharity) GetRegionOk() (*Region, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *PublicCharity) SetRegion(v Region) {
	o.Region = v
}

// GetName returns the Name field value
func (o *PublicCharity) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PublicCharity) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PublicCharity) SetName(v string) {
	o.Name = v
}

// GetCause returns the Cause field value
func (o *PublicCharity) GetCause() CharityCause {
	if o == nil {
		var ret CharityCause
		return ret
	}

	return o.Cause
}

// GetCauseOk returns a tuple with the Cause field value
// and a boolean to check if the value has been set.
func (o *PublicCharity) GetCauseOk() (*CharityCause, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cause, true
}

// SetCause sets field value
func (o *PublicCharity) SetCause(v CharityCause) {
	o.Cause = v
}

// GetSummary returns the Summary field value
func (o *PublicCharity) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *PublicCharity) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *PublicCharity) SetSummary(v string) {
	o.Summary = v
}

// GetLogoUrl returns the LogoUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PublicCharity) GetLogoUrl() string {
	if o == nil || o.LogoUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.LogoUrl.Get()
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicCharity) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoUrl.Get(), o.LogoUrl.IsSet()
}

// SetLogoUrl sets field value
func (o *PublicCharity) SetLogoUrl(v string) {
	o.LogoUrl.Set(&v)
}

func (o PublicCharity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicCharity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["region"] = o.Region
	toSerialize["name"] = o.Name
	toSerialize["cause"] = o.Cause
	toSerialize["summary"] = o.Summary
	toSerialize["logoUrl"] = o.LogoUrl.Get()
	return toSerialize, nil
}

func (o *PublicCharity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"region",
		"name",
		"cause",
		"summary",
		"logoUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicCharity := _PublicCharity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicCharity)

	if err != nil {
		return err
	}

	*o = PublicCharity(varPublicCharity)

	return err
}

type NullablePublicCharity struct {
	value *PublicCharity
	isSet bool
}

func (v NullablePublicCharity) Get() *PublicCharity {
	return v.value
}

func (v *NullablePublicCharity) Set(val *PublicCharity) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicCharity) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicCharity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicCharity(val *PublicCharity) *NullablePublicCharity {
	return &NullablePublicCharity{value: val, isSet: true}
}

func (v NullablePublicCharity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicCharity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


