/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ApiStaffRiskQueueGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffRiskQueueGet200ResponseInner{}

// ApiStaffRiskQueueGet200ResponseInner struct for ApiStaffRiskQueueGet200ResponseInner
type ApiStaffRiskQueueGet200ResponseInner struct {
	Id string `json:"id"`
	UserId string `json:"userId"`
	Region NullableString `json:"region"`
	Severity string `json:"severity"`
	Reason string `json:"reason"`
	Signals []ApiStaffRiskQueueGet200ResponseInnerSignalsInner `json:"signals"`
	EscrowId *string `json:"escrowId,omitempty"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"createdAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffRiskQueueGet200ResponseInner ApiStaffRiskQueueGet200ResponseInner

// NewApiStaffRiskQueueGet200ResponseInner instantiates a new ApiStaffRiskQueueGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffRiskQueueGet200ResponseInner(id string, userId string, region NullableString, severity string, reason string, signals []ApiStaffRiskQueueGet200ResponseInnerSignalsInner, status string, createdAt time.Time) *ApiStaffRiskQueueGet200ResponseInner {
	this := ApiStaffRiskQueueGet200ResponseInner{}
	this.Id = id
	this.UserId = userId
	this.Region = region
	this.Severity = severity
	this.Reason = reason
	this.Signals = signals
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewApiStaffRiskQueueGet200ResponseInnerWithDefaults instantiates a new ApiStaffRiskQueueGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffRiskQueueGet200ResponseInnerWithDefaults() *ApiStaffRiskQueueGet200ResponseInner {
	this := ApiStaffRiskQueueGet200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetUserId(v string) {
	o.UserId = v
}

// GetRegion returns the Region field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffRiskQueueGet200ResponseInner) GetRegion() string {
	if o == nil || o.Region.Get() == nil {
		var ret string
		return ret
	}

	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffRiskQueueGet200ResponseInner) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// SetRegion sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetRegion(v string) {
	o.Region.Set(&v)
}

// GetSeverity returns the Severity field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetSeverity(v string) {
	o.Severity = v
}

// GetReason returns the Reason field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetReason(v string) {
	o.Reason = v
}

// GetSignals returns the Signals field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetSignals() []ApiStaffRiskQueueGet200ResponseInnerSignalsInner {
	if o == nil {
		var ret []ApiStaffRiskQueueGet200ResponseInnerSignalsInner
		return ret
	}

	return o.Signals
}

// GetSignalsOk returns a tuple with the Signals field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetSignalsOk() ([]ApiStaffRiskQueueGet200ResponseInnerSignalsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Signals, true
}

// SetSignals sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetSignals(v []ApiStaffRiskQueueGet200ResponseInnerSignalsInner) {
	o.Signals = v
}

// GetEscrowId returns the EscrowId field value if set, zero value otherwise.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetEscrowId() string {
	if o == nil || IsNil(o.EscrowId) {
		var ret string
		return ret
	}
	return *o.EscrowId
}

// GetEscrowIdOk returns a tuple with the EscrowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetEscrowIdOk() (*string, bool) {
	if o == nil || IsNil(o.EscrowId) {
		return nil, false
	}
	return o.EscrowId, true
}

// HasEscrowId returns a boolean if a field has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) HasEscrowId() bool {
	if o != nil && !IsNil(o.EscrowId) {
		return true
	}

	return false
}

// SetEscrowId gets a reference to the given string and assigns it to the EscrowId field.
func (o *ApiStaffRiskQueueGet200ResponseInner) SetEscrowId(v string) {
	o.EscrowId = &v
}

// GetStatus returns the Status field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApiStaffRiskQueueGet200ResponseInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiStaffRiskQueueGet200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApiStaffRiskQueueGet200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ApiStaffRiskQueueGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffRiskQueueGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["userId"] = o.UserId
	toSerialize["region"] = o.Region.Get()
	toSerialize["severity"] = o.Severity
	toSerialize["reason"] = o.Reason
	toSerialize["signals"] = o.Signals
	if !IsNil(o.EscrowId) {
		toSerialize["escrowId"] = o.EscrowId
	}
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffRiskQueueGet200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"userId",
		"region",
		"severity",
		"reason",
		"signals",
		"status",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffRiskQueueGet200ResponseInner := _ApiStaffRiskQueueGet200ResponseInner{}

	err = json.Unmarshal(data, &varApiStaffRiskQueueGet200ResponseInner)

	if err != nil {
		return err
	}

	*o = ApiStaffRiskQueueGet200ResponseInner(varApiStaffRiskQueueGet200ResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "userId")
		delete(additionalProperties, "region")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "signals")
		delete(additionalProperties, "escrowId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "createdAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffRiskQueueGet200ResponseInner struct {
	value *ApiStaffRiskQueueGet200ResponseInner
	isSet bool
}

func (v NullableApiStaffRiskQueueGet200ResponseInner) Get() *ApiStaffRiskQueueGet200ResponseInner {
	return v.value
}

func (v *NullableApiStaffRiskQueueGet200ResponseInner) Set(val *ApiStaffRiskQueueGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffRiskQueueGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffRiskQueueGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffRiskQueueGet200ResponseInner(val *ApiStaffRiskQueueGet200ResponseInner) *NullableApiStaffRiskQueueGet200ResponseInner {
	return &NullableApiStaffRiskQueueGet200ResponseInner{value: val, isSet: true}
}

func (v NullableApiStaffRiskQueueGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffRiskQueueGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


