/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// VoucherVoidReason Why a voucher was voided. Load-bearing rather than descriptive: a voucher voided by 'transfer' became somebody else's and its value still exists (docs/09 section 7's void-and-remint), while one voided for fraud did not — so the reason is an input to the public-status derivation, and a wallet can tell its owner which happened.
type VoucherVoidReason string

// List of VoucherVoidReason
const (
	VOUCHERVOIDREASON_TRANSFER VoucherVoidReason = "transfer"
	VOUCHERVOIDREASON_FRAUD VoucherVoidReason = "fraud"
	VOUCHERVOIDREASON_REFUND_REVERSAL VoucherVoidReason = "refund_reversal"
	VOUCHERVOIDREASON_ADMIN VoucherVoidReason = "admin"
)

// All allowed values of VoucherVoidReason enum
var AllowedVoucherVoidReasonEnumValues = []VoucherVoidReason{
	"transfer",
	"fraud",
	"refund_reversal",
	"admin",
}

func (v *VoucherVoidReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VoucherVoidReason(value)
	for _, existing := range AllowedVoucherVoidReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VoucherVoidReason", value)
}

// NewVoucherVoidReasonFromValue returns a pointer to a valid VoucherVoidReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVoucherVoidReasonFromValue(v string) (*VoucherVoidReason, error) {
	ev := VoucherVoidReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VoucherVoidReason: valid values are %v", v, AllowedVoucherVoidReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VoucherVoidReason) IsValid() bool {
	for _, existing := range AllowedVoucherVoidReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VoucherVoidReason value
func (v VoucherVoidReason) Ptr() *VoucherVoidReason {
	return &v
}

type NullableVoucherVoidReason struct {
	value *VoucherVoidReason
	isSet bool
}

func (v NullableVoucherVoidReason) Get() *VoucherVoidReason {
	return v.value
}

func (v *NullableVoucherVoidReason) Set(val *VoucherVoidReason) {
	v.value = val
	v.isSet = true
}

func (v NullableVoucherVoidReason) IsSet() bool {
	return v.isSet
}

func (v *NullableVoucherVoidReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoucherVoidReason(val *VoucherVoidReason) *NullableVoucherVoidReason {
	return &NullableVoucherVoidReason{value: val, isSet: true}
}

func (v NullableVoucherVoidReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoucherVoidReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

