/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiStaffEconomyRegionOverviewGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffEconomyRegionOverviewGet200Response{}

// ApiStaffEconomyRegionOverviewGet200Response struct for ApiStaffEconomyRegionOverviewGet200Response
type ApiStaffEconomyRegionOverviewGet200Response struct {
	Region NullableString `json:"region"`
	Coverage ApiStaffEconomyRegionOverviewGet200ResponseCoverage `json:"coverage"`
	DailySeries []ApiStaffEconomyRegionOverviewGet200ResponseDailySeriesInner `json:"dailySeries"`
	ReportedSpread ApiStaffEconomyRegionOverviewGet200ResponseReportedSpread `json:"reportedSpread"`
	ManualPurchases []ApiStaffEconomyRegionOverviewGet200ResponseManualPurchasesInner `json:"manualPurchases"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffEconomyRegionOverviewGet200Response ApiStaffEconomyRegionOverviewGet200Response

// NewApiStaffEconomyRegionOverviewGet200Response instantiates a new ApiStaffEconomyRegionOverviewGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffEconomyRegionOverviewGet200Response(region NullableString, coverage ApiStaffEconomyRegionOverviewGet200ResponseCoverage, dailySeries []ApiStaffEconomyRegionOverviewGet200ResponseDailySeriesInner, reportedSpread ApiStaffEconomyRegionOverviewGet200ResponseReportedSpread, manualPurchases []ApiStaffEconomyRegionOverviewGet200ResponseManualPurchasesInner) *ApiStaffEconomyRegionOverviewGet200Response {
	this := ApiStaffEconomyRegionOverviewGet200Response{}
	this.Region = region
	this.Coverage = coverage
	this.DailySeries = dailySeries
	this.ReportedSpread = reportedSpread
	this.ManualPurchases = manualPurchases
	return &this
}

// NewApiStaffEconomyRegionOverviewGet200ResponseWithDefaults instantiates a new ApiStaffEconomyRegionOverviewGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffEconomyRegionOverviewGet200ResponseWithDefaults() *ApiStaffEconomyRegionOverviewGet200Response {
	this := ApiStaffEconomyRegionOverviewGet200Response{}
	return &this
}

// GetRegion returns the Region field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetRegion() string {
	if o == nil || o.Region.Get() == nil {
		var ret string
		return ret
	}

	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// SetRegion sets field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) SetRegion(v string) {
	o.Region.Set(&v)
}

// GetCoverage returns the Coverage field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetCoverage() ApiStaffEconomyRegionOverviewGet200ResponseCoverage {
	if o == nil {
		var ret ApiStaffEconomyRegionOverviewGet200ResponseCoverage
		return ret
	}

	return o.Coverage
}

// GetCoverageOk returns a tuple with the Coverage field value
// and a boolean to check if the value has been set.
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetCoverageOk() (*ApiStaffEconomyRegionOverviewGet200ResponseCoverage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Coverage, true
}

// SetCoverage sets field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) SetCoverage(v ApiStaffEconomyRegionOverviewGet200ResponseCoverage) {
	o.Coverage = v
}

// GetDailySeries returns the DailySeries field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetDailySeries() []ApiStaffEconomyRegionOverviewGet200ResponseDailySeriesInner {
	if o == nil {
		var ret []ApiStaffEconomyRegionOverviewGet200ResponseDailySeriesInner
		return ret
	}

	return o.DailySeries
}

// GetDailySeriesOk returns a tuple with the DailySeries field value
// and a boolean to check if the value has been set.
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetDailySeriesOk() ([]ApiStaffEconomyRegionOverviewGet200ResponseDailySeriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.DailySeries, true
}

// SetDailySeries sets field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) SetDailySeries(v []ApiStaffEconomyRegionOverviewGet200ResponseDailySeriesInner) {
	o.DailySeries = v
}

// GetReportedSpread returns the ReportedSpread field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetReportedSpread() ApiStaffEconomyRegionOverviewGet200ResponseReportedSpread {
	if o == nil {
		var ret ApiStaffEconomyRegionOverviewGet200ResponseReportedSpread
		return ret
	}

	return o.ReportedSpread
}

// GetReportedSpreadOk returns a tuple with the ReportedSpread field value
// and a boolean to check if the value has been set.
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetReportedSpreadOk() (*ApiStaffEconomyRegionOverviewGet200ResponseReportedSpread, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportedSpread, true
}

// SetReportedSpread sets field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) SetReportedSpread(v ApiStaffEconomyRegionOverviewGet200ResponseReportedSpread) {
	o.ReportedSpread = v
}

// GetManualPurchases returns the ManualPurchases field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetManualPurchases() []ApiStaffEconomyRegionOverviewGet200ResponseManualPurchasesInner {
	if o == nil {
		var ret []ApiStaffEconomyRegionOverviewGet200ResponseManualPurchasesInner
		return ret
	}

	return o.ManualPurchases
}

// GetManualPurchasesOk returns a tuple with the ManualPurchases field value
// and a boolean to check if the value has been set.
func (o *ApiStaffEconomyRegionOverviewGet200Response) GetManualPurchasesOk() ([]ApiStaffEconomyRegionOverviewGet200ResponseManualPurchasesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ManualPurchases, true
}

// SetManualPurchases sets field value
func (o *ApiStaffEconomyRegionOverviewGet200Response) SetManualPurchases(v []ApiStaffEconomyRegionOverviewGet200ResponseManualPurchasesInner) {
	o.ManualPurchases = v
}

func (o ApiStaffEconomyRegionOverviewGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffEconomyRegionOverviewGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["region"] = o.Region.Get()
	toSerialize["coverage"] = o.Coverage
	toSerialize["dailySeries"] = o.DailySeries
	toSerialize["reportedSpread"] = o.ReportedSpread
	toSerialize["manualPurchases"] = o.ManualPurchases

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffEconomyRegionOverviewGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"region",
		"coverage",
		"dailySeries",
		"reportedSpread",
		"manualPurchases",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffEconomyRegionOverviewGet200Response := _ApiStaffEconomyRegionOverviewGet200Response{}

	err = json.Unmarshal(data, &varApiStaffEconomyRegionOverviewGet200Response)

	if err != nil {
		return err
	}

	*o = ApiStaffEconomyRegionOverviewGet200Response(varApiStaffEconomyRegionOverviewGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "region")
		delete(additionalProperties, "coverage")
		delete(additionalProperties, "dailySeries")
		delete(additionalProperties, "reportedSpread")
		delete(additionalProperties, "manualPurchases")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffEconomyRegionOverviewGet200Response struct {
	value *ApiStaffEconomyRegionOverviewGet200Response
	isSet bool
}

func (v NullableApiStaffEconomyRegionOverviewGet200Response) Get() *ApiStaffEconomyRegionOverviewGet200Response {
	return v.value
}

func (v *NullableApiStaffEconomyRegionOverviewGet200Response) Set(val *ApiStaffEconomyRegionOverviewGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffEconomyRegionOverviewGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffEconomyRegionOverviewGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffEconomyRegionOverviewGet200Response(val *ApiStaffEconomyRegionOverviewGet200Response) *NullableApiStaffEconomyRegionOverviewGet200Response {
	return &NullableApiStaffEconomyRegionOverviewGet200Response{value: val, isSet: true}
}

func (v NullableApiStaffEconomyRegionOverviewGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffEconomyRegionOverviewGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


