/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiStaffEconomyRegionMarketingFundingsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffEconomyRegionMarketingFundingsPostRequest{}

// ApiStaffEconomyRegionMarketingFundingsPostRequest struct for ApiStaffEconomyRegionMarketingFundingsPostRequest
type ApiStaffEconomyRegionMarketingFundingsPostRequest struct {
	AmountMinor int64 `json:"amountMinor"`
	Reason string `json:"reason"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffEconomyRegionMarketingFundingsPostRequest ApiStaffEconomyRegionMarketingFundingsPostRequest

// NewApiStaffEconomyRegionMarketingFundingsPostRequest instantiates a new ApiStaffEconomyRegionMarketingFundingsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffEconomyRegionMarketingFundingsPostRequest(amountMinor int64, reason string) *ApiStaffEconomyRegionMarketingFundingsPostRequest {
	this := ApiStaffEconomyRegionMarketingFundingsPostRequest{}
	this.AmountMinor = amountMinor
	this.Reason = reason
	return &this
}

// NewApiStaffEconomyRegionMarketingFundingsPostRequestWithDefaults instantiates a new ApiStaffEconomyRegionMarketingFundingsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffEconomyRegionMarketingFundingsPostRequestWithDefaults() *ApiStaffEconomyRegionMarketingFundingsPostRequest {
	this := ApiStaffEconomyRegionMarketingFundingsPostRequest{}
	return &this
}

// GetAmountMinor returns the AmountMinor field value
func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) GetAmountMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value
// and a boolean to check if the value has been set.
func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) GetAmountMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountMinor, true
}

// SetAmountMinor sets field value
func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) SetAmountMinor(v int64) {
	o.AmountMinor = v
}

// GetReason returns the Reason field value
func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) SetReason(v string) {
	o.Reason = v
}

func (o ApiStaffEconomyRegionMarketingFundingsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffEconomyRegionMarketingFundingsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amountMinor"] = o.AmountMinor
	toSerialize["reason"] = o.Reason

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffEconomyRegionMarketingFundingsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amountMinor",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffEconomyRegionMarketingFundingsPostRequest := _ApiStaffEconomyRegionMarketingFundingsPostRequest{}

	err = json.Unmarshal(data, &varApiStaffEconomyRegionMarketingFundingsPostRequest)

	if err != nil {
		return err
	}

	*o = ApiStaffEconomyRegionMarketingFundingsPostRequest(varApiStaffEconomyRegionMarketingFundingsPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amountMinor")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffEconomyRegionMarketingFundingsPostRequest struct {
	value *ApiStaffEconomyRegionMarketingFundingsPostRequest
	isSet bool
}

func (v NullableApiStaffEconomyRegionMarketingFundingsPostRequest) Get() *ApiStaffEconomyRegionMarketingFundingsPostRequest {
	return v.value
}

func (v *NullableApiStaffEconomyRegionMarketingFundingsPostRequest) Set(val *ApiStaffEconomyRegionMarketingFundingsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffEconomyRegionMarketingFundingsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffEconomyRegionMarketingFundingsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffEconomyRegionMarketingFundingsPostRequest(val *ApiStaffEconomyRegionMarketingFundingsPostRequest) *NullableApiStaffEconomyRegionMarketingFundingsPostRequest {
	return &NullableApiStaffEconomyRegionMarketingFundingsPostRequest{value: val, isSet: true}
}

func (v NullableApiStaffEconomyRegionMarketingFundingsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffEconomyRegionMarketingFundingsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


