/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ApiTenantIdStudioDevelopersCredentialsPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTenantIdStudioDevelopersCredentialsPost201Response{}

// ApiTenantIdStudioDevelopersCredentialsPost201Response struct for ApiTenantIdStudioDevelopersCredentialsPost201Response
type ApiTenantIdStudioDevelopersCredentialsPost201Response struct {
	CredentialId string `json:"credentialId"`
	Label string `json:"label"`
	Sandbox bool `json:"sandbox"`
	State string `json:"state"`
	Secret *string `json:"secret,omitempty"`
	IssuedAt time.Time `json:"issuedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _ApiTenantIdStudioDevelopersCredentialsPost201Response ApiTenantIdStudioDevelopersCredentialsPost201Response

// NewApiTenantIdStudioDevelopersCredentialsPost201Response instantiates a new ApiTenantIdStudioDevelopersCredentialsPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTenantIdStudioDevelopersCredentialsPost201Response(credentialId string, label string, sandbox bool, state string, issuedAt time.Time) *ApiTenantIdStudioDevelopersCredentialsPost201Response {
	this := ApiTenantIdStudioDevelopersCredentialsPost201Response{}
	this.CredentialId = credentialId
	this.Label = label
	this.Sandbox = sandbox
	this.State = state
	this.IssuedAt = issuedAt
	return &this
}

// NewApiTenantIdStudioDevelopersCredentialsPost201ResponseWithDefaults instantiates a new ApiTenantIdStudioDevelopersCredentialsPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTenantIdStudioDevelopersCredentialsPost201ResponseWithDefaults() *ApiTenantIdStudioDevelopersCredentialsPost201Response {
	this := ApiTenantIdStudioDevelopersCredentialsPost201Response{}
	return &this
}

// GetCredentialId returns the CredentialId field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetCredentialId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetCredentialIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialId, true
}

// SetCredentialId sets field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) SetCredentialId(v string) {
	o.CredentialId = v
}

// GetLabel returns the Label field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) SetLabel(v string) {
	o.Label = v
}

// GetSandbox returns the Sandbox field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetSandbox() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetSandboxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sandbox, true
}

// SetSandbox sets field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) SetSandbox(v bool) {
	o.Sandbox = v
}

// GetState returns the State field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) SetState(v string) {
	o.State = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) SetSecret(v string) {
	o.Secret = &v
}

// GetIssuedAt returns the IssuedAt field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetIssuedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.IssuedAt
}

// GetIssuedAtOk returns a tuple with the IssuedAt field value
// and a boolean to check if the value has been set.
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) GetIssuedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuedAt, true
}

// SetIssuedAt sets field value
func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) SetIssuedAt(v time.Time) {
	o.IssuedAt = v
}

func (o ApiTenantIdStudioDevelopersCredentialsPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTenantIdStudioDevelopersCredentialsPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credentialId"] = o.CredentialId
	toSerialize["label"] = o.Label
	toSerialize["sandbox"] = o.Sandbox
	toSerialize["state"] = o.State
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	toSerialize["issuedAt"] = o.IssuedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiTenantIdStudioDevelopersCredentialsPost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credentialId",
		"label",
		"sandbox",
		"state",
		"issuedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTenantIdStudioDevelopersCredentialsPost201Response := _ApiTenantIdStudioDevelopersCredentialsPost201Response{}

	err = json.Unmarshal(data, &varApiTenantIdStudioDevelopersCredentialsPost201Response)

	if err != nil {
		return err
	}

	*o = ApiTenantIdStudioDevelopersCredentialsPost201Response(varApiTenantIdStudioDevelopersCredentialsPost201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "credentialId")
		delete(additionalProperties, "label")
		delete(additionalProperties, "sandbox")
		delete(additionalProperties, "state")
		delete(additionalProperties, "secret")
		delete(additionalProperties, "issuedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiTenantIdStudioDevelopersCredentialsPost201Response struct {
	value *ApiTenantIdStudioDevelopersCredentialsPost201Response
	isSet bool
}

func (v NullableApiTenantIdStudioDevelopersCredentialsPost201Response) Get() *ApiTenantIdStudioDevelopersCredentialsPost201Response {
	return v.value
}

func (v *NullableApiTenantIdStudioDevelopersCredentialsPost201Response) Set(val *ApiTenantIdStudioDevelopersCredentialsPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTenantIdStudioDevelopersCredentialsPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTenantIdStudioDevelopersCredentialsPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTenantIdStudioDevelopersCredentialsPost201Response(val *ApiTenantIdStudioDevelopersCredentialsPost201Response) *NullableApiTenantIdStudioDevelopersCredentialsPost201Response {
	return &NullableApiTenantIdStudioDevelopersCredentialsPost201Response{value: val, isSet: true}
}

func (v NullableApiTenantIdStudioDevelopersCredentialsPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTenantIdStudioDevelopersCredentialsPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


