/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiCounterAuthorizePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCounterAuthorizePostRequest{}

// ApiCounterAuthorizePostRequest struct for ApiCounterAuthorizePostRequest
type ApiCounterAuthorizePostRequest struct {
	Code string `json:"code"`
	AmountMinor *int64 `json:"amountMinor,omitempty"`
	Currency string `json:"currency"`
	OrderRef string `json:"orderRef"`
	OrderTotalMinor int64 `json:"orderTotalMinor"`
	AdditionalProperties map[string]interface{}
}

type _ApiCounterAuthorizePostRequest ApiCounterAuthorizePostRequest

// NewApiCounterAuthorizePostRequest instantiates a new ApiCounterAuthorizePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCounterAuthorizePostRequest(code string, currency string, orderRef string, orderTotalMinor int64) *ApiCounterAuthorizePostRequest {
	this := ApiCounterAuthorizePostRequest{}
	this.Code = code
	this.Currency = currency
	this.OrderRef = orderRef
	this.OrderTotalMinor = orderTotalMinor
	return &this
}

// NewApiCounterAuthorizePostRequestWithDefaults instantiates a new ApiCounterAuthorizePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCounterAuthorizePostRequestWithDefaults() *ApiCounterAuthorizePostRequest {
	this := ApiCounterAuthorizePostRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *ApiCounterAuthorizePostRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ApiCounterAuthorizePostRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ApiCounterAuthorizePostRequest) SetCode(v string) {
	o.Code = v
}

// GetAmountMinor returns the AmountMinor field value if set, zero value otherwise.
func (o *ApiCounterAuthorizePostRequest) GetAmountMinor() int64 {
	if o == nil || IsNil(o.AmountMinor) {
		var ret int64
		return ret
	}
	return *o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCounterAuthorizePostRequest) GetAmountMinorOk() (*int64, bool) {
	if o == nil || IsNil(o.AmountMinor) {
		return nil, false
	}
	return o.AmountMinor, true
}

// HasAmountMinor returns a boolean if a field has been set.
func (o *ApiCounterAuthorizePostRequest) HasAmountMinor() bool {
	if o != nil && !IsNil(o.AmountMinor) {
		return true
	}

	return false
}

// SetAmountMinor gets a reference to the given int64 and assigns it to the AmountMinor field.
func (o *ApiCounterAuthorizePostRequest) SetAmountMinor(v int64) {
	o.AmountMinor = &v
}

// GetCurrency returns the Currency field value
func (o *ApiCounterAuthorizePostRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ApiCounterAuthorizePostRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ApiCounterAuthorizePostRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetOrderRef returns the OrderRef field value
func (o *ApiCounterAuthorizePostRequest) GetOrderRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderRef
}

// GetOrderRefOk returns a tuple with the OrderRef field value
// and a boolean to check if the value has been set.
func (o *ApiCounterAuthorizePostRequest) GetOrderRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderRef, true
}

// SetOrderRef sets field value
func (o *ApiCounterAuthorizePostRequest) SetOrderRef(v string) {
	o.OrderRef = v
}

// GetOrderTotalMinor returns the OrderTotalMinor field value
func (o *ApiCounterAuthorizePostRequest) GetOrderTotalMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrderTotalMinor
}

// GetOrderTotalMinorOk returns a tuple with the OrderTotalMinor field value
// and a boolean to check if the value has been set.
func (o *ApiCounterAuthorizePostRequest) GetOrderTotalMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderTotalMinor, true
}

// SetOrderTotalMinor sets field value
func (o *ApiCounterAuthorizePostRequest) SetOrderTotalMinor(v int64) {
	o.OrderTotalMinor = v
}

func (o ApiCounterAuthorizePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCounterAuthorizePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.AmountMinor) {
		toSerialize["amountMinor"] = o.AmountMinor
	}
	toSerialize["currency"] = o.Currency
	toSerialize["orderRef"] = o.OrderRef
	toSerialize["orderTotalMinor"] = o.OrderTotalMinor

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiCounterAuthorizePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"currency",
		"orderRef",
		"orderTotalMinor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiCounterAuthorizePostRequest := _ApiCounterAuthorizePostRequest{}

	err = json.Unmarshal(data, &varApiCounterAuthorizePostRequest)

	if err != nil {
		return err
	}

	*o = ApiCounterAuthorizePostRequest(varApiCounterAuthorizePostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "amountMinor")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "orderRef")
		delete(additionalProperties, "orderTotalMinor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiCounterAuthorizePostRequest struct {
	value *ApiCounterAuthorizePostRequest
	isSet bool
}

func (v NullableApiCounterAuthorizePostRequest) Get() *ApiCounterAuthorizePostRequest {
	return v.value
}

func (v *NullableApiCounterAuthorizePostRequest) Set(val *ApiCounterAuthorizePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCounterAuthorizePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCounterAuthorizePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCounterAuthorizePostRequest(val *ApiCounterAuthorizePostRequest) *NullableApiCounterAuthorizePostRequest {
	return &NullableApiCounterAuthorizePostRequest{value: val, isSet: true}
}

func (v NullableApiCounterAuthorizePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCounterAuthorizePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


