/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BoostCharge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoostCharge{}

// BoostCharge One closed day's boost spend, charged in cash through the payment driver.
type BoostCharge struct {
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	CampaignId string `json:"campaignId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	CampaignTitle string `json:"campaignTitle"`
	Day string `json:"day" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"`
	Impressions int64 `json:"impressions"`
	// A whole number of some currency's minor unit, WITHOUT saying which (YT-0513). The currency is a sibling field on the same record — listingSchema.currency, voucherSchema.currency — one per record, so an amount can never be stored without its currency and two amounts on one record can never disagree. This replaced IdrMinorUnits on the wire: that brand named a currency it did not always hold, and AU fixtures stored AUD cents in a field typed IdrMinorUnits. Not a nested Money object, because the contracts-to-migrations drift gate maps each field to a snake_case column and a nested object needs columns corresponding to nothing; callers compose money(record.fooMinor, record.currency) at the point of use.
	AmountMinor int64 `json:"amountMinor"`
	Currency Currency `json:"currency"`
	ProviderReference string `json:"providerReference"`
	ChargedAt time.Time `json:"chargedAt" validate:"regexp=^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"`
}

type _BoostCharge BoostCharge

// NewBoostCharge instantiates a new BoostCharge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoostCharge(id string, campaignId string, campaignTitle string, day string, impressions int64, amountMinor int64, currency Currency, providerReference string, chargedAt time.Time) *BoostCharge {
	this := BoostCharge{}
	this.Id = id
	this.CampaignId = campaignId
	this.CampaignTitle = campaignTitle
	this.Day = day
	this.Impressions = impressions
	this.AmountMinor = amountMinor
	this.Currency = currency
	this.ProviderReference = providerReference
	this.ChargedAt = chargedAt
	return &this
}

// NewBoostChargeWithDefaults instantiates a new BoostCharge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoostChargeWithDefaults() *BoostCharge {
	this := BoostCharge{}
	return &this
}

// GetId returns the Id field value
func (o *BoostCharge) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BoostCharge) SetId(v string) {
	o.Id = v
}

// GetCampaignId returns the CampaignId field value
func (o *BoostCharge) GetCampaignId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetCampaignIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *BoostCharge) SetCampaignId(v string) {
	o.CampaignId = v
}

// GetCampaignTitle returns the CampaignTitle field value
func (o *BoostCharge) GetCampaignTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignTitle
}

// GetCampaignTitleOk returns a tuple with the CampaignTitle field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetCampaignTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignTitle, true
}

// SetCampaignTitle sets field value
func (o *BoostCharge) SetCampaignTitle(v string) {
	o.CampaignTitle = v
}

// GetDay returns the Day field value
func (o *BoostCharge) GetDay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetDayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *BoostCharge) SetDay(v string) {
	o.Day = v
}

// GetImpressions returns the Impressions field value
func (o *BoostCharge) GetImpressions() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Impressions
}

// GetImpressionsOk returns a tuple with the Impressions field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetImpressionsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Impressions, true
}

// SetImpressions sets field value
func (o *BoostCharge) SetImpressions(v int64) {
	o.Impressions = v
}

// GetAmountMinor returns the AmountMinor field value
func (o *BoostCharge) GetAmountMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetAmountMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountMinor, true
}

// SetAmountMinor sets field value
func (o *BoostCharge) SetAmountMinor(v int64) {
	o.AmountMinor = v
}

// GetCurrency returns the Currency field value
func (o *BoostCharge) GetCurrency() Currency {
	if o == nil {
		var ret Currency
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetCurrencyOk() (*Currency, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *BoostCharge) SetCurrency(v Currency) {
	o.Currency = v
}

// GetProviderReference returns the ProviderReference field value
func (o *BoostCharge) GetProviderReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderReference
}

// GetProviderReferenceOk returns a tuple with the ProviderReference field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetProviderReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderReference, true
}

// SetProviderReference sets field value
func (o *BoostCharge) SetProviderReference(v string) {
	o.ProviderReference = v
}

// GetChargedAt returns the ChargedAt field value
func (o *BoostCharge) GetChargedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ChargedAt
}

// GetChargedAtOk returns a tuple with the ChargedAt field value
// and a boolean to check if the value has been set.
func (o *BoostCharge) GetChargedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChargedAt, true
}

// SetChargedAt sets field value
func (o *BoostCharge) SetChargedAt(v time.Time) {
	o.ChargedAt = v
}

func (o BoostCharge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoostCharge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["campaignId"] = o.CampaignId
	toSerialize["campaignTitle"] = o.CampaignTitle
	toSerialize["day"] = o.Day
	toSerialize["impressions"] = o.Impressions
	toSerialize["amountMinor"] = o.AmountMinor
	toSerialize["currency"] = o.Currency
	toSerialize["providerReference"] = o.ProviderReference
	toSerialize["chargedAt"] = o.ChargedAt
	return toSerialize, nil
}

func (o *BoostCharge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"campaignId",
		"campaignTitle",
		"day",
		"impressions",
		"amountMinor",
		"currency",
		"providerReference",
		"chargedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoostCharge := _BoostCharge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBoostCharge)

	if err != nil {
		return err
	}

	*o = BoostCharge(varBoostCharge)

	return err
}

type NullableBoostCharge struct {
	value *BoostCharge
	isSet bool
}

func (v NullableBoostCharge) Get() *BoostCharge {
	return v.value
}

func (v *NullableBoostCharge) Set(val *BoostCharge) {
	v.value = val
	v.isSet = true
}

func (v NullableBoostCharge) IsSet() bool {
	return v.isSet
}

func (v *NullableBoostCharge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoostCharge(val *BoostCharge) *NullableBoostCharge {
	return &NullableBoostCharge{value: val, isSet: true}
}

func (v NullableBoostCharge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoostCharge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


