/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiHealthGet200ResponseChecksPostgresOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiHealthGet200ResponseChecksPostgresOneOf1{}

// ApiHealthGet200ResponseChecksPostgresOneOf1 struct for ApiHealthGet200ResponseChecksPostgresOneOf1
type ApiHealthGet200ResponseChecksPostgresOneOf1 struct {
	Status string `json:"status"`
	LatencyMs float32 `json:"latencyMs"`
	Error string `json:"error"`
	AdditionalProperties map[string]interface{}
}

type _ApiHealthGet200ResponseChecksPostgresOneOf1 ApiHealthGet200ResponseChecksPostgresOneOf1

// NewApiHealthGet200ResponseChecksPostgresOneOf1 instantiates a new ApiHealthGet200ResponseChecksPostgresOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiHealthGet200ResponseChecksPostgresOneOf1(status string, latencyMs float32, error_ string) *ApiHealthGet200ResponseChecksPostgresOneOf1 {
	this := ApiHealthGet200ResponseChecksPostgresOneOf1{}
	this.Status = status
	this.LatencyMs = latencyMs
	this.Error = error_
	return &this
}

// NewApiHealthGet200ResponseChecksPostgresOneOf1WithDefaults instantiates a new ApiHealthGet200ResponseChecksPostgresOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiHealthGet200ResponseChecksPostgresOneOf1WithDefaults() *ApiHealthGet200ResponseChecksPostgresOneOf1 {
	this := ApiHealthGet200ResponseChecksPostgresOneOf1{}
	return &this
}

// GetStatus returns the Status field value
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) SetStatus(v string) {
	o.Status = v
}

// GetLatencyMs returns the LatencyMs field value
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) GetLatencyMs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LatencyMs
}

// GetLatencyMsOk returns a tuple with the LatencyMs field value
// and a boolean to check if the value has been set.
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) GetLatencyMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatencyMs, true
}

// SetLatencyMs sets field value
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) SetLatencyMs(v float32) {
	o.LatencyMs = v
}

// GetError returns the Error field value
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) SetError(v string) {
	o.Error = v
}

func (o ApiHealthGet200ResponseChecksPostgresOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiHealthGet200ResponseChecksPostgresOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["latencyMs"] = o.LatencyMs
	toSerialize["error"] = o.Error

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiHealthGet200ResponseChecksPostgresOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"latencyMs",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiHealthGet200ResponseChecksPostgresOneOf1 := _ApiHealthGet200ResponseChecksPostgresOneOf1{}

	err = json.Unmarshal(data, &varApiHealthGet200ResponseChecksPostgresOneOf1)

	if err != nil {
		return err
	}

	*o = ApiHealthGet200ResponseChecksPostgresOneOf1(varApiHealthGet200ResponseChecksPostgresOneOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "latencyMs")
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiHealthGet200ResponseChecksPostgresOneOf1 struct {
	value *ApiHealthGet200ResponseChecksPostgresOneOf1
	isSet bool
}

func (v NullableApiHealthGet200ResponseChecksPostgresOneOf1) Get() *ApiHealthGet200ResponseChecksPostgresOneOf1 {
	return v.value
}

func (v *NullableApiHealthGet200ResponseChecksPostgresOneOf1) Set(val *ApiHealthGet200ResponseChecksPostgresOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableApiHealthGet200ResponseChecksPostgresOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableApiHealthGet200ResponseChecksPostgresOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiHealthGet200ResponseChecksPostgresOneOf1(val *ApiHealthGet200ResponseChecksPostgresOneOf1) *NullableApiHealthGet200ResponseChecksPostgresOneOf1 {
	return &NullableApiHealthGet200ResponseChecksPostgresOneOf1{value: val, isSet: true}
}

func (v NullableApiHealthGet200ResponseChecksPostgresOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiHealthGet200ResponseChecksPostgresOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


