/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiDevClockJobsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDevClockJobsGet200Response{}

// ApiDevClockJobsGet200Response struct for ApiDevClockJobsGet200Response
type ApiDevClockJobsGet200Response struct {
	Jobs []ApiDevClockJobsGet200ResponseJobsInner `json:"jobs"`
	AdditionalProperties map[string]interface{}
}

type _ApiDevClockJobsGet200Response ApiDevClockJobsGet200Response

// NewApiDevClockJobsGet200Response instantiates a new ApiDevClockJobsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDevClockJobsGet200Response(jobs []ApiDevClockJobsGet200ResponseJobsInner) *ApiDevClockJobsGet200Response {
	this := ApiDevClockJobsGet200Response{}
	this.Jobs = jobs
	return &this
}

// NewApiDevClockJobsGet200ResponseWithDefaults instantiates a new ApiDevClockJobsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDevClockJobsGet200ResponseWithDefaults() *ApiDevClockJobsGet200Response {
	this := ApiDevClockJobsGet200Response{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *ApiDevClockJobsGet200Response) GetJobs() []ApiDevClockJobsGet200ResponseJobsInner {
	if o == nil {
		var ret []ApiDevClockJobsGet200ResponseJobsInner
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *ApiDevClockJobsGet200Response) GetJobsOk() ([]ApiDevClockJobsGet200ResponseJobsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *ApiDevClockJobsGet200Response) SetJobs(v []ApiDevClockJobsGet200ResponseJobsInner) {
	o.Jobs = v
}

func (o ApiDevClockJobsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDevClockJobsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiDevClockJobsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiDevClockJobsGet200Response := _ApiDevClockJobsGet200Response{}

	err = json.Unmarshal(data, &varApiDevClockJobsGet200Response)

	if err != nil {
		return err
	}

	*o = ApiDevClockJobsGet200Response(varApiDevClockJobsGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "jobs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiDevClockJobsGet200Response struct {
	value *ApiDevClockJobsGet200Response
	isSet bool
}

func (v NullableApiDevClockJobsGet200Response) Get() *ApiDevClockJobsGet200Response {
	return v.value
}

func (v *NullableApiDevClockJobsGet200Response) Set(val *ApiDevClockJobsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDevClockJobsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDevClockJobsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDevClockJobsGet200Response(val *ApiDevClockJobsGet200Response) *NullableApiDevClockJobsGet200Response {
	return &NullableApiDevClockJobsGet200Response{value: val, isSet: true}
}

func (v NullableApiDevClockJobsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDevClockJobsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


