/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiStaffSettlementRegionQueueGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffSettlementRegionQueueGet200Response{}

// ApiStaffSettlementRegionQueueGet200Response struct for ApiStaffSettlementRegionQueueGet200Response
type ApiStaffSettlementRegionQueueGet200Response struct {
	Region NullableString `json:"region"`
	Statements []ApiStaffSettlementRegionQueueGet200ResponseStatementsInner `json:"statements"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffSettlementRegionQueueGet200Response ApiStaffSettlementRegionQueueGet200Response

// NewApiStaffSettlementRegionQueueGet200Response instantiates a new ApiStaffSettlementRegionQueueGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffSettlementRegionQueueGet200Response(region NullableString, statements []ApiStaffSettlementRegionQueueGet200ResponseStatementsInner) *ApiStaffSettlementRegionQueueGet200Response {
	this := ApiStaffSettlementRegionQueueGet200Response{}
	this.Region = region
	this.Statements = statements
	return &this
}

// NewApiStaffSettlementRegionQueueGet200ResponseWithDefaults instantiates a new ApiStaffSettlementRegionQueueGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffSettlementRegionQueueGet200ResponseWithDefaults() *ApiStaffSettlementRegionQueueGet200Response {
	this := ApiStaffSettlementRegionQueueGet200Response{}
	return &this
}

// GetRegion returns the Region field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffSettlementRegionQueueGet200Response) GetRegion() string {
	if o == nil || o.Region.Get() == nil {
		var ret string
		return ret
	}

	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffSettlementRegionQueueGet200Response) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// SetRegion sets field value
func (o *ApiStaffSettlementRegionQueueGet200Response) SetRegion(v string) {
	o.Region.Set(&v)
}

// GetStatements returns the Statements field value
func (o *ApiStaffSettlementRegionQueueGet200Response) GetStatements() []ApiStaffSettlementRegionQueueGet200ResponseStatementsInner {
	if o == nil {
		var ret []ApiStaffSettlementRegionQueueGet200ResponseStatementsInner
		return ret
	}

	return o.Statements
}

// GetStatementsOk returns a tuple with the Statements field value
// and a boolean to check if the value has been set.
func (o *ApiStaffSettlementRegionQueueGet200Response) GetStatementsOk() ([]ApiStaffSettlementRegionQueueGet200ResponseStatementsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Statements, true
}

// SetStatements sets field value
func (o *ApiStaffSettlementRegionQueueGet200Response) SetStatements(v []ApiStaffSettlementRegionQueueGet200ResponseStatementsInner) {
	o.Statements = v
}

func (o ApiStaffSettlementRegionQueueGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffSettlementRegionQueueGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["region"] = o.Region.Get()
	toSerialize["statements"] = o.Statements

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffSettlementRegionQueueGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"region",
		"statements",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffSettlementRegionQueueGet200Response := _ApiStaffSettlementRegionQueueGet200Response{}

	err = json.Unmarshal(data, &varApiStaffSettlementRegionQueueGet200Response)

	if err != nil {
		return err
	}

	*o = ApiStaffSettlementRegionQueueGet200Response(varApiStaffSettlementRegionQueueGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "region")
		delete(additionalProperties, "statements")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffSettlementRegionQueueGet200Response struct {
	value *ApiStaffSettlementRegionQueueGet200Response
	isSet bool
}

func (v NullableApiStaffSettlementRegionQueueGet200Response) Get() *ApiStaffSettlementRegionQueueGet200Response {
	return v.value
}

func (v *NullableApiStaffSettlementRegionQueueGet200Response) Set(val *ApiStaffSettlementRegionQueueGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffSettlementRegionQueueGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffSettlementRegionQueueGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffSettlementRegionQueueGet200Response(val *ApiStaffSettlementRegionQueueGet200Response) *NullableApiStaffSettlementRegionQueueGet200Response {
	return &NullableApiStaffSettlementRegionQueueGet200Response{value: val, isSet: true}
}

func (v NullableApiStaffSettlementRegionQueueGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffSettlementRegionQueueGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


