/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiStaffModerationVoucherBatchesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffModerationVoucherBatchesGet200Response{}

// ApiStaffModerationVoucherBatchesGet200Response struct for ApiStaffModerationVoucherBatchesGet200Response
type ApiStaffModerationVoucherBatchesGet200Response struct {
	Requests []ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner `json:"requests"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffModerationVoucherBatchesGet200Response ApiStaffModerationVoucherBatchesGet200Response

// NewApiStaffModerationVoucherBatchesGet200Response instantiates a new ApiStaffModerationVoucherBatchesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffModerationVoucherBatchesGet200Response(requests []ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) *ApiStaffModerationVoucherBatchesGet200Response {
	this := ApiStaffModerationVoucherBatchesGet200Response{}
	this.Requests = requests
	return &this
}

// NewApiStaffModerationVoucherBatchesGet200ResponseWithDefaults instantiates a new ApiStaffModerationVoucherBatchesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffModerationVoucherBatchesGet200ResponseWithDefaults() *ApiStaffModerationVoucherBatchesGet200Response {
	this := ApiStaffModerationVoucherBatchesGet200Response{}
	return &this
}

// GetRequests returns the Requests field value
func (o *ApiStaffModerationVoucherBatchesGet200Response) GetRequests() []ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner {
	if o == nil {
		var ret []ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner
		return ret
	}

	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value
// and a boolean to check if the value has been set.
func (o *ApiStaffModerationVoucherBatchesGet200Response) GetRequestsOk() ([]ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requests, true
}

// SetRequests sets field value
func (o *ApiStaffModerationVoucherBatchesGet200Response) SetRequests(v []ApiStaffModerationVoucherBatchesGet200ResponseRequestsInner) {
	o.Requests = v
}

func (o ApiStaffModerationVoucherBatchesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffModerationVoucherBatchesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requests"] = o.Requests

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffModerationVoucherBatchesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffModerationVoucherBatchesGet200Response := _ApiStaffModerationVoucherBatchesGet200Response{}

	err = json.Unmarshal(data, &varApiStaffModerationVoucherBatchesGet200Response)

	if err != nil {
		return err
	}

	*o = ApiStaffModerationVoucherBatchesGet200Response(varApiStaffModerationVoucherBatchesGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requests")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffModerationVoucherBatchesGet200Response struct {
	value *ApiStaffModerationVoucherBatchesGet200Response
	isSet bool
}

func (v NullableApiStaffModerationVoucherBatchesGet200Response) Get() *ApiStaffModerationVoucherBatchesGet200Response {
	return v.value
}

func (v *NullableApiStaffModerationVoucherBatchesGet200Response) Set(val *ApiStaffModerationVoucherBatchesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffModerationVoucherBatchesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffModerationVoucherBatchesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffModerationVoucherBatchesGet200Response(val *ApiStaffModerationVoucherBatchesGet200Response) *NullableApiStaffModerationVoucherBatchesGet200Response {
	return &NullableApiStaffModerationVoucherBatchesGet200Response{value: val, isSet: true}
}

func (v NullableApiStaffModerationVoucherBatchesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffModerationVoucherBatchesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


