/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ListingBrowseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListingBrowseResponse{}

// ListingBrowseResponse GET /api/store/listings's response: one page, the total match count and the facets (13.12.b).
type ListingBrowseResponse struct {
	Object string `json:"object"`
	Data []PublicListing `json:"data"`
	HasMore bool `json:"has_more"`
	Url string `json:"url"`
	TotalCount int64 `json:"total_count"`
	Facets ListingFacets `json:"facets"`
	AdditionalProperties map[string]interface{}
}

type _ListingBrowseResponse ListingBrowseResponse

// NewListingBrowseResponse instantiates a new ListingBrowseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListingBrowseResponse(object string, data []PublicListing, hasMore bool, url string, totalCount int64, facets ListingFacets) *ListingBrowseResponse {
	this := ListingBrowseResponse{}
	this.Object = object
	this.Data = data
	this.HasMore = hasMore
	this.Url = url
	this.TotalCount = totalCount
	this.Facets = facets
	return &this
}

// NewListingBrowseResponseWithDefaults instantiates a new ListingBrowseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListingBrowseResponseWithDefaults() *ListingBrowseResponse {
	this := ListingBrowseResponse{}
	var totalCount int64 = 0
	this.TotalCount = totalCount
	var facets ListingFacets = {"categories":[],"tags":[],"brands":[]}
	this.Facets = facets
	return &this
}

// GetObject returns the Object field value
func (o *ListingBrowseResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ListingBrowseResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ListingBrowseResponse) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value
func (o *ListingBrowseResponse) GetData() []PublicListing {
	if o == nil {
		var ret []PublicListing
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListingBrowseResponse) GetDataOk() ([]PublicListing, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListingBrowseResponse) SetData(v []PublicListing) {
	o.Data = v
}

// GetHasMore returns the HasMore field value
func (o *ListingBrowseResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListingBrowseResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListingBrowseResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetUrl returns the Url field value
func (o *ListingBrowseResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ListingBrowseResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ListingBrowseResponse) SetUrl(v string) {
	o.Url = v
}

// GetTotalCount returns the TotalCount field value
func (o *ListingBrowseResponse) GetTotalCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ListingBrowseResponse) GetTotalCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ListingBrowseResponse) SetTotalCount(v int64) {
	o.TotalCount = v
}

// GetFacets returns the Facets field value
func (o *ListingBrowseResponse) GetFacets() ListingFacets {
	if o == nil {
		var ret ListingFacets
		return ret
	}

	return o.Facets
}

// GetFacetsOk returns a tuple with the Facets field value
// and a boolean to check if the value has been set.
func (o *ListingBrowseResponse) GetFacetsOk() (*ListingFacets, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Facets, true
}

// SetFacets sets field value
func (o *ListingBrowseResponse) SetFacets(v ListingFacets) {
	o.Facets = v
}

func (o ListingBrowseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListingBrowseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["data"] = o.Data
	toSerialize["has_more"] = o.HasMore
	toSerialize["url"] = o.Url
	toSerialize["total_count"] = o.TotalCount
	toSerialize["facets"] = o.Facets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListingBrowseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"data",
		"has_more",
		"url",
		"total_count",
		"facets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListingBrowseResponse := _ListingBrowseResponse{}

	err = json.Unmarshal(data, &varListingBrowseResponse)

	if err != nil {
		return err
	}

	*o = ListingBrowseResponse(varListingBrowseResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "object")
		delete(additionalProperties, "data")
		delete(additionalProperties, "has_more")
		delete(additionalProperties, "url")
		delete(additionalProperties, "total_count")
		delete(additionalProperties, "facets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListingBrowseResponse struct {
	value *ListingBrowseResponse
	isSet bool
}

func (v NullableListingBrowseResponse) Get() *ListingBrowseResponse {
	return v.value
}

func (v *NullableListingBrowseResponse) Set(val *ListingBrowseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListingBrowseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListingBrowseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListingBrowseResponse(val *ListingBrowseResponse) *NullableListingBrowseResponse {
	return &NullableListingBrowseResponse{value: val, isSet: true}
}

func (v NullableListingBrowseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListingBrowseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


