/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CharityRegistration - A charity's registration, by region.
type CharityRegistration struct {
	AuCharityRegistration *AuCharityRegistration
	IdCharityRegistration *IdCharityRegistration
}

// AuCharityRegistrationAsCharityRegistration is a convenience function that returns AuCharityRegistration wrapped in CharityRegistration
func AuCharityRegistrationAsCharityRegistration(v *AuCharityRegistration) CharityRegistration {
	return CharityRegistration{
		AuCharityRegistration: v,
	}
}

// IdCharityRegistrationAsCharityRegistration is a convenience function that returns IdCharityRegistration wrapped in CharityRegistration
func IdCharityRegistrationAsCharityRegistration(v *IdCharityRegistration) CharityRegistration {
	return CharityRegistration{
		IdCharityRegistration: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CharityRegistration) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AuCharityRegistration
	err = newStrictDecoder(data).Decode(&dst.AuCharityRegistration)
	if err == nil {
		jsonAuCharityRegistration, _ := json.Marshal(dst.AuCharityRegistration)
		if string(jsonAuCharityRegistration) == "{}" { // empty struct
			dst.AuCharityRegistration = nil
		} else {
			if err = validator.Validate(dst.AuCharityRegistration); err != nil {
				dst.AuCharityRegistration = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuCharityRegistration = nil
	}

	// try to unmarshal data into IdCharityRegistration
	err = newStrictDecoder(data).Decode(&dst.IdCharityRegistration)
	if err == nil {
		jsonIdCharityRegistration, _ := json.Marshal(dst.IdCharityRegistration)
		if string(jsonIdCharityRegistration) == "{}" { // empty struct
			dst.IdCharityRegistration = nil
		} else {
			if err = validator.Validate(dst.IdCharityRegistration); err != nil {
				dst.IdCharityRegistration = nil
			} else {
				match++
			}
		}
	} else {
		dst.IdCharityRegistration = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AuCharityRegistration = nil
		dst.IdCharityRegistration = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CharityRegistration)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(CharityRegistration): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(CharityRegistration)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CharityRegistration) MarshalJSON() ([]byte, error) {
	if src.AuCharityRegistration != nil {
		return json.Marshal(&src.AuCharityRegistration)
	}

	if src.IdCharityRegistration != nil {
		return json.Marshal(&src.IdCharityRegistration)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CharityRegistration) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AuCharityRegistration != nil {
		return obj.AuCharityRegistration
	}

	if obj.IdCharityRegistration != nil {
		return obj.IdCharityRegistration
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CharityRegistration) GetActualInstanceValue() (interface{}) {
	if obj.AuCharityRegistration != nil {
		return *obj.AuCharityRegistration
	}

	if obj.IdCharityRegistration != nil {
		return *obj.IdCharityRegistration
	}

	// all schemas are nil
	return nil
}

type NullableCharityRegistration struct {
	value *CharityRegistration
	isSet bool
}

func (v NullableCharityRegistration) Get() *CharityRegistration {
	return v.value
}

func (v *NullableCharityRegistration) Set(val *CharityRegistration) {
	v.value = val
	v.isSet = true
}

func (v NullableCharityRegistration) IsSet() bool {
	return v.isSet
}

func (v *NullableCharityRegistration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharityRegistration(val *CharityRegistration) *NullableCharityRegistration {
	return &NullableCharityRegistration{value: val, isSet: true}
}

func (v NullableCharityRegistration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharityRegistration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


