/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.{a,b,c}.ts, one file per area (YT-0552, extended by YT-0559, split by area in 1.3.a). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.{a,b,c}.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a live controller route and a route-registry entry ever disagree, in either direction, across the whole of apps/api/src.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner{}

// ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner struct for ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner
type ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner struct {
	Id NullableString `json:"id"`
	Region NullableString `json:"region"`
	Key NullableString `json:"key"`
	Value interface{} `json:"value"`
	SetBy NullableString `json:"setBy"`
	ApprovedBy NullableString `json:"approvedBy"`
	EffectiveFrom NullableString `json:"effectiveFrom"`
	AdditionalProperties map[string]interface{}
}

type _ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner

// NewApiStaffEconomyRegionSettingsGet200ResponseCurrentInner instantiates a new ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStaffEconomyRegionSettingsGet200ResponseCurrentInner(id NullableString, region NullableString, key NullableString, value interface{}, setBy NullableString, approvedBy NullableString, effectiveFrom NullableString) *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner {
	this := ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner{}
	this.Id = id
	this.Region = region
	this.Key = key
	this.Value = value
	this.SetBy = setBy
	this.ApprovedBy = approvedBy
	this.EffectiveFrom = effectiveFrom
	return &this
}

// NewApiStaffEconomyRegionSettingsGet200ResponseCurrentInnerWithDefaults instantiates a new ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStaffEconomyRegionSettingsGet200ResponseCurrentInnerWithDefaults() *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner {
	this := ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetId(v string) {
	o.Id.Set(&v)
}

// GetRegion returns the Region field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetRegion() string {
	if o == nil || o.Region.Get() == nil {
		var ret string
		return ret
	}

	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// SetRegion sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetRegion(v string) {
	o.Region.Set(&v)
}

// GetKey returns the Key field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetKey() string {
	if o == nil || o.Key.Get() == nil {
		var ret string
		return ret
	}

	return *o.Key.Get()
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Key.Get(), o.Key.IsSet()
}

// SetKey sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetKey(v string) {
	o.Key.Set(&v)
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetValue(v interface{}) {
	o.Value = v
}

// GetSetBy returns the SetBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetSetBy() string {
	if o == nil || o.SetBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.SetBy.Get()
}

// GetSetByOk returns a tuple with the SetBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetSetByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SetBy.Get(), o.SetBy.IsSet()
}

// SetSetBy sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetSetBy(v string) {
	o.SetBy.Set(&v)
}

// GetApprovedBy returns the ApprovedBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetApprovedBy() string {
	if o == nil || o.ApprovedBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApprovedBy.Get()
}

// GetApprovedByOk returns a tuple with the ApprovedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetApprovedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApprovedBy.Get(), o.ApprovedBy.IsSet()
}

// SetApprovedBy sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetApprovedBy(v string) {
	o.ApprovedBy.Set(&v)
}

// GetEffectiveFrom returns the EffectiveFrom field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetEffectiveFrom() string {
	if o == nil || o.EffectiveFrom.Get() == nil {
		var ret string
		return ret
	}

	return *o.EffectiveFrom.Get()
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) GetEffectiveFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EffectiveFrom.Get(), o.EffectiveFrom.IsSet()
}

// SetEffectiveFrom sets field value
func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) SetEffectiveFrom(v string) {
	o.EffectiveFrom.Set(&v)
}

func (o ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	toSerialize["region"] = o.Region.Get()
	toSerialize["key"] = o.Key.Get()
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	toSerialize["setBy"] = o.SetBy.Get()
	toSerialize["approvedBy"] = o.ApprovedBy.Get()
	toSerialize["effectiveFrom"] = o.EffectiveFrom.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"region",
		"key",
		"value",
		"setBy",
		"approvedBy",
		"effectiveFrom",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStaffEconomyRegionSettingsGet200ResponseCurrentInner := _ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner{}

	err = json.Unmarshal(data, &varApiStaffEconomyRegionSettingsGet200ResponseCurrentInner)

	if err != nil {
		return err
	}

	*o = ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner(varApiStaffEconomyRegionSettingsGet200ResponseCurrentInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "region")
		delete(additionalProperties, "key")
		delete(additionalProperties, "value")
		delete(additionalProperties, "setBy")
		delete(additionalProperties, "approvedBy")
		delete(additionalProperties, "effectiveFrom")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner struct {
	value *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner
	isSet bool
}

func (v NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) Get() *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner {
	return v.value
}

func (v *NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) Set(val *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner(val *ApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) *NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner {
	return &NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner{value: val, isSet: true}
}

func (v NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStaffEconomyRegionSettingsGet200ResponseCurrentInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


