/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552). Do not edit by hand.  `paths` covers every route the business module serves (apps/api/src/modules/business), hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the campaign and watch modules are separate, concurrently in-flight streams (YT-0101/YT-0120/YT-0548) this ticket did not give a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a business-module controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// CampaignStatus Lifecycle state as a viewer sees it.
type CampaignStatus string

// List of CampaignStatus
const (
	CAMPAIGNSTATUS_ACTIVE CampaignStatus = "active"
	CAMPAIGNSTATUS_PAUSED CampaignStatus = "paused"
	CAMPAIGNSTATUS_ENDED CampaignStatus = "ended"
)

// All allowed values of CampaignStatus enum
var AllowedCampaignStatusEnumValues = []CampaignStatus{
	"active",
	"paused",
	"ended",
}

func (v *CampaignStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CampaignStatus(value)
	for _, existing := range AllowedCampaignStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CampaignStatus", value)
}

// NewCampaignStatusFromValue returns a pointer to a valid CampaignStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCampaignStatusFromValue(v string) (*CampaignStatus, error) {
	ev := CampaignStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CampaignStatus: valid values are %v", v, AllowedCampaignStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CampaignStatus) IsValid() bool {
	for _, existing := range AllowedCampaignStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CampaignStatus value
func (v CampaignStatus) Ptr() *CampaignStatus {
	return &v
}

type NullableCampaignStatus struct {
	value *CampaignStatus
	isSet bool
}

func (v NullableCampaignStatus) Get() *CampaignStatus {
	return v.value
}

func (v *NullableCampaignStatus) Set(val *CampaignStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignStatus(val *CampaignStatus) *NullableCampaignStatus {
	return &NullableCampaignStatus{value: val, isSet: true}
}

func (v NullableCampaignStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

