/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ApiWatchSessionsSessionIdProgressPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiWatchSessionsSessionIdProgressPostRequest{}

// ApiWatchSessionsSessionIdProgressPostRequest struct for ApiWatchSessionsSessionIdProgressPostRequest
type ApiWatchSessionsSessionIdProgressPostRequest struct {
	FromSeconds float32 `json:"fromSeconds"`
	ToSeconds float32 `json:"toSeconds"`
	ReportedAt time.Time `json:"reportedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d:[0-5]\\\\d(?:\\\\.\\\\d+)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _ApiWatchSessionsSessionIdProgressPostRequest ApiWatchSessionsSessionIdProgressPostRequest

// NewApiWatchSessionsSessionIdProgressPostRequest instantiates a new ApiWatchSessionsSessionIdProgressPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWatchSessionsSessionIdProgressPostRequest(fromSeconds float32, toSeconds float32, reportedAt time.Time) *ApiWatchSessionsSessionIdProgressPostRequest {
	this := ApiWatchSessionsSessionIdProgressPostRequest{}
	this.FromSeconds = fromSeconds
	this.ToSeconds = toSeconds
	this.ReportedAt = reportedAt
	return &this
}

// NewApiWatchSessionsSessionIdProgressPostRequestWithDefaults instantiates a new ApiWatchSessionsSessionIdProgressPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWatchSessionsSessionIdProgressPostRequestWithDefaults() *ApiWatchSessionsSessionIdProgressPostRequest {
	this := ApiWatchSessionsSessionIdProgressPostRequest{}
	return &this
}

// GetFromSeconds returns the FromSeconds field value
func (o *ApiWatchSessionsSessionIdProgressPostRequest) GetFromSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FromSeconds
}

// GetFromSecondsOk returns a tuple with the FromSeconds field value
// and a boolean to check if the value has been set.
func (o *ApiWatchSessionsSessionIdProgressPostRequest) GetFromSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromSeconds, true
}

// SetFromSeconds sets field value
func (o *ApiWatchSessionsSessionIdProgressPostRequest) SetFromSeconds(v float32) {
	o.FromSeconds = v
}

// GetToSeconds returns the ToSeconds field value
func (o *ApiWatchSessionsSessionIdProgressPostRequest) GetToSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ToSeconds
}

// GetToSecondsOk returns a tuple with the ToSeconds field value
// and a boolean to check if the value has been set.
func (o *ApiWatchSessionsSessionIdProgressPostRequest) GetToSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToSeconds, true
}

// SetToSeconds sets field value
func (o *ApiWatchSessionsSessionIdProgressPostRequest) SetToSeconds(v float32) {
	o.ToSeconds = v
}

// GetReportedAt returns the ReportedAt field value
func (o *ApiWatchSessionsSessionIdProgressPostRequest) GetReportedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReportedAt
}

// GetReportedAtOk returns a tuple with the ReportedAt field value
// and a boolean to check if the value has been set.
func (o *ApiWatchSessionsSessionIdProgressPostRequest) GetReportedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportedAt, true
}

// SetReportedAt sets field value
func (o *ApiWatchSessionsSessionIdProgressPostRequest) SetReportedAt(v time.Time) {
	o.ReportedAt = v
}

func (o ApiWatchSessionsSessionIdProgressPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiWatchSessionsSessionIdProgressPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromSeconds"] = o.FromSeconds
	toSerialize["toSeconds"] = o.ToSeconds
	toSerialize["reportedAt"] = o.ReportedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiWatchSessionsSessionIdProgressPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromSeconds",
		"toSeconds",
		"reportedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiWatchSessionsSessionIdProgressPostRequest := _ApiWatchSessionsSessionIdProgressPostRequest{}

	err = json.Unmarshal(data, &varApiWatchSessionsSessionIdProgressPostRequest)

	if err != nil {
		return err
	}

	*o = ApiWatchSessionsSessionIdProgressPostRequest(varApiWatchSessionsSessionIdProgressPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fromSeconds")
		delete(additionalProperties, "toSeconds")
		delete(additionalProperties, "reportedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiWatchSessionsSessionIdProgressPostRequest struct {
	value *ApiWatchSessionsSessionIdProgressPostRequest
	isSet bool
}

func (v NullableApiWatchSessionsSessionIdProgressPostRequest) Get() *ApiWatchSessionsSessionIdProgressPostRequest {
	return v.value
}

func (v *NullableApiWatchSessionsSessionIdProgressPostRequest) Set(val *ApiWatchSessionsSessionIdProgressPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWatchSessionsSessionIdProgressPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWatchSessionsSessionIdProgressPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWatchSessionsSessionIdProgressPostRequest(val *ApiWatchSessionsSessionIdProgressPostRequest) *NullableApiWatchSessionsSessionIdProgressPostRequest {
	return &NullableApiWatchSessionsSessionIdProgressPostRequest{value: val, isSet: true}
}

func (v NullableApiWatchSessionsSessionIdProgressPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWatchSessionsSessionIdProgressPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


