/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)

// VoucherLifecycleState A voucher's INTERNAL lifecycle, owned by the voucher service (YT-0142). Distinct from VoucherStatus: 'minted' (issued, belongs to nobody) and 'held' (an authorization is outstanding against it) are facts no wallet should render. 'redeemed' and 'voided' are terminal — reviving a spent voucher would mean a state write can un-spend money, and a voided voucher that can come back makes the kill switch advisory. The one reversal is expired->active, inside a grace window, so an expiry job that ran against a wrong clock is recoverable.
type VoucherLifecycleState string

// List of VoucherLifecycleState
const (
	VOUCHERLIFECYCLESTATE_MINTED VoucherLifecycleState = "minted"
	VOUCHERLIFECYCLESTATE_ALLOCATED VoucherLifecycleState = "allocated"
	VOUCHERLIFECYCLESTATE_ACTIVE VoucherLifecycleState = "active"
	VOUCHERLIFECYCLESTATE_HELD VoucherLifecycleState = "held"
	VOUCHERLIFECYCLESTATE_REDEEMED VoucherLifecycleState = "redeemed"
	VOUCHERLIFECYCLESTATE_EXPIRED VoucherLifecycleState = "expired"
	VOUCHERLIFECYCLESTATE_VOIDED VoucherLifecycleState = "voided"
)

// All allowed values of VoucherLifecycleState enum
var AllowedVoucherLifecycleStateEnumValues = []VoucherLifecycleState{
	"minted",
	"allocated",
	"active",
	"held",
	"redeemed",
	"expired",
	"voided",
}

func (v *VoucherLifecycleState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VoucherLifecycleState(value)
	for _, existing := range AllowedVoucherLifecycleStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VoucherLifecycleState", value)
}

// NewVoucherLifecycleStateFromValue returns a pointer to a valid VoucherLifecycleState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVoucherLifecycleStateFromValue(v string) (*VoucherLifecycleState, error) {
	ev := VoucherLifecycleState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VoucherLifecycleState: valid values are %v", v, AllowedVoucherLifecycleStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VoucherLifecycleState) IsValid() bool {
	for _, existing := range AllowedVoucherLifecycleStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VoucherLifecycleState value
func (v VoucherLifecycleState) Ptr() *VoucherLifecycleState {
	return &v
}

type NullableVoucherLifecycleState struct {
	value *VoucherLifecycleState
	isSet bool
}

func (v NullableVoucherLifecycleState) Get() *VoucherLifecycleState {
	return v.value
}

func (v *NullableVoucherLifecycleState) Set(val *VoucherLifecycleState) {
	v.value = val
	v.isSet = true
}

func (v NullableVoucherLifecycleState) IsSet() bool {
	return v.isSet
}

func (v *NullableVoucherLifecycleState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoucherLifecycleState(val *VoucherLifecycleState) *NullableVoucherLifecycleState {
	return &NullableVoucherLifecycleState{value: val, isSet: true}
}

func (v NullableVoucherLifecycleState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoucherLifecycleState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

