/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031) plus the route inventory in src/openapi/route-registry.ts (YT-0552, extended by YT-0559). Do not edit by hand.  `paths` covers every route the business module (apps/api/src/modules/business), campaign module, watch module (excluding its checkpoint/ sub-module) and the shared health endpoint serve, hand-declared in route-registry.ts against the live controllers rather than generated from Nest decorators — apps/api has no decorator metadata rich enough to produce accurate request/response shapes on its own. NOT every route apps/api serves: the watch module's checkpoint/ sub-module (YT-0121/YT-0122), the store module (YT-0130/YT-0131/YT-0132) and the auth module (YT-0540) are separate, concurrently in-flight streams this package has not given a contract entry — see src/openapi/route-drift.test.ts's KNOWN_OUT_OF_SCOPE ledger for exactly which routes those are and why. That same test fails CI if a documented module's controller route and a route-registry entry ever disagree, in either direction.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"fmt"
)


// ApiWatchSessionsPost403Response struct for ApiWatchSessionsPost403Response
type ApiWatchSessionsPost403Response struct {
	ApiCampaignsCampaignIdGet404Response *ApiCampaignsCampaignIdGet404Response
	ErrorResponse *ErrorResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ApiWatchSessionsPost403Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ApiCampaignsCampaignIdGet404Response
	err = json.Unmarshal(data, &dst.ApiCampaignsCampaignIdGet404Response);
	if err == nil {
		jsonApiCampaignsCampaignIdGet404Response, _ := json.Marshal(dst.ApiCampaignsCampaignIdGet404Response)
		if string(jsonApiCampaignsCampaignIdGet404Response) == "{}" { // empty struct
			dst.ApiCampaignsCampaignIdGet404Response = nil
		} else {
			return nil // data stored in dst.ApiCampaignsCampaignIdGet404Response, return on the first match
		}
	} else {
		dst.ApiCampaignsCampaignIdGet404Response = nil
	}

	// try to unmarshal JSON data into ErrorResponse
	err = json.Unmarshal(data, &dst.ErrorResponse);
	if err == nil {
		jsonErrorResponse, _ := json.Marshal(dst.ErrorResponse)
		if string(jsonErrorResponse) == "{}" { // empty struct
			dst.ErrorResponse = nil
		} else {
			return nil // data stored in dst.ErrorResponse, return on the first match
		}
	} else {
		dst.ErrorResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ApiWatchSessionsPost403Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApiWatchSessionsPost403Response) MarshalJSON() ([]byte, error) {
	if src.ApiCampaignsCampaignIdGet404Response != nil {
		return json.Marshal(&src.ApiCampaignsCampaignIdGet404Response)
	}

	if src.ErrorResponse != nil {
		return json.Marshal(&src.ErrorResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableApiWatchSessionsPost403Response struct {
	value *ApiWatchSessionsPost403Response
	isSet bool
}

func (v NullableApiWatchSessionsPost403Response) Get() *ApiWatchSessionsPost403Response {
	return v.value
}

func (v *NullableApiWatchSessionsPost403Response) Set(val *ApiWatchSessionsPost403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWatchSessionsPost403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWatchSessionsPost403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWatchSessionsPost403Response(val *ApiWatchSessionsPost403Response) *NullableApiWatchSessionsPost403Response {
	return &NullableApiWatchSessionsPost403Response{value: val, isSet: true}
}

func (v NullableApiWatchSessionsPost403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWatchSessionsPost403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


