/*
YourTal contracts

Generated from the Zod schemas in @yourtal/contracts (YT-0031). Do not edit by hand.  This document carries SCHEMAS ONLY. `paths` is empty because no API surface exists yet — endpoints arrive with apps/api (YT-0100 onward), and each will be added here as it is built.  Cross-field rules are documented per component but NOT enforced by this document. Anything that must enforce them has to run the Zod schema or re-implement and test the rule.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the KybDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KybDocument{}

// KybDocument A business's submitted KYB document and its review state (docs/17 section 5). `storageRef` is an opaque pointer to encrypted bytes; this schema does not cover the upload path itself.
type KybDocument struct {
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	BusinessId string `json:"businessId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	DocumentType KybDocumentType `json:"documentType"`
	StorageRef string `json:"storageRef"`
	Status KybDocumentStatus `json:"status"`
	ExpiresAt BusinessMemberJoinedAt `json:"expiresAt"`
	SubmittedAt time.Time `json:"submittedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d:[0-5]\\\\d(?:\\\\.\\\\d+)?(?:Z|([+-](?:[01]\\\\d|2[0-3]):[0-5]\\\\d)))$"`
	VerifiedAt BusinessMemberJoinedAt `json:"verifiedAt"`
	VerifiedByUserId KybDocumentVerifiedByUserId `json:"verifiedByUserId"`
	AdditionalProperties map[string]interface{}
}

type _KybDocument KybDocument

// NewKybDocument instantiates a new KybDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKybDocument(id string, businessId string, documentType KybDocumentType, storageRef string, status KybDocumentStatus, expiresAt BusinessMemberJoinedAt, submittedAt time.Time, verifiedAt BusinessMemberJoinedAt, verifiedByUserId KybDocumentVerifiedByUserId) *KybDocument {
	this := KybDocument{}
	this.Id = id
	this.BusinessId = businessId
	this.DocumentType = documentType
	this.StorageRef = storageRef
	this.Status = status
	this.ExpiresAt = expiresAt
	this.SubmittedAt = submittedAt
	this.VerifiedAt = verifiedAt
	this.VerifiedByUserId = verifiedByUserId
	return &this
}

// NewKybDocumentWithDefaults instantiates a new KybDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKybDocumentWithDefaults() *KybDocument {
	this := KybDocument{}
	return &this
}

// GetId returns the Id field value
func (o *KybDocument) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KybDocument) SetId(v string) {
	o.Id = v
}

// GetBusinessId returns the BusinessId field value
func (o *KybDocument) GetBusinessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessId, true
}

// SetBusinessId sets field value
func (o *KybDocument) SetBusinessId(v string) {
	o.BusinessId = v
}

// GetDocumentType returns the DocumentType field value
func (o *KybDocument) GetDocumentType() KybDocumentType {
	if o == nil {
		var ret KybDocumentType
		return ret
	}

	return o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetDocumentTypeOk() (*KybDocumentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentType, true
}

// SetDocumentType sets field value
func (o *KybDocument) SetDocumentType(v KybDocumentType) {
	o.DocumentType = v
}

// GetStorageRef returns the StorageRef field value
func (o *KybDocument) GetStorageRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageRef
}

// GetStorageRefOk returns a tuple with the StorageRef field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetStorageRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageRef, true
}

// SetStorageRef sets field value
func (o *KybDocument) SetStorageRef(v string) {
	o.StorageRef = v
}

// GetStatus returns the Status field value
func (o *KybDocument) GetStatus() KybDocumentStatus {
	if o == nil {
		var ret KybDocumentStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetStatusOk() (*KybDocumentStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KybDocument) SetStatus(v KybDocumentStatus) {
	o.Status = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *KybDocument) GetExpiresAt() BusinessMemberJoinedAt {
	if o == nil {
		var ret BusinessMemberJoinedAt
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetExpiresAtOk() (*BusinessMemberJoinedAt, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *KybDocument) SetExpiresAt(v BusinessMemberJoinedAt) {
	o.ExpiresAt = v
}

// GetSubmittedAt returns the SubmittedAt field value
func (o *KybDocument) GetSubmittedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SubmittedAt
}

// GetSubmittedAtOk returns a tuple with the SubmittedAt field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetSubmittedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubmittedAt, true
}

// SetSubmittedAt sets field value
func (o *KybDocument) SetSubmittedAt(v time.Time) {
	o.SubmittedAt = v
}

// GetVerifiedAt returns the VerifiedAt field value
func (o *KybDocument) GetVerifiedAt() BusinessMemberJoinedAt {
	if o == nil {
		var ret BusinessMemberJoinedAt
		return ret
	}

	return o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetVerifiedAtOk() (*BusinessMemberJoinedAt, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifiedAt, true
}

// SetVerifiedAt sets field value
func (o *KybDocument) SetVerifiedAt(v BusinessMemberJoinedAt) {
	o.VerifiedAt = v
}

// GetVerifiedByUserId returns the VerifiedByUserId field value
func (o *KybDocument) GetVerifiedByUserId() KybDocumentVerifiedByUserId {
	if o == nil {
		var ret KybDocumentVerifiedByUserId
		return ret
	}

	return o.VerifiedByUserId
}

// GetVerifiedByUserIdOk returns a tuple with the VerifiedByUserId field value
// and a boolean to check if the value has been set.
func (o *KybDocument) GetVerifiedByUserIdOk() (*KybDocumentVerifiedByUserId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifiedByUserId, true
}

// SetVerifiedByUserId sets field value
func (o *KybDocument) SetVerifiedByUserId(v KybDocumentVerifiedByUserId) {
	o.VerifiedByUserId = v
}

func (o KybDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KybDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["businessId"] = o.BusinessId
	toSerialize["documentType"] = o.DocumentType
	toSerialize["storageRef"] = o.StorageRef
	toSerialize["status"] = o.Status
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["submittedAt"] = o.SubmittedAt
	toSerialize["verifiedAt"] = o.VerifiedAt
	toSerialize["verifiedByUserId"] = o.VerifiedByUserId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KybDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"businessId",
		"documentType",
		"storageRef",
		"status",
		"expiresAt",
		"submittedAt",
		"verifiedAt",
		"verifiedByUserId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKybDocument := _KybDocument{}

	err = json.Unmarshal(data, &varKybDocument)

	if err != nil {
		return err
	}

	*o = KybDocument(varKybDocument)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "businessId")
		delete(additionalProperties, "documentType")
		delete(additionalProperties, "storageRef")
		delete(additionalProperties, "status")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "submittedAt")
		delete(additionalProperties, "verifiedAt")
		delete(additionalProperties, "verifiedByUserId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKybDocument struct {
	value *KybDocument
	isSet bool
}

func (v NullableKybDocument) Get() *KybDocument {
	return v.value
}

func (v *NullableKybDocument) Set(val *KybDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableKybDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableKybDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKybDocument(val *KybDocument) *NullableKybDocument {
	return &NullableKybDocument{value: val, isSet: true}
}

func (v NullableKybDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKybDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


