import type { MediaAsset, MediaRenditionBytes } from "@yourtal/contracts/studio/media";

/** The repository's own view: everything `MediaAsset` has, plus write-side bookkeeping. */
export interface MediaAssetRecord extends MediaAsset {
  readonly rawObjectKey: string;
  readonly uploadId: string;
}

export interface CreateMediaAssetInput {
  /** Generated by the caller (not the DB): the id has to exist before the raw object key can name it. */
  readonly id: string;
  readonly businessId: string;
  readonly campaignId: string;
  readonly contentType: string;
  readonly sizeBytes: number;
  readonly rawObjectKey: string;
  readonly uploadId: string;
  readonly teaserStartSeconds: number;
}

export interface MarkReadyInput {
  readonly durationSeconds: number;
  readonly aspect: string;
  readonly posterUrl: string;
  readonly teaserUrl: string;
  readonly hlsUrl: string;
  readonly captionsUrl: string | null;
  readonly renditionBytes: MediaRenditionBytes;
}

export interface MediaAssetRepository {
  create(input: CreateMediaAssetInput): Promise<MediaAssetRecord>;
  findById(assetId: string): Promise<MediaAssetRecord | null>;
  /** Scoped to the tenant, so one business can never read or complete another's asset by id. */
  findByIdForBusiness(assetId: string, businessId: string): Promise<MediaAssetRecord | null>;
  markQueued(assetId: string): Promise<void>;
  markReady(assetId: string, input: MarkReadyInput): Promise<MediaAssetRecord>;
  markFailed(assetId: string, failureReason: string): Promise<MediaAssetRecord>;
  /** 13.9.c: records the sidecar; when `useNow`, it also becomes the asset's captions. */
  setSidecarCaptions(assetId: string, url: string, useNow: boolean): Promise<MediaAssetRecord>;
  /** 13.9.c: points the campaign at captions after the media has already been written. */
  writeCampaignCaptions(campaignId: string, captionsUrl: string): Promise<void>;
  /**
   * Writes `campaign.campaigns`' own media columns (TASKS.md 7.2.b: "the
   * studio module writes the campaign's media columns", never the worker).
   * A raw statement rather than a Drizzle table import: `campaign.campaigns`
   * is a different session's Drizzle schema in this phase split
   * (apps/api/src/modules/campaign/persistence/schema/**) — this writes the
   * four columns 7.2.b names, nothing else, the same narrow-write approach
   * `media-asset-db.test-helper.ts`'s fixture insert already uses for the
   * same table.
   */
  writeCampaignMedia(
    campaignId: string,
    media: {
      posterUrl: string;
      teaserUrl: string;
      hlsUrl: string;
      captionsUrl: string | null;
      aspect: string;
      /** The 540p rendition: what a viewer on the default quality downloads. */
      estimatedBytes: number;
    },
  ): Promise<void>;
}

export const MEDIA_ASSET_REPOSITORY = Symbol("MEDIA_ASSET_REPOSITORY");
