#!/usr/bin/env node
// Single source of truth for project status.
// Parses docs/tasks/*.md, validates, and regenerates the dashboard in TASKS.md.
//   node scripts/tasks.mjs          → validate + rewrite dashboard
//   node scripts/tasks.mjs --check  → validate + fail if dashboard is stale (CI)
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TASKS_DIR = join(ROOT, 'docs', 'tasks');
const DASHBOARD = join(ROOT, 'TASKS.md');
const CHECK = process.argv.includes('--check');

const STATUSES = ['todo', 'doing', 'review', 'blocked', 'done', 'cut'];
const PHASES = ['PU', 'P-1', 'P0', 'P1', 'P2', 'P3'];
const PHASE_LABEL = {
  PU: 'Phase U · UI first  ◀ NEXT',
  'P-1': 'Phase −1 · Pilot',
  P0: 'Phase 0 · Foundations',
  P1: 'Phase 1 · Indonesia MVP',
  P2: 'Phase 2 · Depth',
  P3: 'Phase 3 · Marketplace & AU',
};

const HEAD = /^### (YT-\d{4}) · (.+)$/;
const META =
  /^`(\w+)`\s*·\s*(P-?\d|PU)\s*·\s*([a-z][a-z0-9-]*)\s*·\s*(\d+[dh])\s*(?:·\s*dep:\s*(.+?))?\s*$/;

const errors = [];
const tasks = [];

function parseFile(file) {
  const lines = readFileSync(join(TASKS_DIR, file), 'utf8').split(/\r?\n/);
  let cur = null;
  lines.forEach((line, i) => {
    const at = `${file}:${i + 1}`;
    const head = HEAD.exec(line);
    if (head) {
      cur = { id: head[1], title: head[2], file, line: i + 1, ac: 0, done: 0 };
      tasks.push(cur);
      return;
    }
    if (!cur) return;
    if (line.startsWith('`')) {
      const m = META.exec(line.trim());
      if (!m) {
        errors.push(`${at}  malformed meta line for ${cur.id}: ${line}`);
        return;
      }
      const [, status, phase, epic, est, dep] = m;
      if (!STATUSES.includes(status)) errors.push(`${at}  bad status "${status}"`);
      if (!PHASES.includes(phase)) errors.push(`${at}  bad phase "${phase}"`);
      Object.assign(cur, {
        status,
        phase,
        epic,
        est,
        deps: dep && dep.trim() !== '—' ? dep.split(',').map((d) => d.trim()) : [],
      });
      return;
    }
    if (/^\s*- \[[ x]\]/.test(line)) {
      cur.ac++;
      if (/^\s*- \[x\]/.test(line)) cur.done++;
    }
  });
}

readdirSync(TASKS_DIR)
  .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
  .sort()
  .forEach(parseFile);

// ---- validation -------------------------------------------------------------
const byId = new Map();
for (const t of tasks) {
  if (byId.has(t.id)) errors.push(`duplicate id ${t.id} (${t.file} and ${byId.get(t.id).file})`);
  byId.set(t.id, t);
  if (!t.status) errors.push(`${t.file}:${t.line}  ${t.id} has no meta line`);
  if (!t.ac) errors.push(`${t.file}:${t.line}  ${t.id} has no acceptance criteria`);
}
for (const t of tasks) {
  for (const d of t.deps ?? []) {
    if (!byId.has(d)) errors.push(`${t.id} depends on unknown task ${d}`);
  }
  if (t.status === 'done' && t.ac !== t.done) {
    errors.push(`${t.id} is done but ${t.ac - t.done} acceptance criteria are unticked`);
  }
}
// dependency cycles
const seen = new Map();
function walk(id, stack) {
  if (stack.includes(id)) return errors.push(`dependency cycle: ${[...stack, id].join(' → ')}`);
  if (seen.get(id)) return;
  seen.set(id, true);
  for (const d of byId.get(id)?.deps ?? []) walk(d, [...stack, id]);
}
for (const t of tasks) walk(t.id, []);

// ---- dashboard --------------------------------------------------------------
const pct = (n, d) => (d ? Math.round((n / d) * 100) : 0);
const open = (t) => !['done', 'cut'].includes(t.status);
const blockedBy = (t) =>
  (t.deps ?? []).filter((d) => byId.get(d) && open(byId.get(d)));

function table(rows, headers) {
  return [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ].join('\n');
}

const lines = [];
lines.push(`_Generated by \`scripts/tasks.mjs\` — do not edit by hand._`, '');

const total = tasks.filter((t) => t.status !== 'cut');
const doneAll = total.filter((t) => t.status === 'done');
lines.push(
  `**${doneAll.length} / ${total.length} tasks done (${pct(doneAll.length, total.length)}%)** · ` +
    `${tasks.filter((t) => t.status === 'doing').length} in progress · ` +
    `${tasks.filter((t) => t.status === 'blocked').length} blocked`,
  ''
);

lines.push('### By phase', '');
lines.push(
  table(
    PHASES.filter((p) => tasks.some((t) => t.phase === p)).map((p) => {
      const ts = tasks.filter((t) => t.phase === p && t.status !== 'cut');
      const d = ts.filter((t) => t.status === 'done').length;
      const bar = '█'.repeat(Math.round(pct(d, ts.length) / 10)).padEnd(10, '░');
      return [PHASE_LABEL[p], `${d}/${ts.length}`, `\`${bar}\` ${pct(d, ts.length)}%`];
    }),
    ['Phase', 'Done', 'Progress']
  ),
  ''
);

lines.push('### By epic', '');
const epics = [...new Set(tasks.map((t) => t.epic))].filter(Boolean).sort();
lines.push(
  table(
    epics.map((e) => {
      const ts = tasks.filter((t) => t.epic === e && t.status !== 'cut');
      const d = ts.filter((t) => t.status === 'done').length;
      return [`\`${e}\``, `${d}/${ts.length}`, `${pct(d, ts.length)}%`];
    }),
    ['Epic', 'Done', '%']
  ),
  ''
);

const doing = tasks.filter((t) => t.status === 'doing');
lines.push('### In progress', '');
lines.push(
  doing.length
    ? doing.map((t) => `- **${t.id}** ${t.title} — ${t.done}/${t.ac} AC`).join('\n')
    : '_Nothing in progress._',
  ''
);

const blocked = tasks.filter((t) => t.status === 'blocked');
lines.push('### Blocked', '');
lines.push(
  blocked.length
    ? blocked.map((t) => `- **${t.id}** ${t.title}`).join('\n')
    : '_Nothing blocked._',
  ''
);

const ready = tasks
  .filter((t) => t.status === 'todo' && blockedBy(t).length === 0)
  .sort((a, b) => PHASES.indexOf(a.phase) - PHASES.indexOf(b.phase) || a.id.localeCompare(b.id));
lines.push('### Ready to start (no open dependencies)', '');
lines.push(
  ready.length
    ? ready.slice(0, 25).map((t) => `- **${t.id}** \`${t.epic}\` ${t.title} · ${t.est}`).join('\n') +
        (ready.length > 25 ? `\n- _…and ${ready.length - 25} more_` : '')
    : '_Nothing ready._',
  ''
);

const waiting = tasks.filter((t) => t.status === 'todo' && blockedBy(t).length);
lines.push('### Waiting on dependencies', '');
lines.push(
  waiting.length
    ? waiting
        .slice(0, 20)
        .map((t) => `- **${t.id}** ${t.title} → waiting on ${blockedBy(t).join(', ')}`)
        .join('\n')
    : '_Nothing waiting._',
  ''
);

// ---- write ------------------------------------------------------------------
if (errors.length) {
  console.error('Task validation failed:\n' + errors.map((e) => `  ✗ ${e}`).join('\n'));
  process.exit(1);
}

const START = '<!-- AUTO:DASHBOARD -->';
const END = '<!-- /AUTO:DASHBOARD -->';
const src = readFileSync(DASHBOARD, 'utf8');
const a = src.indexOf(START);
const b = src.indexOf(END);
if (a === -1 || b === -1) {
  console.error(`TASKS.md is missing the ${START} … ${END} markers.`);
  process.exit(1);
}
const next = `${src.slice(0, a + START.length)}\n\n${lines.join('\n').trimEnd()}\n\n${src.slice(b)}`;

if (CHECK) {
  if (next !== src) {
    console.error('TASKS.md dashboard is stale. Run: node scripts/tasks.mjs');
    process.exit(1);
  }
  console.log(`✓ ${tasks.length} tasks valid, dashboard current.`);
} else {
  writeFileSync(DASHBOARD, next);
  console.log(`✓ ${tasks.length} tasks valid, dashboard regenerated.`);
}
